### ISSUE TITLE
When sharing a link that was already shared to the same subverse, ask the user if they want to share it again or not

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#107]
When a user wants to share a link to a certain subverse, but that exact same link as already been shared to that subverse, it should show the user that is trying to share it again the original discussion, so that the user can evaluate if, on that previous occasion, the correct attention was given to that link and if they think that there is still more things to discuss and the original thread seems inactive, and then ask if they still wish to share the link.

**Comment by DanielFlamino** [comment]
This is not working

https://voat.co/v/test/comments/42492

https://voat.co/v/test/comments/42493

**Comment by voat** [comment]
I just tested it and it is working. CasInG is no longer taken into account.
