### ISSUE TITLE
API controller improvements

### ISSUE THREAD

**Issue by voat** [voat/voat#11]
API controller needs to provide all relevant API functions enabling third party developers to create mobile applications, browser plugins, bots etc.

Currently, only one experimental API is implemented (http://whoaverse.com/api/defaultsubverses) which returns a list of default subverses.

**Comment by tomzorzhu** [comment]
I'd be happy to create a windows phone app for Voat, but for that to happen more APIs are required. (So as I see it this ticket is a little outdated, there are more APIs implemented: https://voat.co/api/help)

I guess for v1 this set would be enough to start in addition to the current ones:

 - login
 - subscribe, unsubscribe
 - comment (optional reply to parameter)
 - upvote/downvote post
 - upvote/downvote comment
 - submit new post

**Comment by rrohrer** [comment]
Seconding this, I was about to make a mobile app, but there aren't the APIs I need.

If there is *no one else* who can do the work... I can get a CLA filled out.

**Comment by voat** [comment]
A new API is in beta testing. This is now obsolete.

**Comment by mechabyte** [comment]
@voat any chance I could get an invite to the new API? Sent PuttitOut a PM a couple days ago but haven't heard back. My username is 'itsmatt'.

**Comment by PuttItOut** [comment]
Matt, sorry, super slammed. Hundreds of PMs.

 

Go visit the thread again. I posted the invite info there.

 

Apologies for the delay.
