### ISSUE TITLE
New feature: subscribe to domains

### ISSUE THREAD

**Issue by voat** [voat/voat#127]
Users should be able to subscribe to domains, just like they are currently able to subscribe to subverses. 

Some ideas from /u/slug on a possible implementation:

> How would your subscriptions affect your frontpage?

Perhaps we could have two "front pages". The default being the one that shows subverses, and one that shows the domain subs.

> What about duplicates where same link is posted to multiple subverses?

They should be left alone, because each link might foster different discussion.

> Should you have a special section of the site to let you manage your domain subscriptions?

Maybe a separate "tab" or something in your subverse subscriptions.

**Comment by PuttItOut** [comment]
Closed as this is not a planned feature.
