### ISSUE TITLE
Enable categorization of submissions and discussions

### ISSUE THREAD

**Issue by lastresort09** [voat/voat#136]
It would be like forums but with reddit style posting. For example, /v/science would have categories of physics, chemistry, biology, etc. If users wanted to see the top comments of any particular subdivision, say physics, they could click on the side bar, and see all submissions of that day that was under that subdivision. 

Reddit thread: http://whoaverse.com/v/ideasforwhoaverse/comments/26601

**Comment by PuttItOut** [comment]
Closed as this is not a planned feature.
