### ISSUE TITLE
Implement support for secondary custom stylesheet

### ISSUE THREAD

**Issue by voat** [voat/voat#143]
Subverse owners should be able to use two custom stylesheets for their sub:
- one for users who use light theme (default theme)
- one for users who use dark theme

**Comment by PuttItOut** [comment]
I will do this it @voat will let me... ;)

**Comment by DanielFlamino** [comment]
Yes, please. :D

**Comment by PuttItOut** [comment]
Fixed by body classes allowing single stylesheet for both themes
