### ISSUE TITLE
Separate action buttons from sorting buttons

### ISSUE THREAD

**Issue by voat** [voat/voat#201]
We need to make the action buttons more prominent and separate them from sorting buttons, perhaps like shown in this screenshot:

![separate action buttons from sorting buttons](https://cloud.githubusercontent.com/assets/3072753/5010425/065aa806-6a73-11e4-9675-0b4f78c7f5a5.png)

Similar approach should be taken for user profile page, in order to improve design consistency.

**Comment by voat** [comment]
@Nurdoidz - this might be something you could do, the same differentiation would be useful for the sidebar?

**Comment by Nurdoidz** [comment]
Glad you reminded me! I started working up some ideas for this, but I forgot to come back to it. I'm on it!
