### ISSUE TITLE
User-selectable flairs and tags when composing a new submission

### ISSUE THREAD

**Issue by voat** [voat/voat#202]
Users should be able to select a flair and a tag when composing a new submission. Subverse moderators should be able to define a list of tags and flairs which are user-selectable. This should make it easy to post to subverses which require user content classification.

**Comment by DanielFlamino** [comment]
Isn't this the same as #96 or am I missing something?

**Comment by voat** [comment]
Yes, it is essentially the same. You can update your original issue with the following sentence "Subverse moderators should be able to define a list of tags and flairs which are user-selectable." to make it clear that flairs must be defined by moderators before they can be used.

**Comment by DanielFlamino** [comment]
Done! :)
