### ISSUE TITLE
MediaWiki integration

### ISSUE THREAD

**Issue by voat** [voat/voat#213]
We need to integrate MediaWiki with WhoaVerse and allow users to create Wiki pages related to the sub they own/moderate.

The Wiki platform should be accessible by /v/subnamehere/wiki route and sub moderators should have write access. Sub moderators from other subs should not have access to wiki pages of other subs.

**Comment by moeVoat** [comment]
Is MediaWiki still the planned implementation for the wiki system?
As far as I know, that would require users to use a formatting syntax different from Markdown.

**Comment by PuttItOut** [comment]
Closed as this is not a planned feature.
