### ISSUE TITLE
Fake usernames from anon subverses are treated as real usernames in the inbox

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#257]
For example, [this comment](https://voat.co/v/DanielFlamino/comments/31772/41085). When I'm on the discussion page, if I click the "41085" username, it doesn't take me to the profile page because that's not a real username since that is an anonymous subverse. However, if I do the same thing on the inbox, it takes me to https://voat.co/u/14045, which is not a real user (as of now).

**Comment by voat** [comment]
I think this was fixed, please open a new issue if you can reproduce this.

**Comment by DanielFlamino** [comment]
Looks like it is fixed, indeed.
