### ISSUE TITLE
Add moderator comment distinguishing checkbox

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#270]
Even though [the functionality is implemented](https://github.com/voat/voat/issues/56), there is no checkbox to make it easy to distinguish moderator comments

**Comment by voat** [comment]
This seems unnecessary. 

Current behavior:
- all comments by mods are not distinguished by default

If a mod wants to distinguish a comment, the comments needs to be submitted and then distinguish button is clicked. This is far better option than cluttering the interface with a checkbox which will be used 1% of the time.
