### ISSUE TITLE
Allow unregistered users to post to subs which allow guest posts

### ISSUE THREAD

**Issue by voat** [voat/voat#272]
Subverse owners should be able to allow submissions from guests. 

In practice, all submissions from guests would show up under the same generic account.

**Comment by DanielFlamino** [comment]
This would be a neat idea, that way people don't have to register for an account if they don't want to and still participate in discussions. Perhaps use \@Guest as the account name?

**Comment by PuttItOut** [comment]
Closed as this is not a planned change.
