### ISSUE TITLE
Login area misplaced on mobile

### ISSUE THREAD

**Issue by voat** [voat/voat#278]
Paging @Nurdoidz

**Comment by voat** [comment]
![screenshot_2015-02-09-08-36-42](https://cloud.githubusercontent.com/assets/3072753/6102450/cdfe1c68-b036-11e4-8712-c5c4eb098517.png)

**Comment by Nurdoidz** [comment]
I'll get right on it. Probably has to do with some of the changes I've made yesterday. I apologize for not being thorough!
