### ISSUE TITLE
Bug: clicking on private messages button in inbox takes you to notifications if inbox has no unread messages

### ISSUE THREAD

**Issue by voat** [voat/voat#282]
When clicking on "private messages" button in inbox, user is redirected to comment replies/user mentions if the user does not have any unread private messages.

**Comment by voat** [comment]
@PuttItOut - I know you're already working on inbox revamp, just wanted to inform you about this.

**Comment by weeeasles** [comment]
I believe this has been fixed. Just tested it on my account.

**Comment by PuttItOut** [comment]
Fixed
