### ISSUE TITLE
Upvoting a comment or post changes the displayed points to ( # upvotes + # downvotes )

### ISSUE THREAD

**Issue by moeVoat** [voat/voat#284]
When a comment has X upvotes and Y downvotes, any increase (upvote or undoing a downvote) applied to a comment's points changes the displayed value from (X - Y) to (X + Y) until the page is reloaded.

e.g. comment is at "-5 (0 | -5)"
upvote comment
comment displays as "6 (1 | -5)"

Undoing a downvote adds another minus sign on the downvotes as well, e.g. "-5 (0 | --5)"

**Comment by voat** [comment]
Thank you for the report. I tried reproducing this but I couldn't. Would you be able to provide a link to the comment where you experienced this behavior?

**Comment by moeVoat** [comment]
https://voat.co/v/announcements/comments/44003/47269

I tested the issue with the latest version of Firefox (Windows) and all add-ons disabled. I can do a GIF recording of it if you're unable to reproduce it in Firefox.

**Comment by moeVoat** [comment]
I evidently have a bunch of js issues that nobody else has, so I'll just close this.

**Comment by DanielFlamino** [comment]
Don't close. I can also reproduce it.

http://gfycat.com/CostlyThreadbareButterfly

Google Chrome 40.0.2214.115 m (64-bit) - Windows 7 Ultimate SP1

**Comment by moeVoat** [comment]
Have you ever experienced this bug? It's happened to me precisely once:

https://voat.co/v/voatdev/comments/49747#65761

**Comment by DanielFlamino** [comment]
Nope, that has yet to have happen to me (or at least I haven't noticed it).

**Comment by voat** [comment]
Okay, let's close it until it can be reproduced.

**Comment by DanielFlamino** [comment]
Why was this issue closed? I was able to reproduce it (see above gfycat). Just not the one that @moeVoat linked:
https://voat.co/v/voatdev/comments/49747#65761

**Comment by DanielFlamino** [comment]
Now this is really closed.
