### ISSUE TITLE
Username reference, '@', is not escaped when using it in code blocks

### ISSUE THREAD

**Issue by Nurdoidz** [voat/voat#285]
I found this out while writing a comment in response to a question a user asked. When I add a code block via `~~~`, then, I have an example media query that uses the `@` character, Voat thinks I'm pointing to the user /u/media:

~~~css
[@media](/user/media) (max-width: 950px) {
    #header {
        background-position: 0 18px;
        height: /* your height value + */ 18px;
    }
~~~

Raw comment data:

    ~~~
    @media (max-width: 950px) {
        #header {
            background-position: 0 18px;
            height: /* your height value + */ 18px;
        }
    ~~~

**Comment by DanielFlamino** [comment]
Also it is not escaped when using a backslash, unlike other markdown elements:

For example, the following should not make a notification:
~~~
\@Nurdoidz
~~~

The same way I can do this:
~~~
\[Title](http://example.com)
~~~

\[Title](http://example.com)

**Comment by PuttItOut** [comment]
This is a tricky thing to do with regex. I'll be dedicating some time to this issue soon.

**Comment by PuttItOut** [comment]
Fixed

**Comment by Nurdoidz** [comment]
You are awesome, PuttItOut!
