### ISSUE TITLE
Voat internal links do not retain capitalization

### ISSUE THREAD

**Issue by moeVoat** [voat/voat#293]
Referencing a subverse such as [**/v/Voat**](https://voat.co/v/Voat) using "**/v/Voat**" will result in "**/v/voat**" being displayed in the hyperlink's anchor text and "https://voat.co/v/voat" in its URL.

I am referring to the feature documented [here](https://github.com/voat/voat/issues/61).

**Note:** This issue is not present when using subreddit references.

**Comment by PuttItOut** [comment]
I just found this issue. The voat links are processed using a routing engine whereas the reddit links are not. The routing engine is dropping the casing. Issue will be fixed next time I merge.

**Comment by PuttItOut** [comment]
Fixed
