### ISSUE TITLE
Mod invitations to subverses with capital letters are not sent to users.

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#295]
As discussed on [this thread](https://voat.co/v/voatdev/comments/49823), moderation invitations for subverses that have capital letters on their name are not sent to the users.

Example: Sending a mod invitation to @spoooky_ghost for /v/InternalVoatDev, will not send a invitation to @spoooky_ghost, yet it registers as if a invitation was sent.

**Comment by voat** [comment]
This had nothing to do with capital letters. The subject of mod invitation contained subverse name and subject is limited to 50 characters. In essence, mod invidations would not be sent for any sub which had a longer name :)

**Comment by DanielFlamino** [comment]
so it was confirmation bias. wow just wow
