### ISSUE TITLE
API: comments

### ISSUE THREAD

**Issue by exidy** [voat/voat#304]
Some suggestions for the comments API:

1. I would've thought the syntax would be something like `/api/comment/<commentid>` and `/api/submission/<submissionid>/comments` rather than passing it as a URL parameter, but this is just a style thing
2. Client needs to be able to paginate requests and get "next page" - similar to the submissions in #302. 
3. Currently only top level comments are returned, there's no way to get to child comments.
4. Nice to have - when retrieving pages of comments to be able to specify the depth of retrieval, i.e. depth = 2 would return top level, replies to top level and replies to replies to top level.
5. "ParentId" probably should be "SubmissionId"

**Comment by PuttItOut** [comment]
Hello exidy. I'm PuttItOut and I'll be working on implementing a new API. These are great suggestions. By Friday I'm going to try to have a new mockup of the API interface.

**Comment by exidy** [comment]
Hi PuttItOut. Thanks for your help. Please see my general API comments in #303 as well if you haven't already.

**Comment by PuttItOut** [comment]
Yeah, I have and you have great ideas. Lets see if we can discuss the API interface when I have it spec'ed out and see what you think. Once everyone is on board, we'll stub it out so you can start accessing with dummy data and shortly afterwards we will implement it with live data. This should be fun.

**Comment by exidy** [comment]
I like your enthusiasm. :)

**Comment by exidy** [comment]
Hi PuttItOut, how are you going on this?

**Comment by PuttItOut** [comment]
Hey, sorry, I don't get notifications for these comments. PM me at @PuttItOut on Voat and I'll keep you posted.
