### ISSUE TITLE
中文版本vota

### ISSUE THREAD

**Issue by guisu6538** [voat/voat#327]
请问这个有中文版本吗  我个人在做和伙伴要做一个中文的

**Comment by artganify** [comment]
Err... I can't say anything about Chinese language support, but if you want to participate, feel free to fork and/or report issues.

**Comment by guisu6538** [comment]
恩 我和伙伴想基于这个系统做一个网站  只是不是中文的呵呵   谢谢回复  我们正在考虑

**Comment by guisu6538** [comment]
谢谢   国外朋友您好

**Comment by artganify** [comment]
@guisu6538 Voat is covered by the GNU general public license v3, which allows you take the source, modify, distribute and use it commercially (there are restrictions, though). You can find a TL;DR of the license here: https://tldrlegal.com/license/gnu-general-public-license-v3-%28gpl-3%29, the current license applicable to voat is here: https://github.com/voat/voat/blob/master/LICENSE. If you want to make contributions to the project, you need a CLA which can be optained here: http://voat.co/cla.

Voat relies on a variety of other open source projects, such as Bootstrap, JQuery, ASP.NET MVC and Entity Framework. They may or may not have Chinese documentation, I'm not sure about that. You can refer to those project if you need any additional support about them.

@voat There aren't any plans for a Chinese documentation of the platform and/or API, right?

**Comment by voat** [comment]
While we would love to be able to translate voat into as many languages as possible, this is currently not possible with our limited resources. There are plans to implement globalization support and make it easier for community to translate voat but this is currently not a priority.
