### ISSUE TITLE
Strikethrough not working in Markdown implementation

### ISSUE THREAD

**Issue by WackyIraqi** [voat/voat#328]
According to https://voat.co/help/markdown markdown is supported. Strikethrough appears to not be implemented.

Steps to reproduce:
replying with "\~\~comment\~\~" does not output ~~comment~~

**Comment by DanielFlamino** [comment]
Voat uses [MarkdownDeep](http://www.toptensoftware.com/markdowndeep/), a C# implementation of [Markdown](http://daringfireball.net/projects/markdown/). Strikethrough is not a feature of MarkdownDeep, nor does it seem to be one of Markdown. Nonetheless, it probably should be a feature to be implemented.

**Comment by talons1337** [comment]
Markdown does support strikethrough. 

What'd be nice is to see strikethrough and underlines.

**Comment by DanielFlamino** [comment]
Still, MarkdownDeep does not support those two features, so I don't know if it's them or Voat, who should implement them.

**Comment by voat** [comment]
Strikethrough is not supported by markdowndeep library which voat relies on and I am afraid this is not something we can justify implementing on our own at the moment.

**Comment by talons1337** [comment]
Hm, how does MarkdownDeep work?

**Comment by voat** [comment]
Here you go: https://github.com/toptensoftware/markdowndeep

**Comment by jksg** [comment]
FYI `<del>` is allowed in posts and comments.

**Comment by DanielFlamino** [comment]
<del> has been a part of the markdown toolbar since #436
