### ISSUE TITLE
Don't accept unicode characters in submission titles

### ISSUE THREAD

**Issue by voat** [voat/voat#330]
Unicode characters in submission titles should not be accepted.

**Comment by DanielFlamino** [comment]
So... this means that we can no longer make submissions with titles like this one, right? 
https://voat.co/v/DanielFlamino/comments/37921

**Comment by voat** [comment]
Correct.

**Comment by Mukt** [comment]
I was going to start a Hindi language sub, but this is a deal breaker.  
Does [voat](https://github.com/voat) intend to change this and accept non-English unicode in submission titles anytime soon?
