### ISSUE TITLE
CSS is not the same across the entire site?

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#334]
I don't know how I can describe this issue, so let the following page do it for you: https://voat.co/help/markdown

As you can see the CSS, the style for various elements (like Headings, Tables and Spoilers) is not the same as you'd see on the rest of the site.

Paging @Nurdoidz (do user mentions work here on GitHub?)

**Comment by talons1337** [comment]
I don't see the difference tbh... Though I think Voat has underlying bootstrap, so maybe that's it.

**Comment by DanielFlamino** [comment]
My bad, I should have posted a screenshot for the specific things I mentioned.

Here we go. [The page I linked](https://i.imgur.com/DRBRvX4.png) and how that markdown result [actually looks like](https://i.imgur.com/MeRaLbB.png).

**Comment by talons1337** [comment]
Ah, I see now. Yeah, this stuff should be unified and using one stylesheet, I think it might be because the styles apply to the comment section and if it's outside of one, it renders differently.

**Comment by DanielFlamino** [comment]
Didn't thought about that. I think I'm going to take a look myself and see if I can fix it.
