### ISSUE TITLE
UI Expandos aren't run on Comment load

### ISSUE THREAD

**Issue by PuttItOut** [voat/voat#337]
UI Expandos for comments are not run on comments retrieved after initial page rendering. The UI Framework needs to be fired: 

window.setTimeout(function () { UI.Notifications.raise('DOM', **CONTAINER ADDED** });

**Comment by PuttItOut** [comment]
This is such a simple fix, I don't know why it hasn't been done yet. Makes me want to break code and not fix it.

**Comment by voat** [comment]
Is this still an issue?

**Comment by PuttItOut** [comment]
No, it's fixed. https://github.com/voat/voat/commit/8c0737dbbe17aef0860f74060221f67035caa2cc

**Comment by DanielFlamino** [comment]
Ah, yes. That was a nice cookie.
