### ISSUE TITLE
Comments don't fill up entire box

### ISSUE THREAD

**Issue by quantumwannabe** [voat/voat#344]
There is a max width of 650px on some internal div in comments that prevents them from filling up the entire shaded comment box. Is this desired?
Demonstration:
![Demonstration](https://cloud.githubusercontent.com/assets/5686957/6539604/d28625d0-c43d-11e4-814b-63d41a8856c9.gif)

**Comment by talons1337** [comment]
I think it's to prevent really long lines of text that are short enough to fill up only one line. Makes it easier to read smaller blocks IMO. 

Either that or cross browser problem fixes.

**Comment by quantumwannabe** [comment]
It is so small of a distance between the two widths that it would make more sense to make the box smaller than to do this. There is already a maximum width on the shaded box.

That is IE11's inspector docked inside the window.

**Comment by DanielFlamino** [comment]
I doubt that it is intentional, since the container layout was adopted as the solution to move the white-space to the sides of the page instead of keeping it on the middle.

See #148, #151 and #152 for more info on the "Kill the whitespace!" saga.

**Comment by PuttItOut** [comment]
This attribute is used in many places though. I don't think it's needed anywhere but I've seen it on the messages pages also... 

My guess is it's simply left over CSS from a previous rev.
