### ISSUE TITLE
Set max number of submissions per account per time unit

### ISSUE THREAD

**Issue by voat** [voat/voat#346]
A single user account should not be able to submit more than x submissions per 24 hours. Recent alphabet submission spam is the perfect example why we need to establish such limit.

**Comment by talons1337** [comment]
Perhaps have a hard limit applied site wide, plus a custom defined limit set by mods, just like CCP.

What about pure text post? Are those affected by this planned change? And also, will deleted posts (either by mod or by user) add one back to the allowed posts count? 

A good system to use would be (values are just examples, don't wanna do algebra this late and on my phone): 

There are 100 posts allowed. User x posts something, there are now 99 posts. one will be added in 24 hours. 12 hours elapse, user posts something else. 98 posts left, one will be added in 24 hours and another in 12. An hour later, user deletes the newest post. 99 posts left, and one will be added in 11 hours. After 12 hours, there are 100 posts allowed, and the user deletes the post. There are still only 100 posts allowed, as all outstanding posts have been readded.

**Comment by DanielFlamino** [comment]
I like @talons1337's suggestion.

That is all (damn GitHub doesn't have an upvote button :P)

**Comment by x-Code-x** [comment]
1) Would that apply to Mods (or mod nominated "super users" in their own subs?

2) Admin roles (specifically you Atko or the general Admin accts) should be an exception.

Overall - Suggest making this role based?

Code X

Sent from my Sony Xperia™ smartphone

---- Daniel Flamino wrote ----

**Comment by x-Code-x** [comment]
Thoughts part two (damn you time limiting RL work...)

"Per 24 hours". I note the propsal is "per time unit". @talon1337 's suggestion otherwise being sound ( in terms of user experience / fairness ) - the "prevent alphabet sub spam" requirement to me trumps "fairness" in that sense.

Just saying that any solution should prevent flood AND slow lorus attacks - 100 per 24 hours could be dangerous if it still allows 100 in 30 mins.

Maybe 1 post per 10 mins or some other reasonable min time plus no more than 100 in 24 hours. Maybe use any web analytics to work out avg time on page where users post new submissions?

**Comment by talons1337** [comment]
1) I think mods should be excepted in their own subs if they mark it as a modpost (which will need to be implemented). 

2) Absolutely.

3) 1 post per 10 minutes might be a little too harsh, some people might have some content they want to post, and don't have much time to post it in. I know from experience that waiting merely 2 minutes per PM or (formerly) 2 minutes to update CSS is pure agony. Perhaps there should be a hidden/not hidden threshold that must be met (eg. x amount of upkarmas) which will allow you to post more content in one go. 

Offtopic: Is it possible to change github username?

**Comment by DanielFlamino** [comment]
Once again I agree with @talons1337 (also, here's how to change it  --> https://help.github.com/articles/changing-your-github-username/)

**Comment by x-Code-x** [comment]
1) Good idea - more work and I see that as still needing RBAC support.

3) I feel your agony. :) They are prescriptive numbers - analytics can work out the idea (user centered) values. Threshold idea - +1 as in scope to support "system". Will make it more flexible IMO.

Sent from my Sony Xperia™ smartphone

---- talons1337 wrote ----

**Comment by x-Code-x** [comment]
(meh - edits

*not prescriptive

* work out the ideal

We do have metrics / analytics in play yeah? If not - Piwik (piwik.org) - won't track API usage for you though, only the web front end) )
