### ISSUE TITLE
Deleting a post causes sidebar to glitch

### ISSUE THREAD

**Issue by quantumwannabe** [voat/voat#350]
Only tested in IE11

Steps to reproduce:
1. Create a new post. I have only tested with self-posts
2. Go back the subverse page.
3. Click discuss
4. Delete the post
5. Sidebar glitches out like in below image.

I did not notice this happening if I skipped step 2.

![Error](https://cloud.githubusercontent.com/assets/5686957/6587643/f0a2f628-c754-11e4-96f7-1a3d6ad9cde3.png)

**Comment by voat** [comment]
I was able to reproduce this with IE 11.

Firefox is not affected.

**Comment by voat** [comment]
Update: this sidebar glitch seems to be caused by JavaScript logic which handles the mobile sidebar (the burger menu). Resizing the window corrects the issue, mobile sidebar disappears and regular sidebar is displayed properly.

**Comment by PuttItOut** [comment]
Fixed
