### ISSUE TITLE
Votes not recorded

### ISSUE THREAD

**Issue by quantumwannabe** [voat/voat#358]
I am unable to vote on content. When I click the upvoat button, the score increases by two instead of one. When I refresh, the score is reset to what it was before. Additionaly, unupvoating it sets the score to 25.

Demo of voting:
![voitng demo](https://cloud.githubusercontent.com/assets/5686957/6657357/d4170000-cb17-11e4-8d91-6511ee9a372e.gif)

Request details:
![request](https://cloud.githubusercontent.com/assets/5686957/6657362/e127fea2-cb17-11e4-8f2a-7225ddc0b379.png)
Response:
`"Voting ok"`

[post](https://voat.co/v/gaming/comments/63979)

**Comment by voat** [comment]
I just looked up that comment ID in the database and it is shown as deleted by user. Closing.

**Comment by quantumwannabe** [comment]
Happened on more than that post. I'll get another example
