### ISSUE TITLE
Can't vote if CCP is exactly 20 and user has voted 10 times in last 24 hours

### ISSUE THREAD

**Issue by quantumwannabe** [voat/voat#359]
This is related to issue #358

My CCP is exactly 20, enough for the error message to go away and have unlimited votes. The problem is that the error message is hidden, but since I have voted more than 10 times in the last day, my votes are not being recorded. This is bad because no feedback is shown that the vote didn't hold until the page is refreshed.

I believe it is related to the lines below. The `> 20`'s should be `>= 20` instead, so it aligns with the error messages.

https://github.com/voat/voat/blob/39eb6a5ae6b154f97e8157505472b1631429b88c/Whoaverse/Whoaverse/Controllers/CommentController.cs#L42-52

https://github.com/voat/voat/blob/7c30223e518567101aeefb02341dd897efbf2747/Whoaverse/Whoaverse/Controllers/SubmissionsController.cs#L132-142

Also the server responds with `"Voting ok"` which it shouldn't do if voting fails.

**Comment by voat** [comment]
Thank you for reporting this.
