### ISSUE TITLE
HTML encoding breaks markdown blockquote

### ISSUE THREAD

**Issue by voat** [voat/voat#361]
Current workflow:

#### Incoming comments/text submissions**
User submits raw HTML 
This is encoded and stored in the database

#### Comment/submission rendering
HTML encoded content is loaded from database
Markdown parser is fed this data
Formatted HTML is the resulting output

#### Cause
In order to render blockquotes, markdown processor is looking for strings which begin with character >
This character will never show up during processing because it is encoded.

#### Possible solution?
Use REGEX to assist the markdown processor?

**Comment by quantumwannabe** [comment]
A regex that strips the tags out completely unless they are in a code block should work. So `<span>hello</span> world` would be stored in the database as `hello world`. Tags in code blocks would then be encoded like normal. I can't think a legitimate use of tags unless they are in a code block or inline code thing and it doesn't seem like a big deal if you can't quote from inside a code block.

**Comment by voat** [comment]
So something like this from http://www.dotnetperls.com/remove-html-tags:

```
static Regex _htmlRegex = new Regex("<.*?>", RegexOptions.Compiled);
public static string StripTagsRegexCompiled(string source)
    {
	return _htmlRegex.Replace(source, string.Empty);
    }
```

I guess we could implement this and work on a code block solution at a later stage.

**Comment by quantumwannabe** [comment]
What does `md.SafeMode = true;` actually do? The markdowndeep website claims that it "only allows whitelisted safe html tags". This might be sufficient enough to not have to encode at all. If the whitelisted tags are not sufficient, a better idea than a regex might be to edit the source of markdowndeep to block every tag.

**Comment by voat** [comment]
Thank you, that was a good find. Markdowndeep indeed has safemode which lets through only whitelisted tags. This is now live.
