### ISSUE TITLE
Ways to prevent users from submitting only links to a single website

### ISSUE THREAD

**Issue by voat** [voat/voat#363]
At the moment, users can submit links to website.com to sub Y unlimited number of times per day. Some users are abusing this and submitting links to (possibly websites they are affiliated with) multiple times per day while targeting a single subverse.

I propose that we implement a way for limiting the number of times website.com can be submitted to a given sub and having this as a sub setting for sub owners to tweak.

Thoughts?

**Comment by TylerDEV** [comment]
I don't know if there is a systematic way to prevent this. Coming up with a hard number to limit sites to could back fire (a blog post getting spammed vs users not able to post images hosted on one site). I think, honestly, it would be best to leave it up to the community. If anything, accounts should get "flagged" if they have a high percentage of posts from a single site. Obviously, sites like Imgur wouldn't cause you account to get flagged, but if your posts are 75% from a single blogspot blog, maybe that should be noted on your posts. Maybe something like a percentage badge next to each post (this site makes up XX% of my posts).

What do you think?

**Comment by DanielFlamino** [comment]
[Maybe something like this?](https://i.imgur.com/ISbw4ry.png)
