### ISSUE TITLE
Implement SignalR chat room for every subverse

### ISSUE THREAD

**Issue by voat** [voat/voat#369]
Every subverse should have its own sidebar chat room. This could be useful for live events as well as casual conversations. Only registered users should be able to take part in conversations.

**Comment by x-Code-x** [comment]
Suggestion 1 - check where real time chat (IRC etc) sits in the swiss legal framework (in case it turns Voat from a site into a type of telecommunications carrier) and make sure we know the privacy / freedom of speech implications.

Sent from my Sony Xperia™ smartphone

---- Atko wrote ----
