### ISSUE TITLE
[Feature Request] Allow users to delete all comments older than x days

### ISSUE THREAD

**Issue by bruestle2** [voat/voat#370]
Voat deletes comments when the user is deleted. It would be nice to have a built-in feature that would allow users to delete all their own comments that are over x days old.

Possible additional feature: Whitelist subverses - Allow users to delete comments from all but specified subverses

**Comment by talons1337** [comment]
I think users should have the option whether or not to purge their comments when they quit

Also, I think that there should be an option to simply auto-remove the username, but not the actual post, since some posts that might potentially help someone in the future... not do so

**Comment by voat** [comment]
This may have negative effect on voat if implemented. Users are already able to delete all of their voat-related history when they delete their accounts.

**Comment by talons1337** [comment]
The comment purging on quitting, is it optional or does it happen when you quit regardless or whether you wanted to or not?

**Comment by voat** [comment]
Everything is purget on account deletion automatically and this is not optional.
