### ISSUE TITLE
Program structure support/documentation

### ISSUE THREAD

**Issue by daimoneze** [voat/voat#377]
Hey voat,

I am a programmer that is rather unfamiliar with Microsoft platforms (and thus ASP .NET, C#, etc) while having a lot of experience with other OO languages (C++, Python, some Java) as well as HTML/CSS/PHP, and starting to get into the more advanced JavaScript libraries like jQuerry. I would like to get into and contribute to this project while cutting my teeth on C#, but installation/configuration of the various technologies (local server configuration, etc) are proving to be a barrier to entry since it's really hard to carve out the time to do all the back research on those. Is there any sort of a guide/tutorial (apart from the readme, of course) on how to plow through the process of actually getting a development environment up and running?

Additionally, as a (really really) nice to have, is there any high-level breakdown of the logical structure of the program? A hard "no" wouldn't prevent me from getting started, but would probably close to obliterate any ramp-up time.

Thanks!

**Comment by xvdiff** [comment]
Hi.

You're in luck, setting up a development environment for C# and getting
voat running is very easy!

As with every programming language that isn't being interpeted at runtime,
you need a compiler. In [C#](
http://en.wikipedia.org/wiki/C_Sharp_(programming_language)), code is being
translated to [ILCode](
http://en.wikipedia.org/wiki/Common_Intermediate_Language), which are
native language instructions for the [.NET framework](
http://en.wikipedia.org/wiki/.NET_Framework) (are you familiar with .NET?
It's basically a runtime framework that compiles ILCode to machine
instructions, similar to the Java VM).

The easiest way to get hands on a C# compiler is downloading Microsofts own
IDE "[Visual Studio](https://www.visualstudio.com)". It ships with
everything you need (full blown IDE with syntax highlighting,
[IntelliSense](http://en.wikipedia.org/wiki/Intelligent_code_completion),
project management, [MSBuild](http://en.wikipedia.org/wiki/MSBuild) build
tasks, compiler): You can get a free copy here:

https://www.visualstudio.com/en-us/products/visual-studio-express-vs.aspx

You should download the "Visual Studio 2013 Express for Web", which is
basically an "Express" (limited, but free) edition of Visual Studio 2013
preconfigured for [ASP.NET](http://www.asp.net) (the web stack voat runs
on, think of RoR for Ruby, Django for Python) development.

After you downloaded VS, just run it. There isn't much to setup here, VS
ships already preconfigured
to get you started quickly. Get familiar with the IDE and the most common
features - most things should be self explaining.. e.g for Building you
press on something that looks like building etc.

Afterwards, fork the repo, clone it and following the instructions here:

https://github.com/voat/voat/blob/master/README.md

Don't be scared about the dependencies you need. Visual Studio ships with a
built-in package manager called [NuGet](https://www.nuget.org) which
fetches all the required libraries from a repository as soon as you press
build (comparable to npm or ruby gem).

Regarding to the project structure: No, there isn't one. Or at least no
different one than the usual project structure for ASP.NET MVC web projects
(you're familiar with the MVC pattern? If not, look it up and check out
some samples in a language you're familiar with). There are views
(html/razor), controllers (for the web pages and the api) and models, both
entities and DTOs. Maybe you should also read a few tutorials on general
ASP.NET MVC development - after that, you'll quickly be familiar with the
structure of voat.

A few things to know in short:

* C# applications are separated into projects (similar to python modules),
each with their own build configuration, namespace (which are transformed
into assemblies (dlls and executables), which are grouped with project
solutions. Voat currently has one solution (the .sln) which you should open
with Visual Studio and 2 projects: One for the application and one for unit
tests

* Voat uses several frameworks that provide infrastructure concerns
available in most programming languages. First, get familiar with them in
your favorite language, then check out the frameworks used in voat/C#: ORM,
MVC, Serialization (json), model binding..

Good luck. If you have any further questions, don't hesitate to get in
touch.


Am Dienstag, 24. März 2015 schrieb Toast :

**Comment by daimoneze** [comment]
Excellent! Visual Studio is great. I've worked it before and IntelliSense was amazing. Is the 2013 Community Edition good (happen to have that installed), or is Express for Web better?

MVC is pretty interesting. I'm digging into that now. Thanks!

P.S. - It builds!

**Comment by thestamp** [comment]
Community edition is like professional, much better than web express.

**Comment by xvdiff** [comment]
@JeffLefebvre Yes you're right. I forgot about that one. @Toast Of course,
if you have the community edition, use that one. Visual Studio editions are
all more or less the same anyway - the real deal (when it get's pricey too)
comes when you're interested in using VS along with Team Foundation Server
and other MS products targeted at enterprise developers. ;)

**Comment by thestamp** [comment]
Actually, using VS with TFS online (private repo) is free for up to five
team members!

The diff between express and community is actually quite large- with
express you're limited to the kind of project you can make per sky (web
edition, desktop edition, etc) and express cannot have add-ons, so no web
essentials or resharper.

**Comment by daimoneze** [comment]
OK, we're getting closer. I promise I'm less of an idiot than I seem, but MS technologies are just **that** foreign to me.

I'm having trouble getting a proper instance of SQL server up. I see via VS there are various things I can do to manipulate DB files (including creating new ones), but if it's feasible I'm perfectly happy recycling the .sql files that are included. According to VS and appwiz.cpl I have all kinds of MS SQL stuff installed (FFS, so much of it) but I can't seem to find any interface that allows me to create a new instance, import existing .sql files, etc. To be clear, I'm trying to avoid dropping a stand-alone SQL server instance on this box if I can avoid it since it seems to be bundled with VS 2013 Community already. Any pointers?

**Comment by thestamp** [comment]
Take a look at db autocreation for sql server localdb or Sal server express

OK, we're getting closer. I promise I'm less of an idiot than I seem, but
MS technologies are just *that* foreign to me.

I'm having trouble getting a proper instance of SQL server up. I see via VS
there are various things I can do to manipulate DB files (including
creating new ones), but if it's feasible I'm perfectly happy recycling the
.sql files that are included. According to VS and appwiz.cpl I have all
kinds of MS SQL stuff installed (FFS, so much of it) but I can't seem to
find any interface that allows me to create a new instance, import existing
.sql files, etc. To be clear, I'm trying to avoid dropping a stand-alone
SQL server instance on this box if I can avoid it since it seems to be
bundled with VS 2013 Community already. Any pointers?

—
Reply to this email directly or view it on GitHub
<https://github.com/voat/voat/issues/377#issuecomment-87244753>.

**Comment by voat** [comment]
I may make a video step-by-step tutorial on setting up voat dev environment and running it locally when I get a chance, but if anyone else is willing to do so, I'm sure it would help newcomers immensely.

**Comment by daimoneze** [comment]
>Take a look at db autocreation for sql server localdb or Sal server express

Do you mean SQL Server Express? Doesn't VS2013 include it?

So I've managed to make new projects for each .sql file in the whoaverse solution (this is the only way I've found to import an existing .sql file). I then imported each .sql file in the repo to its corresponding database. I then browsed over to the two new databases in ```SQL Server Object Explorer``` and added the corresponding new users as they are called out in the ```Web.config``` file. In ```SQL Server Object Explorer``` I created the new users under the top level heading ```Projects - Voat``` (I named the solution Voat) rather than ```SQL Server```. Here is a [screenie](http://i.imgur.com/vgMSQ2U.png) of that I mean. However, this part doesn't seem to be the right thing. I'm having trouble seeing the distinction between the Projects object and the SQL Server object in the screenshot, apart from one referencing the projects in the solution, and the other appearing to be the actual server instance that I suppose would be running. However, trying to add a user to SQL Server doesn't seem to be possible when the user has a password, which is just strange. At this point I realize that I'm pretty far away from what might be considered "db autocreation." With all that, trying to "Build" the two DB projects fails *without* errors. :(

When I build the solution, the site does load in the browser via localhost, but I get the "under heavy load" error and some objects on the page (like the login/register box) are in a strange place, though this seems like a minor issue. I don't really think I have a proper DB connection.

**Comment by xvdiff** [comment]
@Toast Working with SQL using VS can be a real PITA as most tools are
poorly integrated or only practical for viewing, but not editing the
database. Microsofts prefered tool for database administration is Microsoft
SQL Server Management Studio. You can grab a copy here:

http://www.microsoft.com/en-us/download/details.aspx?id=43351

It ships with MS SQL Server Express. Just skip the server installation and
install just the tools. Then you can connect to your database using your
connection string, which is either configured in your app.config or the
default one (mostly "(localdb)\mssqlserver" or something).

If you still struggle with MS SQL and/or don't want to use it at all,
you're in luck. Since voat uses Entity Framework as the ORM, it can be used
with any database provider that EF supports. You can lookup resources on
the webs on how to configure EF for..lets say mysql. But then you can't use
the provided .sql files, though. ;)

regards

Am Samstag, 11. April 2015 schrieb Toast :
