### ISSUE TITLE
Conflict between link markdown and user mentions

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#379]
Really simple to reproduce:

~~~
[DanielFlamino](/u/DanielFlamino)
~~~

expected result would be:

~~~
<a href="https://voat.co/user/DanielFlamino">DanielFlamino</a>
~~~

instead it outputs:
~~~
<a href="[/u/DanielFlamino](/user/DanielFlamino)">DanielFlamino</a>
~~~

**Comment by quantumwannabe** [comment]
Also happens with subverse mentions:
![4-6-2015 11 10 23 am](https://cloud.githubusercontent.com/assets/5686957/7007250/a63f0ac8-dc4d-11e4-925a-6b84af1a48c2.png)
