### ISSUE TITLE
[Feature Request] Option to not purge account comments when you delete your account

### ISSUE THREAD

**Issue by talons1337** [voat/voat#381]
I don't really think this needs that much detail here, but perhaps I should justify why - user who wants to leave voat but leave behind their content. I'm sure there are more reasons to keep comments but this is the first one I could think of.

**Comment by DanielFlamino** [comment]
What would be the difference between this and simply never login again?

**Comment by talons1337** [comment]
Removing your username. Let's say I made an account using my real name and one day decided I wanted to leave my comments behind but not associate them with me... I'd have no options.

**Comment by moeVoat** [comment]
Wouldn't you be stuck with no way to remove the comments after you delete your account? That could be a problem if you later discovered private information in your posts that you didn't catch before.

**Comment by voat** [comment]
Thank you, but I don't see this being implemented anytime soon.
