### ISSUE TITLE
Separate subverse anonymized mode checkbox from sub settings

### ISSUE THREAD

**Issue by voat** [voat/voat#382]
Sub owners can accidentally activate anonymized mode on their subs. This should be separated and require additional input (for example, typing the keyword "CONFIRM") in order to prevent accidental activation.

**Comment by moeVoat** [comment]
It's not just sub owners; all Moderators have the checkbox. Seems like that shouldn't be the case.

**Comment by PuttItOut** [comment]
Closed as this is not a planned change.
