### ISSUE TITLE
Duplicate requests for comment reply, post reply and private message reply partial views

### ISSUE THREAD

**Issue by voat** [voat/voat#387]
When rapidly clicking reply button for comments in a thread or in inbox, as well as reply buttons in inbox for posts or for private messages, it is possible to get duplicate reply forms.

@quantumwannabe patched a similar issue recently when loading more comments and so the same principle could be applied here.

**Comment by quantumwannabe** [comment]
Relevant code is here: https://github.com/voat/voat/blob/master/Whoaverse/Whoaverse/Scripts/whoaverse.js#L282-305

Rather than only checking if a DOM node exists, we should also check to make sure that no request is in progress, like I did in #371
