### ISSUE TITLE
Duplicate requests for load more in sets layout

### ISSUE THREAD

**Issue by voat** [voat/voat#388]
When rapidly clicking load more button in voat sets layout (https://voat.co/v2), it is possible to get duplicate items.

@quantumwannabe patched a similar issue recently when loading more comments and so the same principle could be applied here.

**Comment by quantumwannabe** [comment]
Does this happen in more than just reply, and load more? I have a feeling that it does.

**Comment by voat** [comment]
Not that I'm aware of. This is why I opened 2 issues because both can be reproduced, but I think that wherever background requests like those in reply process are used, we may have the same issue.

**Comment by quantumwannabe** [comment]
I'm adding checks for requests in progress on all requests where we do something with the response.
