### ISSUE TITLE
Allow users to decide if their profile history should be visible to non-logged-in users

### ISSUE THREAD

**Issue by voat** [voat/voat#391]
Currently, user profiles show comment and submission posting history to all voat users and guests.

We need a feature which lets the user decide if their profile history should be publicly visible. In user preferences view, a checkbox should be added which lets the users decide if their profiles should be publicly visible or only visible to logged-in users.

**Comment by PuttItOut** [comment]
Or not visible at all.

**Comment by voat** [comment]
replaced by #694
