### ISSUE TITLE
Creating a subverse, fail recaptcha, rate limited?

### ISSUE THREAD

**Issue by collincusce** [voat/voat#394]
If you fail the captcha when creating a subverse, you are rate limited from creating a subverse... but it doesn't say what that rate is and I would prefer if I fail this hinky captcha it wouldn't rate limit at all.

**Comment by DanielFlamino** [comment]
What is your account btw? I might have an idea of what's going on.

**Comment by collincusce** [comment]
I think the account was "collin" that threw the error.

**Comment by voat** [comment]
This is a bug with our current rate limiting mechanism, or rather, my sloppy implementation of it. Rate limiting needs to be reset if recaptcha validation fails (this issue affects all rate limited areas which involve captcha validation, not only subverse creation process), absolutely, but I never really got around to solving this problem. I apologize for the inconvenience.

**Comment by PuttItOut** [comment]
Fixed
