### ISSUE TITLE
Minimum CCP for downvoting setting is not loaded to the subverse settings page.

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#395]
I think I did an awful job with that title. What I mean is that this right here
![image](https://cloud.githubusercontent.com/assets/6509486/7036847/51857bc6-dd91-11e4-94fe-5789b48bf980.png)
, resets to 0 everytime you open the subverse settings page, so if I go and edit something (like a quick css change or something), I forget to set it again to the desired value and click save, the setting is set to 0.

**Comment by voat** [comment]
this is now fixed
