### ISSUE TITLE
Posting throttle for users with negative CCP or SCP threshold

### ISSUE THREAD

**Issue by voat** [voat/voat#397]
In an effort to improve content quality and discourage common trolling behavior where high negative CCP/SCP is seen as a goal and some people race who can reach, say -10000 CCP/SCP, I propose the following:

If a user has accumulated, say, 100 CCP downvotes from other users in the last 30 days, the user should only be allowed to submit 1 comment per day.

If a user has accumulated, say, 100 SCP downvotes from other users in the last 30 days, the user should only be allowed to submit 1 submission per day.

**Comment by DanielFlamino** [comment]
ooo I like this suggestion.

**Comment by PuttItOut** [comment]
What a web we weave.

**Comment by acgh213** [comment]
I think this will be helpful in discouraging the same type of issue arising on more and more of reddit. And which will keep voat a place of discussion.

**Comment by voat** [comment]
This was implemented a few days ago as announced in /v/announcements.
