### ISSUE TITLE
User name visible in messages when replying from anon subs 

### ISSUE THREAD

**Issue by Howweird** [voat/voat#398]
I made a post in an anonymous sub and when someone would reply I would get a message and it would say who sent it but would show as numbers is the sub. I was able to click the users name and see their profile.
![voat](https://cloud.githubusercontent.com/assets/11897196/7100609/151a0f2e-dfe1-11e4-99f2-55209931642b.PNG)

**Comment by DanielFlamino** [comment]
Ah, this explains why you wanted to send it via the email, nice find!
