### ISSUE TITLE
Implement minimum CCP requirement also for upvoting

### ISSUE THREAD

**Issue by voat** [voat/voat#400]
Currently, all new accounts are able to upvote 10 submissions per day. This is being abused by people who make several accounts in order to upvote their own submissions.

The following will have to be reinstated if it is not already in action:

- minimum X comment contribution points before user is able to upvote comments
- minimum X comment contribution points before user account is able to upvote submissions
- minimum X comment contribution points before user is able to downvote comments
- minimum X comment contribution points before user is able to downvote submissions

**Comment by idlehand** [comment]
Is there a delay set on ability to upvote upon account creation? This would deter it slightly.. The first thing I do when I create an account isn't vote, it's browse for a bit. So why not a 10-15 minute time limit before anything registers.

**Comment by Zer0t3ch** [comment]
@idlehand That would pro ably not really help. If a message shows up telling them about the limit, they'll just go do something else for 10 minutes. 

It would slow people down, but I doubt it would deter anybody.
