### ISSUE TITLE
NSFW thumbnails are not shown when "Display NSFW content" is enabled

### ISSUE THREAD

**Issue by ayawnymouse** [voat/voat#402]
On the front page, in sets. etc. the account setting to show NSFW content doesn't correctly apply to thumbnails. It does seem to work when viewing an individual sub.

**Comment by voat** [comment]
We are unable to reproduce this.

**Comment by ayawnymouse** [comment]
Screenshot showing this issue. The "Display NSFW content" setting is checked in my account but it's still censoring the thumbnails.

![image](https://cloud.githubusercontent.com/assets/12009664/8580986/a4b50036-2572-11e5-9411-a0deec9c91f2.png)

**Comment by ayawnymouse** [comment]
@voat I can't reopen this on GitHub, but the issue is still present (see previous comment) can you please reactivate it for me?
