### ISSUE TITLE
Upvoating a post with at least 1 downvote or downvoting a post shows the number of upvotes/downvotes rather than the net score

### ISSUE THREAD

**Issue by quantumwannabe** [voat/voat#404]
3 upvotes - 1 downvote = 2 score. I upvote, raising the number of upvotes to 4, and the net score to 3. 4, the total number of upvotes is shown instead.

![Demonstration](https://cloud.githubusercontent.com/assets/5686957/7288571/4931f3b6-e929-11e4-82cd-588d60cd474f.gif)

A similar thing happens with downvotes:
[/v/ideasforvoat post](https://voat.co/v/ideasforvoat/comments/84028)

**Comment by DanielFlamino** [comment]
Surprisingly that is intended, except the 3 at the end, it should have returned to 2 and not 3.

**Comment by talons1337** [comment]
I don't like the feature. It should work the way it does on reddit, and if the user wants to see how many upvotes the thing has, hovering over the scorebar should instantly show the ups and downs in a popup box next to it.

**Comment by DanielFlamino** [comment]
It's all up to @voat

**Comment by jksg** [comment]
I understand wanting to show the number of up/downvotes, but hiding the score is unintuitive. Looking down any list of submissions (like my front page) the numbers have different meanings based on whether I’ve voted or not.

I think a much cleaner solution would be showing upvotes *and* downvotes when hovering over either arrow (or the entire `.midcol`).

So a post could look like this:

      ^
      2
      v

and on hover it should look like this:

      ^
    +3/-1
      v

with the + and - numbers coloured appropriately.

After voting and moving the cursor away, the display should revert to the score.

**Comment by DanielFlamino** [comment]
I'm going to fix this as soon as I have some free time.
