### ISSUE TITLE
Moderators hierarchy needs to be more flexible

### ISSUE THREAD

**Issue by vegax87** [voat/voat#408]
some days ago I posted my idea: https://voat.co/v/ideasforvoat/comments/85112 which has received 12 upvotes, basically I would like to see a hierarchy like this:

Level 1 - Admin: Full Privileges
Level 2 - CoAdmins: Access to most areas and can add or remove moderators (except the founder of course)
Level 3 - Moderators: Access to most areas with some restrictions.

**Comment by voat** [comment]
In order for this to be implemented, I'd love to see this described as detailed as possible. For every level suggested, me or other developers which may want to implement this - will require a list of functions which are available to that level.

* Level 1 is crystal clear, no restrictions.
* Level 2 - needs a clear definition (a complete list of functions that this level has access to)
* Level 3 - needs a clear definition (a complete list of functions that this level has access to)

**Comment by vegax87** [comment]
Level 2: Access to Subverse settings, Flair settings, can add other or remove other Level 3 moderators, Ban users and moderation powers (edit\delete\toggle sticky posts, edit\delete\distinguish other comments )

Level 3:  basic moderator with access to subverse settings, flair settings, and ban users, and moderator powers for posts and comments. He CANNOT add\remove other moderators.

**Comment by talons1337** [comment]
Instead of having levels, why not make every setting configurable? I feel like that wouldn't be that much harder, and may possibly be easier depending on how it's done. It would definitely make things better for subverse owners.

**Comment by Zer0t3ch** [comment]
@talons1337 This sounds like a great idea. Maybe have 3 or 4 levels by default (including owner) and then just have a checkbox table with permissions along the side and mod levels along the top where the owner can enable and disable permissions however is seen fit. This would be great where people want a mod who can ONLY modify the CSS or something like that.

**Comment by inkadnb** [comment]
@Zer0t3ch it would be relatively easy to do via a permission matrix.

**Comment by PuttItOut** [comment]
Partially Fixed with new mod roles
