### ISSUE TITLE
Stickied comment - moderator feature

### ISSUE THREAD

**Issue by voat** [voat/voat#412]
Moderators should be able to sticky a maximum of one comment per thread. 

Possible use cases for this feature are discussed [here](https://voat.co/v/ideasforvoat/comments/88400), but the primary idea behind this is a solution for long threads where informative comments are often unable to accumulate as many positive votes as comments written within X hours after thread has been submitted since it takes time and effort to write such comment.

**Comment by PuttItOut** [comment]
Fixed
