### ISSUE TITLE
When a mention is removed, the inbox keeps a unvalid link as the sender.

### ISSUE THREAD

**Issue by Luk3M** [voat/voat#415]
Images: [[1]](http://i.imgur.com/y5ypzEg.png) [[2]](http://i.imgur.com/98y25I2.png)

There is the possibility of someone create a account with the unvalid name and all the removed mentions will redirect to that account.

The problem is in the **/voat/tree/master/Whoaverse/Whoaverse/Views/Messaging**, but I do not have a way to test any fix, and I could send a problematic pull request.

**Comment by DanielFlamino** [comment]
No problem with creating the @deleted account:
![image](https://cloud.githubusercontent.com/assets/6509486/7636704/c000db68-fa60-11e4-9d88-33a36914822f.png)

Making "deleted" not being a link on the message is a probably good change to do.

**Comment by Luk3M** [comment]
This makes the bug more harmless, that's good!

**Comment by deleted** [comment]
Thank you for considering the @deleted's of the world in your design constraints.
