### ISSUE TITLE
Titles of posts are HTML-escaped

### ISSUE THREAD

**Issue by zlsa** [voat/voat#417]
https://voat.co/v/introductions/comments/95984

The following is what I see in Chrome 44:
```
(Not saying I&#39;ve &quot;jumped ship&quot;, but want to give voat a fair shake. So far it looks awesome! | introductions)
```

**Comment by zlsa** [comment]
Oops, this only seems to happen when the title is changed (i.e. I have new messages).

**Comment by DanielFlamino** [comment]
Yep, only when the notifications counter is updated.

**Comment by voat** [comment]
This should be fixed now.
