### ISSUE TITLE
Lock voting for submissions and comments older than 7 days

### ISSUE THREAD

**Issue by voat** [voat/voat#423]
Submissions and comments older than 7 days (configurable value in web.config) should be locked for voting.

**Comment by PuttItOut** [comment]
Let this be a subverse configurable value. It will be way more practical this way. An extension would be separate subverse values to control submission and comment voting lockout periods.

A global setting isn't a good idea.

**Comment by northWind87** [comment]
Perhaps a global default? When a new subverse is created, it adopts the default; after creation, the subverse's lock time can be changed. While you're at it, perhaps allow for the feature to be turned off per subverse (or maybe even globally).
