### ISSUE TITLE
drag n drop link sharing

### ISSUE THREAD

**Issue by voat** [voat/voat#424]
Drag n drop link sharing should be modified to include a "hot zone" in the sidebar with title "drag n drop a link here to share it" instead of currently implemented solution which listens for drag event on body element.

**Comment by PuttItOut** [comment]
In addition this line causes a fatal error in IE rendering the site useless as the overlay stays up and can't be manually removed, requiring a hard refresh.
 
`var i=n.dataTransfer.getData("text/html");`

The `dropFunction(n)` needs to be wrapped in a try/catch to prevent this the unresolvable overlay.

**Comment by God--owner-of-the-universe** [comment]
Additional problems: drag&drop of selected text / browser back button disabled (Firefox Windows 7)

The D&D link sharing should also listen for *actual links*. I just selected a bit of text and dragged/dropped it accidentally. This makes the "share a link" full-page overlay visible, and it *stays* visible. I had to select part of the displayed text and d&d it again to get out of there.

But another thing that sucks is that if you actually drag&drop a link onto the page, which calls the submit-page with URL already filled in, you can't use the browser's back button to get back to the page you were reading. As a temporary solution, maybe this should just open a **new window/tab**. This would be a good idea, anyway. I mean, do you ever open a browser window and go to a Voat page to submit something? No. You are often already there, reading stuff, and then want to submit something. But this will make you lose your current discussion permanently. :(

**Comment by Scaarus** [comment]
I knew I got this idea from somewhere but couldn't remember where. I made a post with an example of what it could look like [here](https://www.voat.co/v/ideasforvoat/comments/130088). I have the code all set pretty much (need to make a dark theme for it).

**Comment by PuttItOut** [comment]
Closed as this is not a planned feature.
