### ISSUE TITLE
Subdomain routing

### ISSUE THREAD

**Issue by voat** [voat/voat#427]
Subdomain.voat.co should be mapped to, and load voat.co/v/subdomain without redirecting.

A wildcard subdomain has already been setup.

**Comment by PuttItOut** [comment]
I have code that does this already.

**Comment by jksg** [comment]
Full disclosure: I’m squatting on /v/www for fun because of this feature. You should probably test for common subdomains (www, mail, ftp)?

**Comment by PuttItOut** [comment]
Don't worry, common subdomains are not forwarded. ;)

**Comment by jksg** [comment]
@PuttItOut Damn, there goes my evil genius plan to take over the front page :imp:

**Comment by PuttItOut** [comment]
It was a great plan though... and if we forget anything it might just still work! ;)

**Comment by Aaron-P** [comment]
Has this been put in yet? I have done this sort of implementation in another project if needed.

**Comment by PuttItOut** [comment]
Closed as this is not a planned change.
