### ISSUE TITLE
Public mod log 

### ISSUE THREAD

**Issue by SolarAquarion** [voat/voat#43]
I would like to request a public mod log and that when a API happens bots can read from the mod log for stuff like reddit requests.

**Comment by voat** [comment]
I will try to make this the next feature I implement. The logs will be non-optional and public. Deleting threads will require a reason and every deleted thread will be publicly visible in /v/subname/deleted. Every thread in /v/subname/deleted will have a "report moderator abuse" button to bring attention of voat staff to rogue moderator behavior.

**Comment by DanielFlamino** [comment]
What about illegal content or things like spam? Will it be hidden and require admin approval before permanent deletion?

**Comment by voat** [comment]
We could skip markdown parsing of content for discussion-type posts and strip links from link-type submissions while still showing the links as clear text. We could also have auto purging (once a month?) from the "trashcan".

**Comment by DanielFlamino** [comment]
I guess the links as plain text would work for the spam part (since they usually just want to spread the link for SEO), but for illegal content I have no clue if that would be enough (I don't even know what is the law (if there is any) regarding linking to illegal material here in Portugal, let alone Switzerland :P ).

**Comment by quantumwannabe** [comment]
Adding `rel=nofollow` on the comment links will stop Google from following them so it should stop SEO spammers (and look nicer than plain text links). Alternatively, the page wide meta tag ` <meta name="robots" content="nofollow" />`  could be used, but then links that we might want followed would be also blocked. [Google's Article](https://support.google.com/webmasters/answer/96569?hl=en)

For illegal content, maybe make mods report it to admins who could replace the bad content with a CIA highlighter like this: ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉

**Comment by voat** [comment]
This is implemented.
