### ISSUE TITLE
UpVotes Not "Sticking" And Staying Blue

### ISSUE THREAD

**Issue by LemonCookieYum** [voat/voat#431]
I cannot upvote.  I have 28 comments and once I hit 20 last night I could upvote.  This AM I cannot upvote.  I tried on AdBlock news article and FB science article.

I also know it is 24 hours since my initial 10 votes, had to wait until I hit 20 comments and then could upvote again.  Is there still some sort of restriction I am not understanding.  Is it still only 10 upvotes every 24 hours?  I don't get the pop up message stating that.  The upvote arrow will not stay "blue" counting my vote.  I refresh and it goes back to grey and the count goes back to say 2 from 3 when I clicked on the upvote.

Thanks.

LemonCookie24 on Voat

**Comment by LemonCookieYum** [comment]
I am now able to upvote although the issue could not be duplicated by a programmer on Voat it just suddenly started working again.

Thanks.

**Comment by DanielFlamino** [comment]
After you have 20 comment points, the number of upvotes you can give per day is (your comment points / 2). Since you had 28 comment points you would only be able to upvote 14 times.
