### ISSUE TITLE
Deleting a comment also deletes the votes on that comment

### ISSUE THREAD

**Issue by IcyDefiance** [voat/voat#432]
It's probably the same for submissions, but I haven't tested it.

If you make a comment, and it gets 2 upvotes, you'll have 2 CCP. Then if you delete it afterward, you'll go back to 0 CCP.

In a way, it might be nice to leave it that way (Stack Exchange does), but it allows users with negative CCP to "reset" their account and avoid being throttled.

**Comment by DanielFlamino** [comment]
Just commenting to confirm that same thing happens to submissions.

**Comment by PuttItOut** [comment]
Talk about a huge issue. Simple on the surface but extremely complex on the underside. 

So, if a user doesn't loose their points upon deletion then that means the system has to maintain their associations to the entries, thus making deletions not true deletions, but pseudo deletions. This is kind facebooky. 

If you calculate and store points separately as to maintain a separate cache of accumulated points then it will become nearly impossible to verify the accuracy of this number over time. If you keep a log on modifications to this cache then we are back at the first point.

**Comment by travis-g** [comment]
Isn't it within the nature of privacy to require comment/submission points to be removed when a submission is deleted?

**Comment by IcyDefiance** [comment]
Pseudo-deletions are annoying. I do think it's important to fully delete the *content* of a comment, or the link and title of a submission, or whatever. However, I don't think it's bad to keep around the score and even the date and have that associated with a user.

It's probably easiest to set [CommentContent](https://github.com/voat/voat/blob/master/Whoaverse/Whoaverse/Models/Comment.cs#L30) or the equivalent for submissions to null instead of deleting the whole row. I'm not really familiar with this repo, but that would be my recommendation as a random guy who knows how to write code.

**Comment by TNTGav** [comment]
Would it not be enough to just store an integer on the user profile that is then used to alter the comment vote calculation?

An update of this integer can trigger when a comment is deleted and recalculate each time a user deletes a comment.

Just a thought, I am a bit of nublet on Github but have been appreciating the ASP.NET MVC EF goodness for much longer! :)
