### ISSUE TITLE
Are html tags intended to go through?

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#434]
[See this](https://voat.co/v/ideasforvoat/comments/105760/211816)

**Comment by voat** [comment]
Safe HTML tags are allowed through a white list built into markdowndeep library.

These are the currently whitelisted tags:

"b","blockquote","code","dd","dt","dl","del","em","h1","h2","h3","h4","h5","h6","i","kbd","li","ol","ul","p", "pre", "s", "sub", "sup", "strong", "strike"

**Comment by DanielFlamino** [comment]
TIL about the kbd tag. Adding the s, sub and sup to the toolbar, since most of those already have an equivalent in markdown.
