### ISSUE TITLE
Voat mishandles a few types of urls

### ISSUE THREAD

**Issue by sstewartgallus** [voat/voat#440]
Voat doesn't handle the following urls properly:
- `https://voat.co/v/foo.bar` and `https://voat.co/.fd` give a weird 404 page variant
- `https://voat.co/v/foo.` and `https://voat.co/...` give exception pages
- `https://voat.co/v/foofdsa/fdafd` redirects to the home page

**Comment by trebach** [comment]
For the first two cases you are receiving ugly IIS error pages. That needs to be fixed.

For the last case, the site thinks you want the subverse "foofdsa" sorted by "fdafd". If it doesn't recognize the sorting type, it boots back to the home page.

**Comment by Scaarus** [comment]
@trebach If anything the last case should send you back to the verse instead of home.

**Comment by trebach** [comment]
@Scaarus Ok, I can certainly change it to send you back to the verse if it exists.

**Comment by deathly809** [comment]
http://voat.co/v/c++ also gives ugly IIS error page.

**Comment by PuttItOut** [comment]
Closed as this is not a planned feature.
