### ISSUE TITLE
Potential issue with RSS feeds

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#441]
https://voat.co/v/AskVoat/comments/113096/239436

**Comment by Aaronontheweb** [comment]
Are we going to add support for per-subverse and per-thread RSS feeds?

**Comment by DanielFlamino** [comment]
Supposedly the current rss feeds are per-subverse. No clue if per-thread is planned.

**Comment by Aaronontheweb** [comment]
Looks like the per-verse RSS structure works like this: https://voat.co/rss/dotnet

**Comment by jksg** [comment]
Every feed item has the same `<guid>` element:

    <guid isPermaLink="false">Item ID</guid>

guid needs to be a unique string in Atom. I’m guessing that’s why some feed readers are only showing the first feed item — they assume every item is a duplicate based on the guid.

I suggest using submission number (i.e. the `113096` in `https://voat.co/v/AskVoat/comments/113096/`), or just the full URL and drop `isPermaLink="false"`. `isPermaLink` defaults to true and there’s no reason not to use a permalink (I assume Voat’s feeds will never list the same submission twice).

[RSSController.cs line 85](https://github.com/voat/voat/blob/master/Whoaverse/Whoaverse/Controllers/RSSController.cs#L85), [111](https://github.com/voat/voat/blob/master/Whoaverse/Whoaverse/Controllers/RSSController.cs#L111) and [122](https://github.com/voat/voat/blob/master/Whoaverse/Whoaverse/Controllers/RSSController.cs#L122)?
