### ISSUE TITLE
Disable downvoting on comments older than 7 days

### ISSUE THREAD

**Issue by voat** [voat/voat#443]
If a comment is more than 7 days old, nobody should be able to downvote it. Upvoting should work as before.

**Comment by pharno** [comment]
why?

**Comment by voat** [comment]
Because profile history is currently public and this is enabling some people who disagree with just one of your comments to go through your entire profile history and downvote everything in a sort of internet revenge spree without having any desire to interact or discuss their actions. Why not?

**Comment by pharno** [comment]
I think it should go both way though. it doesnt seem fair to me to allow a comment to get upvoted further while not allowing it to be downvoted.

**Comment by voat** [comment]
Perhaps you're right and we could do it both ways, but I can see a use-case where new users could discover interesting comments years after said comments were posted and they may want to show their appreciation by upvoting. I see no direct issue with them being able to upvote said comments as this can't be abused like the downvoting. I don't know, I'd like to hear more thoughts on this perhaps in /v/ideasforvoat if someone would like to start a thread.

**Comment by pharno** [comment]
your argument works both way though. say I find a user which I usually like. so I go through his stuff, and find this really shitty comment by him. I feel like I should not be able to vote at all, or to be able to downvote it.

**Comment by DanielFlamino** [comment]
This allows for massupvoting the same way it allows for massdownvoting. Mass downvoting is bad because it can push good commenters below the throttle threshold, whilst mass upvoting can be bad because it can push bad commenters above the throttle threshold.

**Comment by moeVoat** [comment]
Atko, can you message Clayton on Voat?

He wants to help cover the bandwidth costs due to the extremely heavy influx of people migrating from /r/fatpeoplehate. Sorry about getting off-topic here, but you get a buttload of PMs on Voat and it'd be forever until you saw this message.

If anyone else reading this has a faster method of communicating with Atko, please tell him to message Clayton.

**Comment by pharno** [comment]
@moeVoat please create a new issue for this. also atko might have problems accessing voat himself, so give him some email or phone number or whatever if possible

**Comment by RainbowFlwrPowr** [comment]
Hey, this is Clayton, if Atko cannot access Voat and would prefer to use email he can email me at steveroger.junk@gmail.com to get a hold of me. This is the only email I would like to give out publicly.

**Comment by quassy** [comment]
I think the number of days comments (and submissions) can be voted upon should be configurable by subverse. For smaller subs a longer voting period might make more sense, whereas in v/news etc it should be limited to a couple of days.

**Comment by talons1337** [comment]
It should not be limited at all. This restricts user rights and freedom of expression. I understand the reasoning behind it, but it's not the right way to go about doing it.

**Comment by PuttItOut** [comment]
Fixed
