### ISSUE TITLE
Is there an API?

### ISSUE THREAD

**Issue by yotamN** [voat/voat#448]
Is there an API for the site? I want to make a mobile app for iOS and Android but I couldn't find a way to do that without you providing some API, I'm not an ASP.NET developer so I can't help with that.

**Comment by PuttItOut** [comment]
We are nearing completion on a new API, so yes, there is an API. Send me a PM on Voat to the same username and I'll get you the info.

**Comment by yotamN2** [comment]
I will send, once the site will load

**Comment by pembo210** [comment]
https://voat.co/api/help - this could get you started. I want in too :)

**Comment by DanielFlamino** [comment]
That's the legacy API. A new one is on Beta testing

**Comment by bateller** [comment]
SOAP or REST?

**Comment by yotamN2** [comment]
REST

**Comment by Jawnnypoo** [comment]
Is this the new one here? 

https://fakevout.azurewebsites.net/api/help

**Comment by DanielFlamino** [comment]
@Jawnnypoo that link is supposed to be private.

**Comment by Jawnnypoo** [comment]
@DanielFlamino Apologizes mate, I found it through a Google Search. I removed it.
