### ISSUE TITLE
Put up a temporary static landing page

### ISSUE THREAD

**Issue by jksg** [voat/voat#449]
Not going to argue about performance, scalability, which stack to use, whose dick is bigger (mine) etc.

Just put up a temporary static landing page. Reddit is exploding and will continue to explode for the next 24 hours and Voat is bleeding current *and* potential users by 503-ing all over the place.

**Comment by Saturate** [comment]
Cloudflare could help a lot, with almost no work at all. Caching and always online. Pay for it for even more awesomeness, I'm sure somebody want's to donate if a paid plan would help. :-)

**Comment by jksg** [comment]
@Saturate A CDN could help a lot. CloudFlare is but one provider. You should open an issue specifically for CDNs or talk about performance in one of the [other](https://github.com/voat/voat/issues/446) [threads](https://github.com/voat/voat/issues/445).

**Comment by ryanelian** [comment]
Just an input, I think the static landing page should include means to donate (link to paypal? bitcoin?) and a transparent scaling plan written there.

#446 mentioned bits about funding and I think right now with redditors flocking into voat, they're more than likely than ever to donate.

**Comment by bitassassin** [comment]
I'm down to throw money and review code. I also agree that a static landing page in nginx or a similar extra-low I/O web server might be a good stopgap.

**Comment by mlwohls** [comment]
@bitassassin and others.  Since @voat is MIA... we've gone ahead and started pulling together an AWS instance to host a version of the code.
Anyone have any idea + desire to help of what we'd need to populate in the DB to test this thing out?  Then when @voat or others can dive in, we'll be ready to help?

**Comment by jorgeavaldez** [comment]
I'm definitely interested in helping out as well!!!

**Comment by mlwohls** [comment]
FYI - I'm a non-dev CEO that runs a pretty sizeable scale startup.  Our team was excited by what we were seeing and we have some crazy scale capabilities (our VP of Eng built Netflix's architecture).  We're just running fast and trying to get out ahead of the "window of opportunity" for the community.  Let me know if other's are interested and how we can best coordinate.

**Comment by PuttItOut** [comment]
I'm part of Voat. I can answer any questions.

**Comment by mlwohls** [comment]
@PuttItOut shoot me a note at mlwohls2@gmail.com ?  Would love to connect in via slack, chat, FB, or something more realtime?  We've got a great team excited to help (and already moving).  If we can help, would love to do so. If not, I'd hate for the team to waste their time.

**Comment by jksg** [comment]
Guess it was implemented :goat:
