### ISSUE TITLE
Can't upload avatar

### ISSUE THREAD

**Issue by faissaloo** [voat/voat#456]
Here is the file I'm trying to upload:
![avatar](https://cloud.githubusercontent.com/assets/8840681/8138852/8916b7ce-1146-11e5-9234-3c159471fa9b.png)

I get the message "Please upload a .jpg or .png image." when I try to upload it

**Comment by TNTGav** [comment]
I can't replicate this in my environment:

![untitled](https://cloud.githubusercontent.com/assets/3102057/8141755/d3ecb7d6-1163-11e5-94db-eb325323ceaa.png)

I even tried replicating it on the live site and it worked fine.

I suspect you may have been trying when the servers were overloaded so it wasn't properly uploading?

**Comment by PuttItOut** [comment]
Was a permissions issue on server during roll over. Should be fixed. Please verify and close it so.
