### ISSUE TITLE
Private messages break their titles in replies if apostrophe used (Screenshot inside.)

### ISSUE THREAD

**Issue by ghost** [voat/voat#457]
https://i.imgur.com/3KFOvxn.png

(Maybe it's related to [Japanese characters are ignored in submission titles](https://github.com/voat/voat/issues/411).)

For testing, I sent myself a PM. Then I replied to my own PM. In the replies, the message title ends directly before the apostrophe that I had used there. (When replying, you don't see / can't edit the title of the reply.)

**Comment by Scaarus** [comment]
It's not related to the Japanese characters thing. The single quotes aren't escaped in the subject so it causes the subject to change for the reply. I can do a pull request for a fix later but it will only prevent new cases, it wont fix old ones.

**Comment by God--owner-of-the-universe** [comment]
Make it so.

https://www.youtube.com/watch?v=fVCzpR0qVtA

(To save time: The link is 1:15 of funny, not any useful info.)

**Comment by PuttItOut** [comment]
Fixed
