### ISSUE TITLE
CSS Styling

### ISSUE THREAD

**Issue by Zer0t3ch** [voat/voat#459]
Ok, so I couldn't think of a better title, but a mod can change it to something more appropriate after reading what I have to say:

---

Currently, it seems that light mode loads 1 CSS file, dark mode loads a different one, and I would like to propose a change to this for 2 reasons.

What it should be is a single CSS file that uses classes to seperate between light and dark mode. (IE, every element should have the class `dark` if dark mode is enabled, or `light` if light mode is enabled. 

The reasons for this are:

1. If a client is using a browser that caches CSS, it only needs to cache 1 file that can continue to be loaded from. This reduces the necessary downloads, especially on theme switches, which helps both the user and reduces server load.
2. Subverse Theming: It seems to me that currently, a subverse mod can only have one set of CSS to be used on the sub, not two seperate ones for light/dark. Switching to this system would allow mods and theme designers to have a single CSS file using class selectors to embrace a users light/dark choices.

**Comment by jksg** [comment]
> every element should have the class dark

Not every element. It should be on the `<body>`.

You can then style like so:

```css
element {
    /* default style */
}

.dark element {
    /* night-mode */
}
```

The night-mode toggle will only need to `$("body").toggleClass("dark")` of reloading the page like currently.

Good call; I’ve been meaning to open an issue like this.

**Comment by talons1337** [comment]
Problem with this is that CSS files will have to be much larger, and they have a limit at the moment. The best way to go about doing this, in my opinion, is having 3 stylesheets, Universal, which is code for both, light, which is code for light, and dark, which is code for dark.

**Comment by yotamN2** [comment]
@talons1337 +1

**Comment by Zer0t3ch** [comment]
@talons1337 That would work as well, but all 3 would have to be exposed to sub owners/mods. My main concern right now is that there's no good way for custom CSS to embrace a user's light/dark choice.

**Comment by travis-g** [comment]
This goes along with #435

**Comment by Aaron-P** [comment]
#514 adds a theme class to body which is related to this along with #435 and #143, so it should be possible to do theme targeting on custom css.  Doing the styling this way should have a negligible affect on size with gzip, the only issue is with the input size limit.

**Comment by jksg** [comment]
@Aaron-P Just noticed the change on the site. Thank you on behalf of every mod and sub designer!
