### ISSUE TITLE
Creating a verse named "frontpage" acts like the frontpage.

### ISSUE THREAD

**Issue by Scaarus** [voat/voat#461]
You can view the voat post about it [here](https://www.voat.co/v/voatdev/comments/124691). Effected subverse [here](https://www.voat.co/v/frontpage).

In [Controllers\HomeController.cs](https://github.com/voat/voat/blob/master/Whoaverse/Whoaverse/Controllers/HomeController.cs#L459) the "frontpage" subverse is referenced in Index and IndexV2. This is causing the actual subverse to display some properties of the front page such as having an "incoming" tab instead of "top". All three of the tabs at the top link back to voat.co instead of the subverse.

**Comment by jksg** [comment]
Similar issue, a [subverse named “user”](https://voat.co/v/user) acts like a user profile. The top tabs are to Overview (`https://voat.co/user/`), Submissions (`https://voat.co/user//submissions`), and Comments (`https://voat.co/user//comments`) instead of Hot/New. The sidebar is the front page’s.

**Comment by talons1337** [comment]
I wonder what else this could possibly effect. /v/v?

**Comment by Scaarus** [comment]
I actually have a list. /v/undefined (you can randomly get subscribed to this, possibly a javascript error somewhere?), /v/subverses, /v/domains, /v/user. Each of those pages is used for displaying what they say, but they are intended to act as verses. When a user creates a verse with the same name, it pulls over some of the features from the real page. The verses weren't blocked for users to create, which I assume was just an oversight.

**Comment by voat** [comment]
This should no longer be an issue. Thanks!
