### ISSUE TITLE
Cloning the repository does not provide all the necessary files to run the project

### ISSUE THREAD

**Issue by lloydjatkinson** [voat/voat#467]
Hi,

Downloading the repo as a ZIP or cloning via VS's Team Explorer does not provide all the files needed to run.

**Web.Config**
Despite being in the root of the repo, it seems unavailable and has a warning icon next to it in Solution Explorer. To fix this delete the Web.config file from Solution Explorer, make a new one, and copy paste contents of the repo version: https://github.com/voat/voat/blob/master/Web.config

Same issue with sitemap.xml.

**SignalR/OWIN**
When the above issue has been fixed I tried running the project but get an exception on line 16 of Startup.cs:

`{"Could not load file or assembly 'Microsoft.Owin, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)":"Microsoft.Owin, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"}`

**Comment by liamlaverty** [comment]
Once you've followed your Web.config step, Open Package Manager Console

    Update-Package -Reinstall

Select "L" when prompted (as you don't want to overwrite the items already in the project). This should allow you to run the project properly.

**Comment by liamlaverty** [comment]
It's worth noting that you'll also need to sign up for a Recapcha account and you'll need to modify the connection strings to the two databases.

**Comment by kowsheek** [comment]
Also, the WebActivator package has to be renamed into WebActivatorEx since that [has been renamed](https://www.nuget.org/packages/WebActivatorEx/). Running `Update-Package` would throw the following error:

    Update-Package : Package 'WebActivator.1.5.0' is not found
    At line:1 char:1
    + Update-Package -Reinstall
    + ~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
        + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
