### ISSUE TITLE
Invalid column name 'FormattedContent' when loading /v/[name]/comments/[id]

### ISSUE THREAD

**Issue by liamlaverty** [voat/voat#468]
Fresh installation throws the error:

   Invalid column name 'FormattedContent'.
        Exception Details: System.Data.SqlClient.SqlException: Invalid column name 'FormattedContent'.

in file _LinkSubmissionDetails.cshtml on line 20:

    var commentCount = Model.Comments.Count(c => c.Name != "deleted");

Doesn't appear to be an issue in live, but I'm having issues opening comment pages. Anyone else seeing the same issue?

**Comment by trebach** [comment]
You need to run a script. Look at the second comment of the link.

https://github.com/voat/voat/commit/6eb69401ab12047d00c80fe8e1c46e8a81742862

**Comment by johnduhart** [comment]
Exactly that, you need to add a column. The SQL script was not updated.

**Comment by voat** [comment]
I pushed the new, updated script.
