### ISSUE TITLE
shorthand linking to wikipedia, google pagesetc...

### ISSUE THREAD

**Issue by mofosyne** [voat/voat#471]
http://www.halfbakery.com/idea/wikipedia_20uri_20schema

Instead of `[link](https://en.wikipedia .org/wiki/Dog)` a shorthand version might look like 

```
[[wikipedia: dog ]]

[[google: dog eats dog ]]
```

or 

```
[ dog article at wikipedia ](wikipedia:dog)

[ Just google it ](google: dog eats dog )
```
---

Maybe the `[[wikipedia: dog ]]` style has a different meaning than `[ dog article at wikipedia ](wikipedia:dog)`

Perhaps the link just show as a link. While the `[[]]` version shows up as a preview box of the content, e.g. the first paragraph of the dog article.

**Comment by DanielFlamino** [comment]
And why not just use the current way to make links?

**Comment by jksg** [comment]
@mofosyne Relevant: [Interwiki links](https://en.wikipedia.org/wiki/Interwiki_links) and [CURIE syntax](http://www.w3.org/TR/curie/). CURIE (Compact URI) is the standard you’re looking for.

Agreed with @DanielFlamino though, this seems unnecessary. “Dog” is a convenient example but does not represent most use cases. If I were thinking of sharing [Wikipedia’s featured article for today](https://en.wikipedia.org/wiki/Panama%E2%80%93Pacific_commemorative_coins), I would be far more likely to copy the URL, than either copy the title or type it out as `(wikipedia:Panama–Pacific commemorative coins)`.

**Comment by talons1337** [comment]
It's interesting but not particularly useful. It'd be a waste of valuable time to implement this. Probably only if `@ko` and co (hue hue hue good pun) finish Voat fully, or at least all the main and critical features. And at that point they'd probably want to take a break.

**Comment by PuttItOut** [comment]
Closed as this is not a planned feature.
