### ISSUE TITLE
EF and basic testing

### ISSUE THREAD

**Issue by pcwiek** [voat/voat#473]
I'm considering tinkering a little bit with DB access to speed things up (if you need help with that), but there are no semi-integration tests in place, so I have no real confidence that I won't break anything in the process.

I'd like to ask if it's OK to actually use, for example, [Effort](https://www.nuget.org/packages/Effort.EF6) to write tests that would check if basic queries that are compatible with LINQ provider actually return correct results? As I mentioned in #464, that won't replace full end-to-end tests because of differences in LINQ provider implementation and the fact that Effort has no way of supporting raw SQL, but for LINQ-compatible queries it could be a pretty good bottom line.

Thoughts?

**Comment by inkadnb** [comment]
:+1: 

I wouldn't mind helping with this side of things too.

**Comment by pcwiek** [comment]
@inkadnb I started tinkering with it on [ef-restructuring](https://github.com/pcwiek/voat/tree/ef-restructuring) branch in my fork. I'm not referencing the issue in commits just yet, I'll have to rebase it when I'm at least partially done and *then* reference the issue.

I went ahead and added xUnit as testing framework. There's a pending pull request to main repo with bare-bones scaffolding, but I'm using it for testing as I go.

**Comment by pcwiek** [comment]
@voat @inkadnb Would you rather have me create the pull request for the 'new' query support without removing the old queries, or should I refactor *everything* in one go, including controllers and models where appropriate?

**Comment by pcwiek** [comment]
@voat Any thoughts about my comment above?

**Comment by PuttItOut** [comment]
Closed as code has changed significantly
