### ISSUE TITLE
Chat in comments

### ISSUE THREAD

**Issue by LudwikJaniuk** [voat/voat#475]
Could we have this? Would be a great replacement for casual conversation in comments.

**Comment by inkadnb** [comment]
I vote we wait until we reach stability before we start trying to add new features.

**Comment by jksg** [comment]
@inkadnb Why, does *talking* about ideas on Github put additional stress on Voat’s servers? :p

@LudwikJaniuk There’s already a chat box in the sidebar of each subverse. How would this feature differ from that?

**Comment by LudwikJaniuk** [comment]
The chat box is in the subverse, but if one is in the comments of one specific post, there is no chatbox to my knowledge.

**Comment by pharno** [comment]
@jksg what he's saying is we should focus on stability and performance before new features

**Comment by LudwikJaniuk** [comment]
@pharno And I can totally agree. Just, putting it on the roadmap for the future.

**Comment by jksg** [comment]
@pharno Of course, the people who are actively developing the site are focussing on stability and performance right now, and we all appreciate that. But there’s no reason to stop *talking* about features (unless the noise is distracting them?)

**Comment by inkadnb** [comment]
@jksg I didn't imply that we couldn't talk about them. I just wanted to make it clear that new features will likely sit in the backlog for a while before they're even addressed by the primary development team.

**Comment by jksg** [comment]
@inkadnb Okay. I think that’s quite clear from the 84 open issues (some more than a year old) and thought it odd that you were cutting off discussion before it happened. We’re good then…

**Comment by talons1337** [comment]
No, I don't think it's necessary to have a per-topic chatbox. That's literally what the comments section is for. However, some form of chat history for each sub would be nice (though perhaps intensive on the servers and/or drives).

**Comment by PuttItOut** [comment]
Chat has been refactored and changed.
