### ISSUE TITLE
Improve Comment posting error handling

### ISSUE THREAD

**Issue by pharno** [voat/voat#476]
I tried to comment on a post, but got the 30 Second cooldown timer. I have not posted a comment during that timeframe, last comment was an hour ago.

It looks like the frontend interprets error messages from the backend as the cooldown timer.

I suggest to display the error on the frontend, like "Error posting comment (500: Internal server error)" or something like that

edit: I realize that this might have something to do with the deployment ongoing atm (?), but proper error handling is allways a good thing to do

**Comment by handsforphriar** [comment]
This is a problem for me too. I hate it.

**Comment by PuttItOut** [comment]
Fixed
