### ISSUE TITLE
Logged in while URL starts with voat.co, logged out while URL starts with www.voat.co, and vice versa.

### ISSUE THREAD

**Issue by ghost** [voat/voat#478]
Example: I was logged in while reading this and other "www."-less Voat pages:

https://voat.co/v/ideasforvoat/comments/130088

But if there's www. at the beginning, I am supposedly logged out:

https://www.voat.co/v/ideasforvoat/comments/130088

For testing, I logged out from "voat.co" and then logged in on "www.voat.co", now the above situation was reversed. I assume that this even means that I can be logged in with two different accounts simultaneously as long as I keep the URLs separate, which is kind of a feature, but I much rather would like the URL to be irrelevant.

**Comment by liamlaverty** [comment]
Fix is to rewrite always to either voat.co or www.voat.co, having 2 urls serve the same site is redundant - may cause some routing issues though, so it'll need a bit of testing.

Don't have the source with me just now, but to go with always-www, so long as it's running from >IIS7 modify web.config as such:

    <system.webServer>
      <httpRedirect enabled="false" destination="http://www.voat.co" exactDestination="true" httpResponseStatus="Permanent" />
        <rewrite>
            <rules>
              <rule name="non to www" stopProcessing="true">
                <match url=".*" />
                <conditions>
                  <add input="{HTTP_HOST}" pattern="^voat.co$" />
                </conditions>
                <action type="Redirect" url="http://www.voat.co/{R:0}"
                     redirectType="Permanent" />
              </rule>
            </rules>
        </rewrite>
    </system.webServer>

**Comment by DanielFlamino** [comment]
I think this has been a problem only since this weekend. IIRC it used to always redirect to https://voat.co, no matter if you typed the www. bit or choose to use http://

**Comment by talons1337** [comment]
Hm, that explains why I was logged out on my phone... 

Eh, why was www removed anyway? I mean I didn't really use it but I don't see why not have it. Then again I cannot into servers.

The easiest solution would be just removing www so I think it would be wisest to do that. Saves a lot of time and effort and doesn't make any dramatic side effects. The only problem I can see with this fix is that www could eventually creep up again unnoticed, but I don't servers so I might be wrong.

**Comment by voat** [comment]
This should no longer be an issue.
