### ISSUE TITLE
Add flickr expando iframe

### ISSUE THREAD

**Issue by jrupp** [voat/voat#480]
Some communities prefer all their images to be on flickr instead of imgur or slimgur or others.  Please add an IFrameEmbedderExpando for flickr.

**Comment by talons1337** [comment]
You don't (or shouldn't) use IFrames. They're unneeded and flickr uses frame-busting so it doesn't work anyway. RES just puts an <img> element. That should work just fine. 

Unless I'm misunderstanding and flickr has some way to embed via iframe and/or iframe refers to something else.

**Comment by PuttItOut** [comment]
We need to get convo started about embedding. Right now we use a custom voat OO JS framework to parse expandos and it handles EVERY expando on the site (Comments, Posts, Messages, etc.). 

I want to get people's thoughts on extending our custom framework or using 3rd party framework, or using a combination of the two.

Thoughts? I know @quantumwannabe had some suggestions on this subject.

**Comment by quantumwannabe** [comment]
#401 was my proposal. oEmbed is an open format for describing how to embed a sites content and is supported by a fair amount of large sites (including flickr ([example](https://www.flickr.com/services/oembed?url=http%3A//flickr.com/photos/bees/2362225867/))).

**Comment by kiwwisk** [comment]
Hello,
my pull request #587 uses SoundCloud oembed URL for it's expando (trying to reuse existing code). Maybe with little fiddling and polishing it could be made useful for all the providers listed on http://www.oembed.com/

**Comment by voat** [comment]
This should already be implemented.
