### ISSUE TITLE
What browsers do we need to support?

### ISSUE THREAD

**Issue by yotamN** [voat/voat#481]
If I want to start working more on the client side of the site I need to know what browsers I need to support, I understand you are using jQuery 2 so IE9+?

**Comment by minial90000** [comment]
I think at this point most users use google chrome or Safari. Internet explorer really isn't common. To answer your question it should be all of them.

**Comment by yotamN2** [comment]
Where did you get those stats? Because maybe that represent the whole internet (and it's not, IE is used as much as Safari and Firefox is really close behind) but we need statics of voat because maybe there aren't any IE9 users that we need to support.
And what do you mean "all of them", are you talking about evergreen browsers only?

**Comment by travis-g** [comment]
From a tracking pixel in my subverse's sidebar, out of a total of 677 sessions the breakdown was:

Browser | Sessions | Percent
----------|----------|-----------
Chrome | 376 | 55.54%
Firefox | 244 | 36.04%
Safari | 47 | 6.94%
Opera | 5 | 0.74%
IE | 1 | 0.15%

Plus a few others at ~1 session each. Like minial said, all browsers should be supported to allow everyone to use Voat with what they're comfortable with or whatever is available. Most of the time pages work regardless of browser, but they'll appear different.

**Comment by yotamN2** [comment]
@travis-g I'm not sure you understand the question, of course that site should support all the 5 major browsers, the question is what version, only evergreen browsers or should we have backward compatibility and if so, how much.

**Comment by travis-g** [comment]
@yotamN2 if users only have access to IE8, if Voat can't accommodate them they can't use the site. It may be an extreme minority but support should be as broad as possible, not just the evergreens.

**Comment by yotamN2** [comment]
@travis-g I agree that we shouldn't support only evergreen browsers but IE8? Really? Even big companies started to drop it/take more money for this, so why should we support it? I think that we should notify Internet Explorer 8 and Safari 7.1 users that their browser is outdated and they should upgrade or switch. 

Don't forget, if we don't support the browser it doesn't mean they see blank page, they just see it a little bit ugly.

**Comment by umilmi81** [comment]
No way. This is a tech site.  Evergreen only. Like you said, older browsers
will still see stuff it will just be ugly. If they are using IE8 they
better get used to sites not working 100%.

**Comment by travis-g** [comment]
IE8 users wouldn't be able to use/see Voat *as it was meant to be used/seen,* sorry. I can't tell you what to do so do what you are willing to do. In a perfect world IE8 and other antiquated browsers should be supported fully.
