### ISSUE TITLE
"Whoaverse" -> "Voat"

### ISSUE THREAD

**Issue by deltaidea** [voat/voat#482]
I think it's a good idea to rename "Whoaverse" directories, files, and things in the code itself and use the word "Voat" instead.

What stops us?

**Comment by inkadnb** [comment]
I think once the code base is stable this can be done but now that we've got a lot of hands in the pot doing this now could make for some annoying merges.

**Comment by moshmage** [comment]
I don't think that this is a change that can be done easier as time passes. But then again, "find usage in path, replace with" is an option in some IDEs

**Comment by talons1337** [comment]
It's a bit too late to replace WV with V now.

**Comment by kiwikku** [comment]
So we're still stuck calling them subverses?

**Comment by DanielFlamino** [comment]
Yes

**Comment by kiwikku** [comment]
Oh well.

**Comment by talons1337** [comment]
Subvoat is a silly name anyway.

**Comment by kiwikku** [comment]
Yeah but the naming conventions.. XD

**Comment by deltaidea** [comment]
I consider this resolved. Good job, everybody!

**Comment by mgiuffrida** [comment]
[We did it, Whoaverse!](http://i3.kym-cdn.com/photos/images/newsfeed/000/987/428/82a.gif)
