### ISSUE TITLE
When a head mod deletes their account- no one moves up to take their place. 

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#487]
[See this thread](https://voat.co/v/help/comments/136406)

**Comment by Scaarus** [comment]
What would be the best way to handle this? Appoint the mod who has had the highest clearance for the longest amount of time?

**Comment by DanielFlamino** [comment]
That's probably the best thing that can be done, unless some sort of "second in command" is appointed.

**Comment by Scaarus** [comment]
The only other thing I could think of would be popular vote, but that may be open to abuse.

**Comment by PuttItOut** [comment]
Closed as this is not a planned change.
