### ISSUE TITLE
Shortened permalinks to comments and submissions

### ISSUE THREAD

**Issue by talons1337** [voat/voat#490]
Adapted from this idea by enchanted-forest: https://voat.co/v/ideasforvoat/comments/136363/

Perhaps something like voat.co/s/<submission id> for submissions and voat.co/c/<comment id> for comments.

**Comment by TNTGav** [comment]
I don't think this would be too difficult to implement. We could just register a new route and that would be enough. Do we need to display this information in the sidebar though?

**Comment by culverit** [comment]
enchanted-forest here, maybe if you click a button it can reveal it, but it doesn't need to be there unless you want to share something really.

**Comment by slampisko** [comment]
Just want to mention that, as I said in the comments of my earlier post on this topic [https://voat.co/v/ideasforvoat/comments/94040], the /s/ in submission shortlinks is not really necessary. Using /c/for comments and nothing for submissions makes more sense from the current implementation perspective and makes submission shortlinks two additional characters shorter.

**Comment by talons1337** [comment]
No. You can't have the shortened submission links in the "root" url of voat. You would /need/ to have the /s/

**Comment by slampisko** [comment]
I see, didn't know it was technically impossible. Is there a particular reason why? It seems to me like doing something like this would be sufficient:

http://stackoverflow.com/questions/29526268/need-to-simplify-urls-via-asp-net-mvc-routing-pattern-in-routeconfig-cs

**Comment by TNTGav** [comment]
Anything is possible, the actual question is whether it is a good idea or not, and in this case it isn't. For example it makes routing anything else difficult and messy from the root level.

**Comment by slampisko** [comment]
I see, thanks for clearing that up.

**Comment by PuttItOut** [comment]
Implemented
