### ISSUE TITLE
Remove "cooldown" from sending PMs

### ISSUE THREAD

**Issue by Zer0t3ch** [voat/voat#493]
Sending a PM should not be in any way related to the "cooldown" system. Sometimes there are a lot of people to reply to.

**Comment by talons1337** [comment]
Ah, now I know why atko doesn't respond to PMs anymore!

**Comment by weverett** [comment]
One problem with removing the cooldown altogether is that it allows bots to quickly spam lots of users.

**Comment by jksg** [comment]
@weverett The cooldown could only kick in for new messages and not replies to existing PMs.

**Comment by PuttItOut** [comment]
Closed as this is not a planned feature.
