### ISSUE TITLE
Occasionally, Voat will tell you to wait 30 seconds but the comment will still go through

### ISSUE THREAD

**Issue by talons1337** [voat/voat#495]
No steps to reproduce but there was one occasion where I posted the same comment like, I don't know, probably 7 times because it kept telling me to wait 30 seconds every single time I hit submit.

The comment also won't show up like it normally does when it goes through.

**Comment by Scaarus** [comment]
I added to PR #472 to fix this. SubmitComment was adding the comment and then returning a bad request error. The commit I added will return an OK error instead.

**Comment by kiwikku** [comment]
The entire wait 30 seconds thing should be removed. It can become annoying when replying to lots of posters in a thread, the spam filter should trigger when you make more than 5 comments in 2 minutes instead.

**Comment by DanielFlamino** [comment]
I can't find the comment anymore, but Atko said that 30 seconds would be the lowest he'd go, after changing it from 2 minutes.

**Comment by kiwikku** [comment]
Thanks for the quick reply. So it used to be 2 minutes? 
BTW, what do you think of my anonymity and bump suggestions?

**Comment by PuttItOut** [comment]
Fixed
