### ISSUE TITLE
Bad gateway trying to reach a certain page

### ISSUE THREAD

**Issue by talons1337** [voat/voat#496]
https://voat.co/v/AskVoat/comments/137727 

I've been trying to reach this AskVoat question like a million times and every single time it says bad gateway. I've tried opening a different tab and going via google and nothing works. The rest of the site works without a problem (okay sometimes the page says service unavailable) but this page just refuses to let me through.

**Comment by PuttItOut** [comment]
This is very interesting indeed. A quick look through the data shows nothing obvious.

**Comment by PuttItOut** [comment]
Fixed
