### ISSUE TITLE
Design improvement strategy

### ISSUE THREAD

**Issue by natemcguire** [voat/voat#498]
I've got a few design updates / pull requests for improvements and bug fixes. What do I need to do to get access to make a pull request? Most of them I've already got committed and tested locally and are simple things (like improving display for wider resolution and small design fixes). Happy to contribute and take these on if there's not someone else working on it already.

**Comment by AmarJayR** [comment]
Are you asking how to make pull requests on Github? If so just make a fork of this repo, commit all changes to the fork, press the green compare button, put in your repo, and then click "Create pull request"

**Comment by jksg** [comment]
To add to what Amar said, don’t just commit everything but try to submit separate pull requests for specific feature changes (e.g. one pull request for widescreen fixes). Makes it easier for Voat to merge the changes they want. You can probably group minor fixes together though.

@Nurdoidz does the base CSS and light and dark themes, so he’s the boss on design issues.

**Comment by PuttItOut** [comment]
Closed as code has changed significantly since issue logged.
