### ISSUE TITLE
Add an "active" or "bumped" tab next to hot, rising and new on subvoats that show bumped threads. Also consider compact/grid view to see more threads on a page.

### ISSUE THREAD

**Issue by kiwikku** [voat/voat#499]
One of the biggest missing features on reddit is the lack of bumping: There's no way to find or see threads with the latest replies. This allows threads which are heavily downvoted to essentially be buried from view, and is probably the most glaring issue with the site. Not to mention heavily-upvoted threads with little or no replies represent a barrier to discussion (low effort posts)

Threads which are more than a few hours old, even if they have active conversations going on inside are forced to die. If you add an option to see threads with the latest replies, then posts with current discussions will be pushed to the top, not just heavily upvoted ones. In bumped mode, new posts could be highlighted in some way. 
---

Grid view is a "power user" feature, and could be represented by a small grid icon in the corner of a sub, next to your name. Clicking it shows you an alternate representation of the subvoat, in[ "catalog" form not unlike this](http://8ch.net/tech/catalog.html), only tidied up and changed to fit voat's style. Grid view is helpful since it lets you view far more threads at once than you can in feed view. Browsing is quicker and easier on the eyes. The default image of a thread would be the voat goat with "no image". 

If grid view isn't a good format for text, then compact view similar to what gmail uses could work to fit more information on a page.

**Comment by DanielFlamino** [comment]
I like both of these suggestions and think they might be useful.

**Comment by kiwikku** [comment]
Thanks! Hopefully there may be time to implement them when the mess dies down.

**Comment by PuttItOut** [comment]
Partially implemented in API logic.
