### ISSUE TITLE
Logging in returns generic error message

### ISSUE THREAD

**Issue by Marou443** [voat/voat#502]
Rather than username or password incorrect.  Account name and password are valid.  Issue began today.

![image](https://cloud.githubusercontent.com/assets/12958271/8242546/21fc921a-15de-11e5-931d-052ddba739ab.png)

**Comment by PuttItOut** [comment]
We had a database issue after a site update. Shouldn't be an issue any longer.

**Comment by PuttItOut** [comment]
Fixed
