### ISSUE TITLE
Some html tags are going through the whitelist

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#503]
See this thread -> https://voat.co/v/Voat/comments/144925

That uses an img tag, but according to Atko's comment on #434, that tag is not supposed to go through.

**Comment by PuttItOut** [comment]
Someone is getting fired for this one.

**Comment by DanielFlamino** [comment]
It's Atko, isn't it? I knew you never should have hired him. Can't trust that guy.

**Comment by PuttItOut** [comment]
Are there any other HTML elements that pass through that shouldn't?

**Comment by DanielFlamino** [comment]
I have no clue. How many tags are there to even test?

**Comment by jksg** [comment]
http://www.w3.org/TR/html-markup/elements.html?

**Comment by DanielFlamino** [comment]
Hmm... Not as many as I thought there would be. I'll check it out tonight.

**Comment by talons1337** [comment]
Well I know that <sub> is part of the toolbar so I suppose it should be allowed through for sure. 

I'll go ahead and test every single HTML element and see what gets cut and what doesn't.

**Comment by quantumwannabe** [comment]
This happens because for HTML escaping we are using MarkdownDeep's safe mode. Images are allowed in this mode.
Full list of allowed tags:

"b", "blockquote", "code", "dd", "dt", "dl", "del", "em", "h1", "h2", "h3", "h4", "h5", "h6", "i", "kbd", "li", "ol", "ul", "p", "pre", "s", "sub", "sup", "strong", "strike", "img", "a"

Allowed attributes:
    "a": href, title, class
    "img":  "src", "width", "height", "alt", "title", "class"

**Comment by DanielFlamino** [comment]
According to Atko the "img" and "a" tags should not be whitelisted.

>"b","blockquote","code","dd","dt","dl","del","em","h1","h2","h3","h4","h5","h6","i","kbd","li","ol","ul","p", "pre", "s", "sub", "sup", "strong", "strike"

**Comment by quantumwannabe** [comment]
Removing them from MarkdownDeep is probably the easiest way. See https://github.com/toptensoftware/markdowndeep/blob/37cd165d154d3b1e7190af6253cf5f6d5710cdc4/Backup/MarkdownDeep/HtmlTag.cs#L82-125
