### ISSUE TITLE
"Blocking" subverses is not working for me

### ISSUE THREAD

**Issue by zwhitchcox** [voat/voat#504]
I clicked "block" and "unsubscribe for multiple subs, and they are still showing up on my front page.

**Comment by jksg** [comment]
Your front page (i.e. http://voat.co while logged in) shows the equivalent of /v/all unless you are subscribed to at least one subverse, in which case it will show posts from all your subscribed subverses.

The block subverse feature is currently bugged for /v/all/hot specifically, I believe.
