### ISSUE TITLE
Incorrect "next" link on sent messages page

### ISSUE THREAD

**Issue by Mumberthrax** [voat/voat#505]
Discovered this small bug a moment ago. A search on here on github for the terms "sent","mail", and "page" returned nothing about it, but did turn up one result /v/bugs from three months ago: https://voat.co/v/bugs/comments/53979 and one result on /v/voatdev from 2 months ago https://voat.co/v/voatdev/comments/78148

From here: https://voat.co/messaging/sent

Scroll scroll down and click "next", it sends you not to page 2 of your sent items but to page 2 of your inbox for received messages.

That is, it *should* send you to https://voat.co/messaging/sent?page=2  
but instead it sends you to https://voat.co/messaging/inbox?page=2

Similarly when viewing https://voat.co/messaging/sent?page=2, both the "prev" and "next" buttons go to the inbox, not pages of sent messages.

**Comment by DanielFlamino** [comment]
#723 should fix this.
