### ISSUE TITLE
Thumbnails not showing up on submissions.

### ISSUE THREAD

**Issue by Identifier1** [voat/voat#506]
When submitting a link to voat thumbnails aren't properly loading. I've noticed that if I link directly to the image it will show up. However, if I link to an album or Gfycat it won't show up. Example here NSFW https://voat.co/v/MyFavoritePornstars/comments/145837 and here NSFW https://voat.co/v/MyFavoritePornstars/comments/145832

**Comment by Aaron-P** [comment]
Right now thumbnails are only generated for direct image links (based on extension) and pages with open graph metadata.  More complex parsing can be added but that starts to go down the rabbit hole of trying to automatically determine relevance.

**Comment by PuttItOut** [comment]
Fixed
