### ISSUE TITLE
Database design and inconsistencies

### ISSUE THREAD

**Issue by pcwiek** [voat/voat#507]
There are several different things I wanted to tackle here. Not all of those are performance related, more consistency-related and thinking about streamlining the approach would probably make supporting the application way easier.
### <a name='table_names'></a> Table names

Some tables are `PascalCased`, some are `Imnotsurewhatthatcaseis`. Personally, I think that just standardizing to `PascalCase` everywhere would make it easier on the eyes.
### <a name='fk_names'></a> Foreign key column names

Some foreign key columns are named `RelatedTableNameId`, some are `RelatedTableName_id`. Whether it's `RelatedTableName_Id` (pascal casing again) or `RelatedTableNameId` doesn't really matter as long as naming is the same across the project.
### <a name='col_names'></a> Column names

Similar to [table](#table_names) or [FKs](#fk_names), there are columns like `Created_by` or `Banned_by`, there are `Markedasunread`, there are full snake case (`promoted_submission_id`) and pascal cased (`ReasonForRemoval`) columns.
My vote goes, again, towards `PascalCasedColumnNames` everywhere.
### <a name='timestamp_usage'></a> Using `DateTime.Now` for timestamp

As soon as you have a second server in a different time zone, that will come back to haunt you. If you want timestamps:
1. Use `DateTimeOffset.Now` stored in `datetimeoffset(7)`, which is very useful if you want to display the date and time in user's time-zone _and_ you also want to support easy comparison between time zones.
2. Consistently use `DateTime.UtcNow` _everywhere_ in the application, which might be sometimes confusing (if user submits a post at 4 PM UTC-4, displayed time would be 8 PM), but all the dates could be compared.
### 'Name' is the natural key for `subverse` table

My opinion is that `subverse` table should have a surrogate key (`Id, INT`, or whatever the naming case might be) with unique index on `Name`.
### Losing the relation between users and all other tables

Since there are two databases (one for users, one for everything else), any relation and automatic constraint checking capability in the main database that should point to any user (for example, 'sent by' in the message) is lost. Why are there two separate databases for that anyway? ASP.NET Identity just adds a couple of tables and that's it...
### Audit fields

Did you notice that property `Timestamp` is set manually all over the place? EF provides enough abstraction to set this field automatically when changes are saved. All entities that should be stamped should just implement `ITimestamped` interface that would expose that property. That also ties back to consistency in [timestamp usage](#timestamp_usage).
### Missing indexes (perf.)

Currently, there are no indexes in the DB at all. It's not a problem when tables are small and app is used by a small group of people, but at one point you really have to set your indexes. SQL Server doesn't automatically index FK column, so those indexes should be added because of joins. Another clear candidate is any type of `UserName` or `Name` column, queries are _very_ often filtered by it.

I think that's it for now...

Thoughts?

**Comment by inkadnb** [comment]
All good points.

As a side note, I usually rely on the database to determine timestamps
since it's fairly central, obviously you can have multiple databases but in
general it's better practice to have the db determine timestamps.

**Comment by pcwiek** [comment]
@inkadnb Good point. Having `SYSDATETIMEOFFSET()` as default column value is a fool proof option.

It's just something I wanted to point out in general, I'm in the middle of restructuring some of the EF stuff so it's not the best moment for me to make changes to SQL scripts and data model, but it will have to be addressed at one point.

**Comment by voat** [comment]
Very good points, thank you. 

There are indexes in both databases which most likely weren't included in the schema scripts in this repository. 

We'll use PascalCasing when we get a chance to work on schema changes. As you probably noticed, all new tables are already using PascalCasing. The DB has survived several iterations and origins of some tables date back to when Voat was an asp.net webforms project. 

Regarding the 2 databases: I like to keep the users accounts in a separate database and even on a different server. This is just a personal preference with pros and cons of its own, where cons outweigh the pros if we are considering that user registration and authentication process may become its own, standalone system one day. 

Again, thank you for these points, it can never hurt to have multiple eyes on this. We'll work on fixing the remaining issues gradually.

**Comment by pcwiek** [comment]
@voat I thought as much :) I can help with those, at least to a degree, but it will have to be gradual. I'm in the middle of tinkering with EF to make the queries a bit more predictable and - arguably - more efficient.

You should definitely include indexes in the SQL file then...

**Comment by PuttItOut** [comment]
Closed as code has changed significantly since issue logged.
