### ISSUE TITLE
Context link: Is the double-slash intentional or a mistake without effect?

### ISSUE THREAD

**Issue by ghost** [voat/voat#532]
Example - the permalink is this:

https://voat.co/v/gaming/comments/145885/354392

The context link is this:

https://voat.co/v/gaming/comments/145885//354392#354392

These links were given to me by my comments page: https://voat.co/user/king_of_the_universe/comments

EDIT: Entering the link _without_ the second slash doesn't seem to cause any different behavior. But I did not do any tests with a non-root level comment or in a situation where there are further replies. (Nobody talks to me, I am so alooooooooone!;)

**Comment by Aaron-P** [comment]
This seems to be caused by comments that don't have parent ids, I'm not sure why parentid is inserted into the url at all. https://github.com/voat/voat/blob/5a2ac7d455068ca6c8f1b078bd36ab8cbc81ad05/Whoaverse/Whoaverse/Views/Shared/Userprofile/_UserProfileComment.cshtml#L115

**Comment by God--owner-of-the-universe** [comment]
So, the explanation is: Side-effect of the string building process that happens for root comments. Seems quasi wanted, but since the URLs look weird to the user, I'm not sure if this issue should be closed.

**Comment by PuttItOut** [comment]
Fixed
