### ISSUE TITLE
click + drag image resize

### ISSUE THREAD

**Issue by 0101adm** [voat/voat#537]
when you click + drag on any pic (showing inline), it will zoom out but zooms underneath the right sidebar.

**Comment by DanielFlamino** [comment]
Working as intended: #354

**Comment by 0101adm** [comment]
OSX 10.10.2 / Firefox 38.0.5

<iframe width=400 height=385 frameborder="0" scrolling="no" src="//screencast-o-matic.com/embed?sc=co1tc1frKG&w=400&v=3"></iframe>

**Comment by jksg** [comment]
That’s how it works. When you zoom into something it does not change or leave the container but only shows you what you want to zoom in on. You can scroll and pan within the container.

**Comment by 0101adm** [comment]
then id like to request that media overlay on the side bar as it zooms out.

[![IMAGE ALT TEXT HERE](http://img.youtube.com/vi/L515CLdyHpg/0.jpg)](http://www.youtube.com/watch?v=L515CLdyHpg)

**Comment by quantumwannabe** [comment]
Try using a full-width userstyle. (https://userstyles.org/styles/111655/full-width-voat) It should give you more room for the image to expand before hitting the sidebar.

**Comment by PuttItOut** [comment]
Fixed
