### ISSUE TITLE
Any user can accept any mod invite for another user

### ISSUE THREAD

**Issue by Scaarus** [voat/voat#540]
Lets say I invite Atko to be moderator of my subverse. Atko doesn't immediately know if he wants to moderate it, so he leaves the invitation in his inbox. Some other user comes along and guesses the mod invite id correctly and visits voat.co/acceptmodinvitation/<id>. Atko is now a moderator of the subverse even though it wasn't him that accepted.

**Comment by talons1337** [comment]
What's more is that they are simply numbers so you could write a program to accept every mod invitation for everyone.

**Comment by voat** [comment]
Thank you for reporting this! :)

**Comment by voat** [comment]
Also, if you have the same username on voat, I added a thank-you badge to your profile for this discovery :)

**Comment by Scaarus** [comment]
Thanks! :)

**Comment by Aaron-P** [comment]
This method is still vulnerable to CSRF to conduct the same sort of attack with a bit of social engineering.
