### ISSUE TITLE
Entity Framework Migrations

### ISSUE THREAD

**Issue by Aaron-P** [voat/voat#542]
Is there any particular reason for not using migrations provided by Entity Framework, which is already being used, to define database schema?  It would make changes to the schema to support bug and feature fixes a lot easier to implement from within the project.  Absent that, is there an established means of requesting a DB schema change in a pull request?

**Comment by pcwiek** [comment]
Good question about the schema changes. I have never used EF Migrations in depth (I prefer to have custom scripts for that), so I'm just wondering whether it's only for tables, or other elements too (views, stored procedures, user-defined functions, table-valued parameters etc)?

I'm working on some improvements to the queries and [some of the queries in-app would be a lot simpler if the body was moved into a view where appropriate](https://github.com/pcwiek/voat/blob/402d33ce48fd422790528d70dbcc84098dd6af7d/whoaverse.sql#L996-L1043). That would have to be pulled back to base SQL file at one point...

**Comment by voat** [comment]
EF migrations are currently only used for changes to voat users DB. Any changes to main DB are usually made first on SQL server and then EF models are updated. If you only need a minor schema change, we could process it if you open a new issue as there have never been requests for schema changes so far and thus no (yet) established means of requesting a schema change.

**Comment by Aaron-P** [comment]
@pcwiek The current stable version of EF is only for constructing tables, however you can include raw sql (e.g. create view) along with a migration, so all database handling could be handled centrally in that way.  I don't know about the upcoming version of EF.

**Comment by Romoku** [comment]
Something to look at regarding migrations is [Insight.Database.Schema](https://github.com/jonwagner/Insight.Database.Schema). The models can be kept in sql and the framework will calculate the diff needed to update the database.

**Comment by pcwiek** [comment]
I haven't used the schema migrations tool, but Insight.Database is a high quality library - full documentation, easy to use and works as advertised. I'd expect Insight.Database.Schema to follow suit in quality.

**Comment by PuttItOut** [comment]
Closed as code has changed significantly since issue logged.
