### ISSUE TITLE
Allow upvotes in anonmode [Enhancement]

### ISSUE THREAD

**Issue by theanonymous1** [voat/voat#548]
I have not seen how anon mode is implemented but if it is not possible to allow upvotes in anon mode then all posts should have the vote counter set to the default value.

**Comment by DanielFlamino** [comment]
Votes are not possible and all posts are set to the default value of 1 point.

**Comment by theanonymous1** [comment]
When I say all posts I mean all posts ever created in the history of the subverse, sorry if there was any confusion in the original post.

**Comment by fringenerd** [comment]
As a temporary solution, the sub's mod could delete posts with higher scores. It's not an ideal workaround, but it works.

**Comment by PuttItOut** [comment]
Implemented
