### ISSUE TITLE
Minor - Incorrect calculation of time span for post age

### ISSUE THREAD

**Issue by gavsto** [voat/voat#550]
Referenced here:
https://voat.co/v/voatdev/comments/173538

The code I believe is triggering this (line 59 in Utils/Submission.cs)

``` csharp
            else if (span.TotalHours > 1 || Math.Abs(span.TotalHours - 1) < Tolerance)
            {
                //hours
                result = String.Format("{0} hour{1}", (int)span.TotalHours, IsPlural((int)span.TotalHours));
            }

```

The tolerance is set to 0.01 but I can't see any reason for the tolerance being there at all. There is a period of around 36 seconds where I believe the or evaluates true.

Anyone have any clue why the tolerance is there and it's not just using a span.TotalHours >= 1 ?

**Comment by pr1m4zu1** [comment]
I submitted a pull request to fix this, I'm not sure why there was a tolerance either.

**Comment by PuttItOut** [comment]
Fixed
