### ISSUE TITLE
Limit the number of accounts a user can have with same IP

### ISSUE THREAD

**Issue by voat** [voat/voat#556]
Currently there is a lot of copy-paste comment spam floating around. All of it is coming from a single IP address with 29 different voat accounts.

As a temporary measure, we should limit the number of voat accounts that can be made to, say, 3, with the same IP address.

I understand there may be entire organizations or universities behind a single IP address, but since Voat is a pretty small community, manual spam of this sort is noticeable. Other ideas are welcome of course.

**Comment by pharno** [comment]
isnt there a domain blacklist?

**Comment by voat** [comment]
Yes, but domain blacklist is only relevant for link type submissions and it doesn't help with comments. This is only concerning creation of new voat user accounts.
