### ISSUE TITLE
/v/test or /r/test is expanded inside link text

### ISSUE THREAD

**Issue by mgiuffrida** [voat/voat#559]
A comment like this:

```
[Test link /v/test](http://example.com)
```

displays as:

```
Test link [/v/test](/v/test)
```

The whole thing correctly links to example.com, but the /v/test shouldn't be expanded into Markdown syntax within the link text.

**Comment by mgiuffrida** [comment]
I guess if the entire comment content is passed through the ContentFilter, then the fix should be within the filters. [SubverseLinkFilter.ProcessContent](https://github.com/voat/voat/blob/4f5ad24fce445855dfaf791268829e616eea5b64/Whoaverse/Whoaverse/Utils/Components/ContentFilters.cs#L109-L115) and RedditLinkFilter.ProcessContent need to check that the content isn't within a link.

**Comment by DanielFlamino** [comment]
[This is fixed on Voat's new API beta test site.](http://i.imgur.com/0bDkqfw.png)

**Comment by mgiuffrida** [comment]
@DanielFlamino where does the source for that live?

**Comment by DanielFlamino** [comment]
I think [this](https://github.com/PuttItOut/voat/) is it. But @PuttItOut is the one who knows the answer for sure.

**Comment by talons1337** [comment]
Offtopic: You have so many badges on the fake voat

**Comment by DanielFlamino** [comment]
Still offtopic: http://fakevout.azurewebsites.net/v/Universall/comments/148

**Comment by talons1337** [comment]
>Alt + F4: Instantly give 1 Billion upvotes to yourself

Gee I don't know. Can't do that on mac. Obviously you need `Cmd + Q` keyboard combination for mac users.

**Comment by PuttItOut** [comment]
Fixed
