### ISSUE TITLE
focused sidebar buttons shouldn't change text color

### ISSUE THREAD

**Issue by mgiuffrida** [voat/voat#569]
In Light mode, `.btn-whoaverse-paging:focus` is `color: #fff`. This makes the block and chat `<button>`s white on focus, which is hard to read against the `#a7deff` background.

Other buttons, like the contribute buttons and the paging buttons, remain black on focus. And in Dark mode, `.btn-whoaverse-paging:focus` is the same color as `.btn-whoaverse-paging` (white).

![focused-button](https://cloud.githubusercontent.com/assets/1449368/8445012/fa46e8b0-1f4c-11e5-9d01-7d40157de079.png)

**Comment by TNTGav** [comment]
I've submitted a pull request to remove the CSS doing this.

**Comment by PuttItOut** [comment]
Fixed
