### ISSUE TITLE
Cannot post dongers in titles ( ﾉ ﾟｰﾟ)ﾉ

### ISSUE THREAD

**Issue by wanghealerr** [voat/voat#571]
https://voat.co/v/raiseyourdongers

It's not possible to post dongers from the sidebars that use text from languages that aren't english.

༼ຈل͜ຈ༽_•︻̷┻̿═━一

Check out the sidebar - I don't know what should be put in.

**Comment by moeVoat** [comment]
This is not a bug.
High ANSI characters are intentionally disallowed in submission titles.

**Comment by talons1337** [comment]
Why are they disabled? Everything in unicode, as long as it doesn't break the site in a way that allows injections and whatnot, should be allowed.

**Comment by voat** [comment]
Because some characters really mess things up visually. Until we can sit down and whitelist the “good” characters, this will have to wait.

**Comment by talons1337** [comment]
Does this include foreign language characters?

**Comment by DanielFlamino** [comment]
Currently yep, those aren't allowed. I assume those will be whitelisted in the future.

**Comment by ekg** [comment]
Seems the wontfix tag suggests otherwise. This just isn't a priority for @voat.
