### ISSUE TITLE
DB broken? Cannot create comment in this post but in others.

### ISSUE THREAD

**Issue by God--owner-of-the-universe** [voat/voat#573]
https://voat.co/v/DebateanAtheist/comments/188770

When I make a root comment (e.g. "PING"), the button changes to "Doing the magic..." forever. When I try to make a new comment in a new tab with that or a different post too quickly, the 30 second wait message appears, so the server knows of my actions.

When I try to reply to the only comment in that post, the button changes to "Please wait..." for a normal time, and then everything changes to a state as if I had never attempted to write/send the reply.

Reloading or "loading more" doesn't make the attempted comments show up.

I can interact normally with the site in this post, for example:

https://voat.co/v/AskVoat/comments/188974

So, I guess the database is somehow borked for that one post. Possibly an angle to investigate for improvements/fixes.

**Comment by voat** [comment]
Are you banned in that sub? 

https://voat.co/v/DebateanAtheist/modlog/bannedusers

**Comment by God--owner-of-the-universe** [comment]
Right. That's me. I didn't receive a notice of ban or anything, and the interface didn't behave in a meaningful way. I assume that this will change in the future. Closing the issue.

Side-note: Fuck Xanin! I am so fed up with power-abusing moderators. Little do they know that I have the power to ban them from my cosmic, and my list of permabans is long. One more. So be it.

regards

God
