### ISSUE TITLE
Can't grant ban powers to subverse moderators

### ISSUE THREAD

**Issue by tinoesroho** [voat/voat#575]
I can't grant my moderators banning powers. This is problematoc for a chat centriv sub.

**Comment by DanielFlamino** [comment]
Only the level 1 moderator can ban users

**Comment by tinoesroho** [comment]
Can't add level 1 users, either. Voat needs a specific ban power, not
necessarily tied to CSS editing powers.

**Comment by daimoneze** [comment]
I think what @DanielFlamino is saying is that only having 1 user able to ban per subverse is intentional.

**Comment by DanielFlamino** [comment]
I don't think that is the case. I think only the level 1 mod can ban people because there currently are only 2 levels of moderators and banning isn't a power that you might want to give to every moderator. The "only one level 1 mod" thing is just because only one person can create a subverse.

**Comment by PuttItOut** [comment]
Fixed with new moderator roles.
