### ISSUE TITLE
Sidebar does not appear in Firefox 38.0.5 on macbook pro retina

### ISSUE THREAD

**Issue by pcasaes** [voat/voat#576]
Sidebar does not appear in Firefox 38.0.5 on macbook pro retina. Happens in both light and dark mode. Using FF's developer tools I noticed it carried the following:

    `.side {
        position: absolute;
        top: -11px;
        left: -300px;
        transition: 500ms left;
        background-color: rgba(51, 51, 51, 1);
        margin: 0;
        overflow-y: auto;
        overflow-x: hidden;
        z-index: 2;
        height: calc(100vh - 81px)
    }`

Disabling the `position:absolute` was enough to make it appear. I then noticed that it's part of the following media rule:

`@media(max-width:870px)`

Shouldn't be applied since the screen is much wider. I'm not 100% certain but I believe that according to CSS3 specs a space is required between `@media` and `(max-width:870px)`.

**Comment by pcasaes** [comment]
I believe I might be right. Keywords immediately followed by left parenthesis denotes a [functional notaton (8. Functional Notations)](http://www.w3.org/TR/css3-values/). `@media` isn't a function.

**Comment by jksg** [comment]
Can’t reproduce on FF 38.0.5 / OS X 10.10.3 rMBP.

Sorry to ask the obvious, but is your window narrower than 870px…? If so, the sidebar is collapsed and there is a “burger” icon in the top-left that brings it up.

**Comment by pcasaes** [comment]
Ah! you're correct. It was set at 831px because I had it zoomed in. Thanks.
