### ISSUE TITLE
Text wrapped around < > causes PM submission to fail

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#577]
If I try to send a PM with something in the text like "<PuttItOut>", the message is not sent and I'm redirected to the "Well this is embarrassing. Something went wrong and let's face it, nobody's happy about it. We'll dispatch our monstersquad to take a look at it right away!" error page.

**Comment by CoryMcDonald** [comment]
I'm pretty sure that this is related to the how ASP handles Validation. I saw something similar when modifying the Search view/controller. I have a pull request (https://github.com/voat/voat/pull/519) that fixes this on the search page, maybe we should look at creating a custom validator that all requests go into?

**Comment by Fezch** [comment]
I'd imagine this has something to do with avoiding XSS attacks. Likely used to stop people sending malicious javascript scripts to other people.

**Comment by PuttItOut** [comment]
Fixed
