### ISSUE TITLE
Can I delete my account and remake it with the same name?

### ISSUE THREAD

**Issue by Archiux** [voat/voat#579]
Can I delete my account and remake it with the same name? The reason is because I wanted to change one of the characters in the username. Is there a wait period before someone can reuse the name again?

**Comment by yesiamquitesmall** [comment]
You really should not be asking this in the issue section on github...

**Comment by seanfreiburg** [comment]
// username will stay permanently reserved

https://github.com/voat/voat/blob/cad35c1647e651c572c791353f44364288f482dc/Whoaverse/Whoaverse/Utils/User.cs

Line 117.

Please close this issue.
