### ISSUE TITLE
Feature Request - Implement static content pages

### ISSUE THREAD

**Issue by git-project-one** [voat/voat#580]
I think it would be a good idea for the future if we were able to implement something like static.voat.co where the content would be updated every 5 or 15 minutes. 

The major perk to this should it exist, is for times like these we could save some CPU time rendering the same page over and over again. This somewhat mirrors np.reddit.com however it would actually enforce no participation. 

Also we could take advantage of cloudflares' caching to offload more from voat's servers.

**Comment by voltagex** [comment]
voat.co is currently missing a huge opportunity to gain traffic and traction from the ongoing Reddit drama. If not static pages, you should be on the phone to Cloudflare right now!

**Comment by ruvyas** [comment]
Agree 100%

**Comment by bennnn** [comment]
They're already on CloudFlare, to what capacity is unknown though. They should have static.voat.co heavily cached with short TTL as the default for non-logged in users at least, it would handle all the people coming in to look without using any resources. Taking the blunt of the blow as it were.

**Comment by revolution42** [comment]
Could you potentially use something like http://www.devtrends.co.uk/blog/donut-output-caching-in-asp.net-mvc-3 content views can then just be pages that are cached longer

**Comment by fringenerd** [comment]
@Voat really should have static pages for /v/all, /v/front, and /v/[insert subverse], perhaps only refreshing every 10, 15 minutes.

The only pages that benefit from not being static are comments pages and /new.

**Comment by PuttItOut** [comment]
Closed as this is not a planned feature.
