### ISSUE TITLE
Expand all slimgur URLs

### ISSUE THREAD

**Issue by kiwwisk** [voat/voat#588]
When user posts non-image Slimgur URL e.g. `https://slimgur.com/image/XXXXX`, the image is not expanded upon clicking -> user is redirected to Slimgur page, which is quite annoying.

Should non-image Slimgur URL expand like normal image URL?

**Comment by PuttItOut** [comment]
Voat supports direct image expansion and any additional code to match particular providers burdens the UI.

**Comment by PuttItOut** [comment]
Closed as this is not a planned feature.
