### ISSUE TITLE
Question/Discussion - Project Organization

### ISSUE THREAD

**Issue by bob3695** [voat/voat#593]
Hello everyone,

I am interested in seeing if I can help you guys out a little bit so I pulled the project and the first thing I noticed is there is really no structure to keep a good separation of concerns. 
- All of the database stuff is in the web project.
  - IMHO the database stuff should be in a different class that only handles data access
- All the of actions to WAY more then a action should do.
  - All business logic could be in a service so that you can share it between your MVC actions and API actions cutting down on code duplication and maintenance overhead
- (this one is a personal preference) API controllers mixed with MVC controllers.
  - I like knowing if a controller is an MVC controller or API controller just by looking at the solution explorer
- A single web api controller instead of splitting it up into controllers that handle specific areas of the app.
  - This controller will get HUGE as you add more API endpoints. Which you will likely be adding a ton here if you ever go with a mobile app or even a SPA (Which I would recommend for the type of site this is)
- Actions that should be an API action in MVC controllers
  - Example: ~/Controllers/CommentController.cs ln 37 - It returns a JsonResult which tells me this is only called via AJAX (or another REST based call). This is the "old" way of doing a API before Web API was introduced.

Misc things:
- The unit testing leaves a lot to be desired. Switching to more of a service oriented architecture would allow for more robust testing.

I am open to hearing about if the architecture was setup this way for any particular reason? If not, would you guys be open to a PR that makes some of these changes?

**Comment by Romoku** [comment]
Well Voat started as a learning project, so that is why the structure is really ad-hoc. Adding incremental improvement to the existing project is the more straightforward way to go.

One simple refactoring is the command pattern. This way larger methods can be made into discrete chunks without breaking existing code.

Another thing that can be done is optimizing the EF queries and adding a caching layer.

**Comment by bob3695** [comment]
I am a believer in having a baseline set of tests before you dive into any changes whatsoever. So step 1 for anything for me is to get better unit testing. I have created a pull request #595 to show a way of doing some unit testing around the controllers.

**Comment by Romoku** [comment]
+1 for more tests.

**Comment by Aaron-P** [comment]
There is a fair bit of organization that can and should be done but it will have to wait until the changes as mentioned here https://github.com/voat/voat/issues/585#issuecomment-118432967.  I'm not sure what all they are changing but no pulls have been getting merged for a while.

**Comment by galbacarys** [comment]
I agree with bob3695; I think the smartest way forward is to start doing an in-place refactor. Continue patching and improving the current codebase to keep the site afloat, while also building up some better-architected, more thoughtfully laid out components alongside it. Then, we can flip the switch later and hopefully dramatically improve some of the issues plaguing the project.

**Comment by celluj34** [comment]
cross-posting my comment from #590, I believe every non-POCO and non-Controller class should implement an interface. Both for testability and dependency injection. At my work we have a unit test project and integration test project, where both grab interfaces for mocking/fakes/etc.

**Comment by Romoku** [comment]
Interfaces do lend themselves to composability. Non-framework services should provide an interface unless the situation dictates otherwise.

**Comment by PuttItOut** [comment]
Closed as code has changed significantly since issue logged.
