### ISSUE TITLE
Unable to run private instance of Voat: Unable to load the specified metadata resource.

### ISSUE THREAD

**Issue by gholol** [voat/voat#594]
Hi

I'm a begineer with C#, and I wanted to install voat on my local machine in order to understand better how it all works.

But I'm unable to set it up. I did everything as was told in the README, but when I'm opening Voat.sln, after build process and typing CTRL+F5 it redirects me to my localhost instance and I can see this text:

    Voat is under heavy load. Please try again in a few minutes.

After some debugging I've noticed it's returned in the HomeController:

            try
            {
                // show only submissions from subverses that user is subscribed to if user is logged in
                // also do a check so that user actually has subscriptions
                if (User.Identity.IsAuthenticated && Utils.User.SubscriptionCount(User.Identity.Name) > 0)
                {
                    var blockedSubverses = _db.UserBlockedSubverses.Where(x => x.Username.Equals(User.Identity.Name)).Select(x => x.SubverseName);
                    IQueryable<Message> submissions = (from m in _db.Messages.Include("Subverses").AsNoTracking()
                                                       join s in _db.Subscriptions on m.Subverse equals s.SubverseName
                                                       where m.Name != "deleted" && s.Username == User.Identity.Name
                                                       where !(from bu in _db.Bannedusers select bu.Username).Contains(m.Name)
                                                       select m).OrderByDescending(s => s.Rank);

                    var submissionsWithoutStickies = submissions.Where(s => s.Stickiedsubmission.Submission_id != s.Id);
                    var submissionsExcludingBlockedSubverses = submissionsWithoutStickies.Where(x => !blockedSubverses.Contains(x.Subverse));
                    PaginatedList<Message> paginatedSubmissions = new PaginatedList<Message>(submissionsExcludingBlockedSubverses, page ?? 0, pageSize);

                    return View(paginatedSubmissions);
                }
                else
                {
                    // get only submissions from default subverses, order by rank
                    IQueryable<Message> submissions = (from message in _db.Messages.Include("Subverses").AsNoTracking()
                                                       where message.Name != "deleted"
                                                       where !(from bu in _db.Bannedusers select bu.Username).Contains(message.Name)
                                                       join defaultsubverse in _db.Defaultsubverses on message.Subverse equals defaultsubverse.name
                                                       select message).OrderByDescending(s => s.Rank);

                    var submissionsWithoutStickies = submissions.Where(s => s.Stickiedsubmission.Submission_id != s.Id);

                    PaginatedList<Message> paginatedSubmissions = new PaginatedList<Message>(submissionsWithoutStickies, page ?? 0, pageSize);

                    return View(paginatedSubmissions);
                }
            }
            catch (Exception)
            {
                return View("~/Views/Errors/DbNotResponding.cshtml");
            }

     Unable to load the specified metadata resource.
    Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Same thing happens If I run it from Linux (via mono)  or Windows

I set up reCaptcha keys, I've successfully installed SQL Server (on another virtual machine, but I'm 100% sure it works as I can access it from VS in the voat's solution.) 

My connectionString:

      <connectionStrings>
        <add name="whoaverseUsers" connectionString="Data Source=192.168.1.114, 1041;Initial Catalog=whoaverse_users;Persist Security Info=True;User ID=sa;Password=qwe2232" providerName="System.Data.SqlClient"/>
        <add name="whoaverseEntities" connectionString="metadata=res://*/Models.WhoaverseEntityDataModel.csdl|res://*/Models.WhoaverseEntityDataModel.ssdl|res://*/Models.WhoaverseEntityDataModel.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=192.168.1.114, 1041;initial catalog=whoaverse;persist security info=True;user id=sa;password=qwe2232;MultipleActiveResultSets=True;App=EntityFramework&quot;" providerName="System.Data.EntityClient"/>
      </connectionStrings>

I've tried recreating the EDMX. I've tried  tried recreating the database, from scratch. No luck, whatsoever.

**Comment by bob3695** [comment]
This page shows if anything in that method throws an exception. The easiest way to get some more information around this error is to put a break point into the "return View("~/Views/Errors/DbNotResponding.cshtml");" line and that will break to let you see all the debug information OR after running the app look at the Output pane in VS (with Debug selected in the dropdown at the top of it) and scroll through looking for something that starts with "A first chance exception of type". This won't give you the full stack trace but will have an idea of where the error happened which will help focus your troubleshooting efforts.

**Comment by Aaron-P** [comment]
Run it in debug mode and see what exception you hit.

**Comment by gholol** [comment]
This is all I got:

    An exception of type 'System.Data.Entity.Core.MetadataException' occurred in EntityFramework.dll but was not handled in user code

     Additional information: Unable to load the specified metadata resource.

     at   System.Data.Entity.Core.Metadata.Edm.MetadataArtifactLoaderCompositeResource.LoadResources(String assemblyName, String resourceName, ICollection`1 uriRegistry, MetadataArtifactAssemblyResolver resolver)
       at System.Data.Entity.Core.Metadata.Edm.MetadataArtifactLoaderCompositeResource..ctor(String originalPath, String assemblyName, String resourceName, ICollection`1 uriRegistry, MetadataArtifactAssemblyResolver resolver)
       at System.Data.Entity.Core.Metadata.Edm.MetadataArtifactLoaderCompositeResource.CreateResourceLoader(String path, ExtensionCheck extensionCheck, String validExtension, ICollection`1 uriRegistry, MetadataArtifactAssemblyResolver resolver)
       at System.Data.Entity.Core.Metadata.Edm.MetadataArtifactLoader.Create(String path, ExtensionCheck extensionCheck, String validExtension, ICollection`1 uriRegistry, MetadataArtifactAssemblyResolver resolver)
       at System.Data.Entity.Core.Metadata.Edm.MetadataArtifactLoader.Create(String path, ExtensionCheck extensionCheck, String validExtension, ICollection`1 uriRegistry)
       at System.Data.Entity.Core.Metadata.Edm.MetadataCache.SplitPaths(String paths)
       at System.Data.Entity.Core.Common.Utils.Memoizer`2.<>c__DisplayClass2.<Evaluate>b__0()
       at System.Data.Entity.Core.Common.Utils.Memoizer`2.Result.GetValue()
       at System.Data.Entity.Core.Common.Utils.Memoizer`2.Evaluate(TArg arg)
       at System.Data.Entity.Core.Metadata.Edm.MetadataCache.GetArtifactLoader(DbConnectionOptions effectiveConnectionOptions)
       at System.Data.Entity.Core.Metadata.Edm.MetadataCache.GetMetadataWorkspace(DbConnectionOptions effectiveConnectionOptions)
       at System.Data.Entity.Core.EntityClient.EntityConnection.GetMetadataWorkspace()
       at System.Data.Entity.Core.Objects.ObjectContext.RetrieveMetadataWorkspaceFromConnection()
       at System.Data.Entity.Core.Objects.ObjectContext..ctor(EntityConnection connection, Boolean isConnectionConstructor, ObjectQueryExecutionPlanFactory objectQueryExecutionPlanFactory, Translator translator, ColumnMapFactory columnMapFactory)
       at System.Data.Entity.Core.Objects.ObjectContext..ctor(EntityConnection connection)
        at System.Data.Entity.Internal.InternalConnection.CreateObjectContextFromConnectionModel()
       at System.Data.Entity.Internal.LazyInternalConnection.CreateObjectContextFromConnectionModel()
       at System.Data.Entity.Internal.LazyInternalContext.InitializeContext()
       at System.Data.Entity.Internal.InternalContext.Initialize()
       at System.Data.Entity.Internal.InternalContext.GetEntitySetAndBaseTypeForType(Type entityType)
       at System.Data.Entity.Internal.Linq.InternalSet`1.Initialize()
       at System.Data.Entity.Internal.Linq.InternalSet`1.get_InternalContext()
       at System.Data.Entity.Internal.Linq.InternalSet`1.Find(Object[] keyValues)
       at System.Data.Entity.DbSet`1.Find(Object[] keyValues)
       at Voat.Utils.User.UserStylePreference(String userName) in c:\Users\voat\Downloads\voat-master\voat-master\Whoaverse\Whoaverse\Utils\User.cs:line 396
       at Voat.MvcApplication.Session_Start(Object sender, EventArgs e) in c:\Users\voat\Downloads\voat-master\voat-master\Whoaverse\Whoaverse\Global.asax.cs:line 74
        at System.Web.SessionState.SessionStateModule.RaiseOnStart(EventArgs e)
       at System.Web.SessionState.SessionStateModule.OnStart(EventArgs e)
       at System.Web.SessionState.SessionStateModule.CompleteAcquireState()
       at System.Web.SessionState.SessionStateModule.BeginAcquireState(Object source, EventArgs e, AsyncCallback cb, Object extraData)
       at System.Web.HttpApplication.AsyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()

**Comment by Romoku** [comment]
Some issues that I ran into:

Need to copy web.config from base of repo to Whoaverse project.

The whoaverse.sql and whoaverse_users.sql files generate databases call `voat` and `voatUsers`. However, the connection strings look for `whoaverse` and `whoaverse_users` databases. I had to change the connection string to get it to work.

Additionally you need to add two users: `whoaverse` and and `whoaverse_users` and grant them access to their respective databases.

After that it worked for me.

**Comment by gholol** [comment]
I did all of this, and I'm still getting the same freaking error.

**Comment by gholol** [comment]
Okay, I think I'm getting close. It now shows this:

    An error occurred while executing the command definition. See the inner exception for details.     EntityFramework System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near 'OFFSET'. Invalid usage of the option NEXT in the FETCH statement. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData() at System.Data.SqlClient.SqlDataReader.get_MetaData() at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString) at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method) at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior) at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior) at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.b__c(DbCommand t, DbCommandInterceptionContext`1 c) at System.Data.Entity.Infrastructure.Interception.InternalDispatcher`1.Dispatch[TTarget,TInterceptionContext,TResult](TTarget target, Func`3 operation, TInterceptionContext interceptionContext, Action`3 executing, Action`3 executed) at System.Data.Entity.Infrastructure.Interception.DbCommandDispatcher.Reader(DbCommand command, DbCommandInterceptionContext interceptionContext) at System.Data.Entity.Internal.InterceptableDbCommand.ExecuteDbDataReader(CommandBehavior behavior) at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior) at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior) ClientConnectionId:8b2b1367-91e6-474a-ae7e-28218f14833b

**Comment by gholol** [comment]
After upgrading to SQL Server 2012 it works like a charm now.

**Comment by msilvya** [comment]
Sorry for reopening this issue but I've just given up (hobbyist developer here).

@gholol, could you please elaborate on what you did?

When I publish or debug the project, there are 0 build errors and no warnings or messages. The pages load fine but I'm redirected to the dreaded "Voat is under heavy load. Please try again in a few minutes.". Clicking any page/link redirect me to the same page. The developer I hired told me that I'm getting the connection strings wrong but won't tell me 'how?"

Anyway, here's my test [azure test page](https://lawrkhawmm.azurewebsites.net/) and following are the connection strings in the **web.config** file - yes, the **web.config** has been copied from the base of repo to the project folder. I'd be grateful if you (or someone here) could give some pointers where I'm getting it wrong - the developer I hired has confirmed that he has cleaned up the code but just that I'm getting the connection strings wrong. 

**voatUser** = the voatUsers database with **UserID** = voatUSER
**voat** = main voat database with **UserID** = voat

```
<connectionStrings>

<add name="voatUsers" connectionString="data source=tcp:voat.database.windows.net;initial catalog=voatUsers;User ID=voatUser;Password=PASSWORD;Trusted_Connection=False;persist security info=True;Encrypt=True;TrustServerCertificate=True;Max Pool Size=2048;" providerName="System.Data.SqlClient"/>

<add name="voatEntities" connectionString="metadata=res://*/Models.VoatEntityDataModel.csdl|res://*/Models.VoatEntityDataModel.ssdl|res://*/Models.VoatEntityDataModel.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=tcp:voat.database.windows.net;initial catalog=voat;persist security info=True;user id=voat;password=PASSWORD;MultipleActiveResultSets=True;App=EntityFramework;Max Pool Size=2048;Pooling=true;Timeout=30;&quot;" providerName="System.Data.EntityClient"/>

<add name="voatEntitiesReadOnly" connectionString="metadata=res://*/Models.VoatEntityDataModel.csdl|res://*/Models.VoatEntityDataModel.ssdl|res://*/Models.VoatEntityDataModel.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=tcp:voat.database.windows.net;initial catalog=voat;persist security info=True;user id=voatmain;password=PASSWORD;MultipleActiveResultSets=True;App=EntityFramework;Max Pool Size=2048;Pooling=true;Timeout=30;&quot;" providerName="System.Data.EntityClient"/>

</connectionStrings>
```
