### ISSUE TITLE
Look and Feel

### ISSUE THREAD

**Issue by kingflurkel** [voat/voat#598]
I know you ex-redditors don't care for a second about how stuff looks :) but it could be nice for newbies to get a slightly more polished look for the site. Anyone interested in that? 
I would love to help on this, but honestly can't find a friggin css file in the code.

**Comment by TNTGav** [comment]
https://github.com/voat/voat/tree/master/Whoaverse/Whoaverse/Content whoaverse.css

**Comment by mgiuffrida** [comment]
The CSS file is generated from the files TNTGav pointed to into one bundle named Light or Dark, so you won't find it if you're looking for a ".css" extension. Just check for the <link rel="stylesheet">.

**Comment by PuttItOut** [comment]
Closed as this is not a planned feature.
