### ISSUE TITLE
A question about Voat and Linux

### ISSUE THREAD

**Issue by 436wtw3ry546** [voat/voat#600]
I'm using linux all the time, and I just wonder, Is it possible to run Voat on Linux OS?

I know there's no way to run SQL Server on it, but it could be set up on another machine.

**Comment by rocketpastsix** [comment]
If you can remote into an SQL Server, you could potentially get the .NET core up on Linux, but at least I checked I dont think it was 100% just yet.

**Comment by SemiNormal** [comment]
You would need Mono, not .NET core since Voat is using EF6 and MVC5.

**Comment by 436wtw3ry546** [comment]
I just installed mono and dnvm, after poking around it, I can safely assume Mono is not compatible with EF6 in some way. Unless I'm missing something.

This is all I'm getting after building voat from monodevelop (compilation succeeds)

At first it looked like I forgot to run SQL Server
![img 1](http://i.imgur.com/vo4AbmY.png)


So I launched it. Does it work now? Nope.

![img 1](http://i.imgur.com/cGnJNLR.png)

**Comment by alexbooker** [comment]
Voat uses ASP.NET MVC 5 which does not _inherently_ run on Linux. You _might_ be able to get it working on Linux using Mono if you do enough tinkering and run SQL Server using Wine - sounds like a pain in the ass, though.

You seem to be under the impression that Voat is running on a version of ASP.NET that is cross-platform when it is not.

The next iteration of ASP.NET is a clean-room implementation of ASP.NET that _is_ cross platform. ASP.NET 5 is still in a somewhat early beta and is _not_ intended for use in production at this time. Voat does not use it.

**Comment by NeilHanlon** [comment]
*cough* if the codebase did run on Linux (sans Mono/.NET)... scaling wouldn't be as much of an issue...

**Comment by thestamp** [comment]
That's an unfair argument. Saying that all Linux software is scalable
simply because it's on Linux is completely false.

**Comment by 436wtw3ry546** [comment]
It would be great if we could run it on LInux but well... Looks like Mono isn't compatible

**Comment by danieldafoe** [comment]
@436wtw3ry546 I received an answer about a similar question I had in relation to running voat on OS X, and the short of it is that voat.co is built using .NET 4.5, which Mono currently doesn't have support for. Take a look here:

http://www.mono-project.com/docs/about-mono/compatibility/

**Comment by k-rloss** [comment]
@436wtw3ry546
Can you please post the full stack trace as text? I'm curious to see where exactly it's failing

**Comment by milezteg** [comment]
<rant>I would gladly send bitcoins to anyone clever enough to make a robust, scalable, manageable etc.  voat/reddit clone for *nix.  I'm amazed it hasn't been done properly yet and it's 2015.  The reddit source code is 'a mess' while voat is written in .NET for some ungodly reason.</rant>

**Comment by rocketpastsix** [comment]
Im down to start on it with others, but cash is always better.

**Comment by TorrhenStark** [comment]
@milezteg Why not offer the bitcoins to help improve Voat? Or maybe even Mono to get .NET 4.5 supported?

**Comment by 436wtw3ry546** [comment]
@milezteg Yeah, Reddit source code is a big mess to understand. But  C# is really neat, and I love writing programs in it. MS SQL could be changed to MySQL or some other RDBMS at any time,  It's just a problem with the current state of Mono which still have many issuses and/or inconsistencies.

@k-rloss

Here's full stack trace. I can't get anything else out of it.
![stack trace](https://camo.githubusercontent.com/44cbede7035c6219c5fee0b021c6e4f603a5f2e0/687474703a2f2f692e696d6775722e636f6d2f63476e4a4e4c522e706e67)

**Comment by PuttItOut** [comment]
Closed as we are planning a future conversion to .NET Core.
