### ISSUE TITLE
Prepend body.$theme to every CSS selector

### ISSUE THREAD

**Issue by mgiuffrida** [voat/voat#601]
Mods are encouraged to use body.light and body.dark in their subverse stylesheets to prevent breaking light or dark mode.

However, this means their selectors are automatically more specific than Voat selectors that don't start with body.light or body.dark.

For example, a rule like this:

```
body.light a {
  color: red;
}
```

Will override a rule like this:

```
a.btn-tour {
  color: white;
}
```

Causing unintended breakages. Example: open https://voat.co/v/Typogra/comments/176824 in a new incognito instance and notice the "Take a tour" button in the announcement at the top

It's not feasible for mods to handle every selector the default stylesheet uses -- there are hundreds. But adding body.$theme to the default stylesheet's selectors will help.

@Nurdoidz 

-roboticon

**Comment by PuttItOut** [comment]
Fixed
