### ISSUE TITLE
Implement a comment sorting function focused on comment quality

### ISSUE THREAD

**Issue by engstrom** [voat/voat#602]
There are currently two ways to sort comments: top & new. Top sorts by commentScore (commentScore = likes - dislikes) or by date. New sorts by date. There's no doubt that 'new' is a useful sort function and total commentScore may very well be useful in some cases, but I think there's another approach that allows comments of higher quality to rise towards the top.

I propose we add a third comment sorting option that uses the "lower bound of Wilson score confidence interval for a Bernoulli parameter" as outlined by Evan Miller on his blog: http://www.evanmiller.org/how-not-to-sort-by-average-rating.html

This allows comments to be sorted by their proportion of likes to dislikes in a way that doesn't result in the normal trappings of 5-star review rankings -- where an item with one 5-star review is displayed higher than an item with 500 4-star reviews.

**Comment by Romoku** [comment]
Is this the same as the reddit algorithm?

**Comment by engstrom** [comment]
@Romoku 

From the linked article:
> I initially devised this method for a Chuck Norris-style fact generator to honor of one of my professors, but it has since caught on at places like Reddit, Yelp, and Digg.

**Comment by airbreather** [comment]
Another link discussing this, written by Randall Munroe (the guy who does xkcd): http://www.redditblog.com/2009/10/reddits-new-comment-sorting-system.html

**Comment by airbreather** [comment]
For what it's worth, here's the relevant code, as of the latest commit at the time of commenting: https://github.com/voat/voat/blob/2cf2a691bcdcee6ae30f827fcfa94f4bb2d068c2/Voat/Voat.UI/Controllers/CommentController.cs#L255-L270

**Comment by Romoku** [comment]
OK. I will look into this. Gotta merge existing PRs before I do any cove. Thanks for these links!

**Comment by tchoulihan** [comment]
How does voat do its comment and link sorting, IE, what are the equations in use? It'd be really helpful to throw those on the about or FAQ page.

I've only seen two types of sorting for voat: top and new. I sure hope top actually uses time-based z-scores and isn't just likes - dislikes descending.

Also, here's pretty much the best description of how to come up with a 'hot' or 'trending' algorithm:

http://stackoverflow.com/a/826509/1655478

**Comment by engstrom** [comment]
@tchoulihan I don't mean to be rude, but if you made it this far why don't you just look at the code?

**Comment by tchoulihan** [comment]
Because I'm deferring to experts that know the codebase.

Do you know where the sorting algorithms are?

**Comment by engstrom** [comment]
@tchoulihan They were linked above in [this comment](https://github.com/voat/voat/issues/602#issuecomment-120725812).

**Comment by engstrom** [comment]
Evan Miller posted a dissection of the 'hot' formula used by reddit yesterday. It may be of interested to those following this issue.

http://www.evanmiller.org/deriving-the-reddit-formula.html

**Comment by PuttItOut** [comment]
Implemented with recent sorting logic.
