### ISSUE TITLE
"It sure feels lonely in here" message appears when only posts are stickies

### ISSUE THREAD

**Issue by mgiuffrida** [voat/voat#604]
1. Post in an empty subverse. "It feels lonely in here" fake-post goes away.
2. Sticky the post you made. "It feels lonely in here" fake-post comes back.

"It feels lonely in here" fake-post should not be shown when the sub has posts. I don't see why a sticky should change this as you're still not going to be "the first person to share a link or discuss".

**Comment by PuttItOut** [comment]
This is a because stickies are filtered. Closed as this is not a planned feature.
