### ISSUE TITLE
Can't cancel "share a link" overlay

### ISSUE THREAD

**Issue by imanrp** [voat/voat#607]
I often accidentally drag things to browser and voat thinks I want to share a link. When the "share a link" overlay is showing, I can't cancel it, even if I drop the thing I dragged outside the browser window, the overlay stays there and cannot be closed. Can anyone confirm this bug? Then to continue using Voat, I have to refresh the page. 

I think there should better be a **close button** on the corner of the overlay to close the overlay and naturally can also be triggered by **Escape** key.

Of course to me it's better if I have an option to disable the whole drag-and-drop feature, because I don't like to use it, but excluding such option is perhaps intentional for simplicity, so it's understandable as long as it's not buggy.

**Comment by k1nger** [comment]
If you hover away/off the browser it should fix this. Also, unless it's a supported type of file if you just drop the file in the window it won't do anything.

**Comment by imanrp** [comment]
Umm no it's not. If I hover away or drop it outside the browser, the overlay stays there and cannot be closed. If I drop it there, it went to upload form which don't make sense because I'm dragging file or launcher from my desktop, **not a link**. Anyway, for additional information, I'm on Ubuntu and using Firefox 38.

**Comment by nicolapcweek94** [comment]
I can confirm this happening with the latest Firefox Developer Edition (41.0a2) on Windows 7 x64. However, it didn't happen for me when I tried to reproduce it with Waterfox x64 (38.1) on 8.1 x64.
Dragging anything to the browser window, or even starting the drag event *inside* the window (ie: selecting text from voat and dragging it to another window), gets the "Share a link" modal to popup and it never disappears, forcing me to reload.

**Comment by thestamp** [comment]
Trying to repo on firefox, it looks like its redirecting to a diff page now. Can you confirm?

**Comment by PuttItOut** [comment]
Fixed
