### ISSUE TITLE
Re-adding a max-width to comments and link markdown

### ISSUE THREAD

**Issue by Nurdoidz** [voat/voat#608]
Posts about widening the container are starting to pick up speed, causing a number of subverse owners enabling it on their subverses. Example:

![](https://cloud.githubusercontent.com/assets/8064810/8552548/0c8baeb8-249b-11e5-9360-93624c098c2a.png)

With the container, `max-width` values on comments and posts were unnecessary since the container itself acted as a line limiter, so they were removed in favor of the inline expando functionality.

However, I propose re-adding the values so that readability isn't deteriorated when sub owners widen the container on their subverses. The code I have prepared will be unnoticeable when the container is unmodified; it will only activate when it is widened.

Normal:

![](https://cloud.githubusercontent.com/assets/8064810/8552933/4278a966-249d-11e5-9150-fb45488392b6.png)

Container intact, markdown max-width active:

![](https://cloud.githubusercontent.com/assets/8064810/8552964/61e2aaea-249d-11e5-9909-065c29a84dfa.png)

Container widened, markdown max-width active:

![](https://cloud.githubusercontent.com/assets/8064810/8552986/8151f584-249d-11e5-99bc-78fa1b869a2f.png)

Thoughts?

**Comment by DanielFlamino** [comment]
I'm in favour. :+1:

**Comment by quantumwannabe** [comment]
Doing this will stop image expandos from filling up the whole width. I've heard some complaints that voat's expandos don't cover the whole page like RES, and using widescreen CSS allows for the best of both.

**Comment by Nurdoidz** [comment]
@quantumwannabe 

> Doing this will stop image expandos from filling up the whole width.

This will have no effect on image expandos. Expandos in comments and posts are inside the `md` div, which is already restricted by the container layout. Since this suggestion is adding a max-width restriction on the comments greater than their possible width value in an unmodified container, there is literally no effect in that regard.

Expandos activated by the posts are not inside `md` divs, so they will be unaffected.

> I've heard some complaints that voat's expandos don't cover the whole page like RES, and using widescreen CSS allows for the best of both.

This is not relevant to this issue.

**Comment by quantumwannabe** [comment]
Here's some screenshots to illustrate what I mean:

Current:
![Current](https://cloud.githubusercontent.com/assets/5686957/8559932/53b5f2e8-24d8-11e5-9a20-86b542cec063.png)
With no max-width on container and max-width on `md`
![With no max-width on container and max-width on md](https://cloud.githubusercontent.com/assets/5686957/8559931/53b2b04c-24d8-11e5-9198-1d68409f1650.png)
With no max-width on container and no max-width on `md`
![With no max-width on container and no max-width on md](https://cloud.githubusercontent.com/assets/5686957/8559930/53b1e2b6-24d8-11e5-8a12-18d262acfb9b.png)

With the max-width on the `md`, the image can't expand all the way and there is lots of wasted space.

I agree that your styles make it much nicer to read text, I'm just concerned that they, as a side effect, take away image space.

Floating the expando almost fixes this:

![7-7-2015 6 56 55 pm](https://cloud.githubusercontent.com/assets/5686957/8560094/0cf11e8a-24da-11e5-9297-257763065cc4.png)
But there are issues:
![7-7-2015 6 57 12 pm](https://cloud.githubusercontent.com/assets/5686957/8560093/0ce1b080-24da-11e5-99fa-365aad16e650.png)

**Comment by Nurdoidz** [comment]
Here is my perspective:

1. Sub owners widening the container is an unorthodox change.
2. The purpose of this suggestion is to retain readability for subs that widen the container.
3. On an unmodified container, an image will expand to a maximum of *x* px. When a sub owner widens the container, an unorthodox change, an image will **still** expand to a maximum of *x* px.
4. On an unmodified container, text will wrap at *x* px. When a sub owner widens the container, text will **still** wrap at *x* px.
5. It is the responsibility of the sub owner to support a wider expando, since they make an unofficially-supported change to Voat's layout.
6. Finally, comment and post markdown have always had a max-width value **prior** to image expandos. When they were implemented, I held my tongue when that value was removed in favor of the expandos, since the container acted as a fall-back max-width to keep text wrapping correctly.

    Since a growing portion of the site is now containerless, that fall-back has been lost and the max-width should be **re-added** since it is needed again. I hold the opinion that readability should take precedence over extra features.

Reddit has a max-width on their comments and posts and, if I am assuming correctly, RES's expandos ignore that rule somehow. Therefore, allowing the expando to move more freely throughout the container is a separate issue and is not relevant to this suggestion.

**Comment by quantumwannabe** [comment]
RES gets around it by positioning the expandos absolutely and using JS push the rest of the content down. This allows for unlimited width, but kind of looks awkward when going over the sidebar and the comment backgrounds. (On a related note, I could add RES style expandos to voat, but when they were first added, the consenous was that the scrollbar container style was better)

Yah, I agree that subverse mods should be responsible for their style changes. Your change is good and should be merged.

**Comment by jksg** [comment]
+1. The full-width container trend is terrible for readability. The common user complaint about “wasted space” at the sides is unfounded — don’t use a full-screen, landscape browser to read text in a portrait page.

**Comment by DanielFlamino** [comment]
@Nurdoidz I guess this issue can now be closed?
