### ISSUE TITLE
I am Human

### ISSUE THREAD

**Issue by zunox** [voat/voat#611]
Could it be possible to become verified? Maybe mobile verification? Not sure just figured id put it out there.

**Comment by Romoku** [comment]
Is reCAPTCHA not enough?

**Comment by squ1dk1d** [comment]
I think he means as a replacement to captcha. For example, once you are verified, you don't need to enter a captcha.

**Comment by Romoku** [comment]
I guess it is my inexperience showing. I thought the captcha only appears when a user is registering.

**Comment by fringenerd** [comment]
Captcha only appears in very limited circumstances--when you register, and when you want to create a new subverse. Mobile verification is unnecessary.

**Comment by nicolapcweek94** [comment]
I also had the captcha appear when creating a new text post on v/introductions though, maybe it also appears when creating the first post?

**Comment by fringenerd** [comment]
I ... don't recall, and I can't check now. Even if that's the case, it's not unduly cumbersome. Most Captcha checks simply involve checking a box. Is that really too much of a burden?

Considering the state of the site, keeping it in place is a better idea. It wards off spammers, and anything that slows down participation of even legitimate users at this point is a boon.

Mobile verification would require grafting a whole new system onto the existing one, and there are more important issues to address right now. This is a very low priority request, and really should have been submitted at a later date.

Let's get the site working first, with all of the features it needs to be functional, before asking for stuff like this.

**Comment by zunox** [comment]
I am afraid, you guys are mistaken. Every time you make a submission, there is verification. Crate a sub, i understand we don't want spam. But i don't spam.  Maybe after so much comment karma or link karma this should go away?

**Comment by jksg** [comment]
I haven’t faced a captcha for submissions after my first couple of days on Voat. It should go away after 100 CCP.

**Comment by PuttItOut** [comment]
CCP restrictions apply to captcha. Closing.
