### ISSUE TITLE
"My Subverse" Dropdown

### ISSUE THREAD

**Issue by ghost** [voat/voat#614]
Whenever I mouse over the "My Subverse" drop down and move my pointer to click on a subverse, the drop down disappears. I looked around to see if anything was posted about it, but couldn't find anything.

**Comment by HorzaGobuchul** [comment]
I couldn't replicate this in Firefox or Chrome.

Is there anything peculiar

**Comment by jksg** [comment]
Which browser/OS and is this happening on a specific sub or on the entire site?

**Comment by fringenerd** [comment]
@ghost, if your mouse cursor moves off the list, the list will vanish. Make sure your cursor remains on the list while you navigate to your choice.
