### ISSUE TITLE
Suggestion: Add rewind feature to front page

### ISSUE THREAD

**Issue by phly95** [voat/voat#615]
Sometimes we want to find something that was on the front page in the past, but it disappeared. It's not deleted, just nowhere to be found on the front page. I would like to be able to go back to a specific date and time on voat so this doesn't happen in the future.

**Comment by TNTGav** [comment]
It's not impossible, but I don't think is feasible for a number of reasons:

1) Upvoats are calculated dynamically and only the current rating is stored at present so to do this you would either need to create a snapshot cache of each page or expand the DB to store the state of the front page at any given time

2) This is what a working search is for

3) People are unlikely to remember what specific time something they read was anyway.

**Comment by fringenerd** [comment]
4) This is what archives like Wayback Machine and archive.today are for.

A cumbersome feature with only very fringe use cases, which needs are better served by other functionality, anyway. Not worth it.

**Comment by PuttItOut** [comment]
Closed as this is not a planned feature, but a very cool idea.
