### ISSUE TITLE
You're doing that too fast, wait 30 seconds and try again

### ISSUE THREAD

**Issue by philmcclure** [voat/voat#617]
I typed up a rather long-winded response to a Linux beginner, and when I went to hit the submit button, I got the "You're doing that too fast [...]" or whatever it says. I ended up splitting my response over a couple of comments and then went back to the thread.

Apparently I hit submit 8 times and each time I got the error (You're doing that too fast). I say 8 times because there were 8 full comments before the two comments that went through via the web interface.

I deleted the two, and seven of the previous 8 replies.

I'm assuming this is a bug and somebody would want to look into it.

![Screenshot](http://i.imgur.com/7ZGLNDi.png)

**Comment by thestamp** [comment]
The flag to determine when your last post was is done via the context cache. The expiry of the cache is set to n number of seconds in the future, at which time the flag is removed.

Try logging off and on again, clearing your cache. If that doesn't do it, your account SHOULD be in good standing tomorrow.

Admins: Did the clock change? Perhaps a diff method on flagging comment timings are in order? (when you're done putting out the fires of course)

**Comment by philmcclure** [comment]
I'm not explaining it right.

The web interface said that I was doing it too fast *but it was posting anyways*.

When I shortened my comment, it posted immediately.  It didn't make me wait 30 seconds.

Is there a hidden character count that prevents posting?  Or triggers the error?

**Comment by PuttItOut** [comment]
Fixed
