### ISSUE TITLE
You are doing that too fast... even after a hour.

### ISSUE THREAD

**Issue by leetdood** [voat/voat#618]
I tried to leave a comment in an AskVoat thread: https://voat.co/v/AskVoat/comments/220458/?sort=new

It kept telling me "You are doing that too fast. Please wait 30 seconds before trying again." even after I waited long periods of time, up to about a hour. I can post in other subverses and threads but not that specific one. Here's a picture.

![image](https://cloud.githubusercontent.com/assets/13247372/8586646/08e15766-25bf-11e5-8cc6-0823faa4d59a.png)

**Comment by thestamp** [comment]
Already reported, #617'

**Comment by leetdood** [comment]
The issue seemed a bit different because his was going through after he split the comments up, but I'll try the suggestion you posted there. Thank you.

**Comment by leetdood** [comment]
Logging off and on didn't work.

**Comment by thestamp** [comment]
Blegh. Not sure how to get you up and going right away then (not an admin).
Sorry!

**Comment by voat** [comment]
Are you still having this issue? What browser are you using and is it a clean browser install with no plugins/addons? Are you getting this issue in every sub or just in /v/askvoat?

**Comment by Acharvak** [comment]
It also happens to me often enough to be extremely annoying. I've seen it happen in /v/askvoat, /v/news and /v/linux.

Logging off and on doesn't work. I found the only workaround is to either not post your comment at all (because you can still post comments in other threads, even in the same subverse) or to significantly change the text.

**Comment by mgiuffrida** [comment]
I can reproduce this. With certain comments I get this message and the comment does not get posted. Removing quotation marks fixes the issue. [This comment](https://voat.co/v/programming/comments/371436/1534547) could not be posted until I removed quotation marks from the last blockquote.

[The source of the problematic comment is here](http://pastebin.com/ii4fyqda), and the [modified source that allowed be to submit the comment is here](http://pastebin.com/jC7k12kX).

**Comment by scottbyrns** [comment]
Some user isolated it. 

https://voat.co/v/voatdev/comments/418807

**Comment by PuttItOut** [comment]
Fixed
