### ISSUE TITLE
Hot ranking and front page is susceptible to vote manipulation.

### ISSUE THREAD

**Issue by squ1dk1d** [voat/voat#619]
The algorithm used to sort submissions on hot can be easily manipulated in order to get a very popular submission. Say a person manipulating votes posted a post, and contacted a vote manipulation ring of just 30 people. A 1 hour old post with 30 points will have a higher visibility ranking than a 12 hour post with 750 points! This will greatly improve the visibility of the post, and encourage non-manipulative users to vote on the post, causing it to get a high point score, and longer visibility. [This](https://www.desmos.com/calculator/yfmeuamwm7) shows the disparity between a valid and manipulated submission, and [this](https://www.desmos.com/calculator/2dsrnjs1az) shows the algorithm used to determine submission rank. The function used to calculate rank can be found [here](https://github.com/voat/voat/blob/cad35c1647e651c572c791353f44364288f482dc/Whoaverse/Whoaverse/Utils/Ranking.cs#L22). A way to prevent this could be to use logarithms instead of roots in order to determine the ranking, giving far less weight to votes after each power of 10, or some other reference number (reddit uses 10). This would mean that the first 10 points increase the rank just as much as the next 100 upvotes would. Additionally, more emphasis should be put on the first 24-48 hours in the time weight, as opposed to the first few hours.

**Comment by PuttItOut** [comment]
Closed as this is not a planned feature.
