### ISSUE TITLE
Comments you make are listed twice if you submit and then scroll down without refreshing

### ISSUE THREAD

**Issue by rankinbc** [voat/voat#621]
When you make a comment on a post that has enough comments to warrant a "load more" button, and then scroll through the comments without refreshing, your comment will appear twice on the page. One comment will be at the top and one towards the bottom (not always the last though)

From here you can edit and vote on the comments separate of one another and if you edit then refresh, both will be listed as if you made two comments.

Also it only happens when you haven't already scrolled down and loaded additional comments already before making your comment.

**Comment by rankinbc** [comment]
Also t

**Comment by pharno** [comment]
related: I was in a thread which also had a load more button. Downvoated a comment, and scrolled down. the downvoated comment appeared again.

**Comment by cvtele** [comment]
I've seen the double comment issue too July 9 and 10. Was using IE 11.

**Comment by PuttItOut** [comment]
Has to do with paging. Closing for now.
