### ISSUE TITLE
I can't Upvoat any more for some reason, even though I have at least 84 CCP.

### ISSUE THREAD

**Issue by leetdood** [voat/voat#622]
I upvoat someone, then refresh the page, and it doesn't stick. I upvoat and wait, and it still doesn't stick. I upvoat topics, different users, and they all aren't sticking right now. I don't know if this is some sort of intermittent issue, but upvoating just doesn't work for me right now. There's no message or pop-up or anything. It just doesn't actually stay upvoated. I tried logging off and on, and using a different browser.

Link to my userpage: https://voat.co/user/leetdood

**Comment by moeVoat** [comment]
Your are given (CCP / 2) upvoats per day.

**Comment by leetdood** [comment]
I've gained 42 CCP since the writing of this post, and I still can't voat. Maybe there should be something that explains this in more detail in the future?

**Comment by voat** [comment]
Unable to reproduce. Please open a new issue if you are still having this problem.
