### ISSUE TITLE
Front Page is full of links from the last hour

### ISSUE THREAD

**Issue by yotamN2** [voat/voat#625]
Before posts could be there for days, now it's the opposite, I see post from 1 minute ago with 2 upvotes on the front page, second place. The first place is also a post from 2 minutes ago with 2 upvotes.

**Comment by squ1dk1d** [comment]
This is the same problem as #619 and #613 . It has to do with the fact that the hot ranking algorithm gives VERY heavy emphasis to the first hour in which something is posted, ranking it above submissions only a few hours old with hundreds or even over a thousand points.
