### ISSUE TITLE
can't include Cyrillic characters in submission titles

### ISSUE THREAD

**Issue by Mumberthrax** [voat/voat#633]
I first noticed this here: https://voat.co/v/Mumberthrax/comments/237805/751097

A search for Cyrillic turned up this post noting the same issue: https://voat.co/v/help/comments/232111

**Comment by DanielFlamino** [comment]
Related to #411

**Comment by Mumberthrax** [comment]
oh darn. Thanks @DanielFlamino.

**Comment by PuttItOut** [comment]
Closed as this is not a planned feature.
