### ISSUE TITLE
Sub deleted

### ISSUE THREAD

**Issue by zunox** [voat/voat#635]
I ran /v/NBAstreams and had a template on it with 12 followers... Then it gets deleted! WTF is that? Why did it get deleted? I got here early to ensure i got the subs i wanted. I don't like working hard for it to be thrown away in a few seconds.. I ensure you if this was /v/aww or /v/funny and it got deleted there would be a riot.

**Comment by Romoku** [comment]
This repo is for discussing code related issues. Please post general questions [on the website](https://voat.co/v/voat).

**Comment by quantumwannabe** [comment]
Subverses get automatically deleted after 12 hours if they have no posts.
