### ISSUE TITLE
There is no User Flairs system

### ISSUE THREAD

**Issue by stormyjet** [voat/voat#637]
Hey there Voat devs. 

I run a subverse which would benefit greatly from having the ability for user flairs. Right now we have to set them in a specialized CSS layout. If there could be a system to allow users to set their flair from a predetermined list, or their own custom ones, that would be great for my subverse, and I feel that other subverses will benefit as well. 

Thanks, Stormy

**Comment by V1rusKing** [comment]
From what I have been reading about, there's no current plans yet to implement that feature, even that I think it would be very useful.

I might be wrong though, and the plans can always change.

**Comment by tchoulihan** [comment]
+1

**Comment by coldacid** [comment]
+1

**Comment by moeVoat** [comment]
-2

**Comment by DanielFlamino** [comment]
:zero:

**Comment by PuttItOut** [comment]
Closed as this is not a planned feature.
