### ISSUE TITLE
[Question] Translations?

### ISSUE THREAD

**Issue by utybo** [voat/voat#638]
Are there any plans for translating the website in other languages? 

If there are, I can easily translate the website in French since French is my mother tongue.

**Comment by Xayaan** [comment]
I second this, I think there should be plans for translating the website into multiple languages. I can translate the website into the languages i am fluent in as well.

**Comment by guest20** [comment]
There's a lot of text strewn about in the templates, pulling that out could take some work.

**Comment by voat** [comment]
This is currently at the bottom of our to-do list and adding globalization would slow us down. We did think about it, but realistically I don't see any work on this front happening any time soon. /Atko

**Comment by Estruenos** [comment]
voat, I believe its a mistake. Better implement languages now than later, the more you wait the more complex it will become to do the needed changes. Use the .po & .mo language file system, it works great.

**Comment by guest20** [comment]
I'll just leave this here...

http://search.cpan.org/dist/Locale-Maketext/lib/Locale/Maketext/TPJ13.pod
