### ISSUE TITLE
Can't accept mod invitation

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#640]
I don't know exactly what I can add to this. Just that I have a PM with a mod invite, but when I click to accept it, I just get redirected to the frontpage and I don't show up as moderator on the subverse moderator list nor on my profile.

![image](https://cloud.githubusercontent.com/assets/6509486/8635567/7775a962-2820-11e5-8f28-773d2b401117.png)

![image](https://cloud.githubusercontent.com/assets/6509486/8635568/8864b236-2820-11e5-8a1d-1f731f04fccb.png)

![image](https://cloud.githubusercontent.com/assets/6509486/8635570/97f12810-2820-11e5-9e93-b0e2831b82ea.png)

**Comment by voat** [comment]
Congrats, you found a bug related to username casing.

**Comment by DanielFlamino** [comment]
And that is why using a username made from two names is a good idea. :P

I am now able to accept the second invite.

**Comment by fringenerd** [comment]
I've had a problem inviting people to be mods on subverses I moderate. They accept the invitation, but nothing happens. From what I can tell, this appears to be a problem on other subverses, like /v/news, too.

**Comment by DanielFlamino** [comment]
You're right. I just got a PM from someone with the same issue. I'll reopen this one.

**Comment by Owner5** [comment]
Same issue for me, attempting to accept mod request but I'm just redirected to the homepage.

Oddly, it worked for one sub (/v/Creepy) but not another (/v/MaleFashionAdvice)

Username is /u/Owner
