### ISSUE TITLE
Lack of user notification regarding max Title and Side Bar character values

### ISSUE THREAD

**Issue by jameson-mcghee** [voat/voat#641]
When creating a new subverse, the Title and Side Bar fields do not have a notification message regarding max number of characters for each field.

If the user adds to many characters to the Title and Side Bar fields, a message is generated which simply states "Something bad happened, please report this to /v/voatdev. Thank you."

**Comment by jameson-mcghee** [comment]
When creating a new subverse, the Title and Side Bar fields do not have a notification message regarding max number of characters for each field.

If the user adds to many characters to the Title and Side Bar fields, a message is generated which simply states "Something bad happened, please report this to /v/voatdev.  Thank you."

**Comment by PuttItOut** [comment]
Closed as this is not a planned feature.
