### ISSUE TITLE
Missing changes to voat.sql and voat_users.sql

### ISSUE THREAD

**Issue by Romoku** [voat/voat#642]
@PuttItOut Added a bunch of changes to the EF context, but the sql scripts were renamed and not regenerated (see 270a724).

**Comment by Romoku** [comment]
This got the home page loading for me. I do not know if this is the only thing that changed.

    ALTER TABLE [dbo].[Messages]
    ADD [IsArchived] [bit] NOT NULL CONSTRAINT [DF_Messages_IsArchived]  DEFAULT ((0))

**Comment by voat** [comment]
We'll push updated scripts asap.
