### ISSUE TITLE
Random Suggestions

### ISSUE THREAD

**Issue by airbreather** [voat/voat#643]
Did a non-exhaustive audit of the code and DB stuff just to see what's going on.  Most things are small, and I didn't want to create separate things for each one.  Feel free to do whatever you want with this; I'll answer direct questions for clarification, but that's about as far as I'm going to go.
- (db) Several ID columns used as keys are 32-bit and seem reasonably likely to overflow sometime in the future (submissions, comments, notifications).  It's not getting any easier to fix this as time goes on.
- (db) PK / clustered index on Subverses is the actual name rather than an increasing integral column, which will often increase the size of nonclustered indexes plus other tables that reference it, and potentially cause fragmentation nearly every time new subverses are created.
- (code) CacheHandler isn't really taking full advantage of `ConcurrentDictionary<TKey, TValue>`, as nearly all accesses are synchronized anyway... might as well just synchronize RefetchItem and use regular Dictionary<TKey, TValue> objects.  Note that if this causes deadlocks, then you probably already have a race condition because this method updates both the cache and meta dictionaries without going through `GetLockObject`.
- (code) Hardcoded English text... hardcoded English text everywhere...
- (code) Someone already pointed this out somewhere else, but there's way too much business logic in your controller classes, and even in your views.  It's not getting any easier to fix this as time goes on, and I think you're going to identify several reuse opportunities along the way that are currently just copy-pasted.
- (code) Other than the obvious issues with `IpHash.CreateHash` that someone pointed out somewhere else, hashing by the string representation could be ambiguous.  As [RFC 1924](https://tools.ietf.org/html/rfc1924) mentions, `1080:0:0:0:8:800:200C:417A` and `1080::8:800:200C:417A` are the same IP address.  There may be similar issues on IPv4 addresses -- all of this is a huge can of worms that I don't want to go into right now that leads to lots of complexity behind the scenes.  Assuming this hashing adds some kind of benefit at all over just parsing to `System.Net.IPAddress` and comparing other similar objects for equality, you probably at least want to make sure that equal addresses hash equally for this.

**Comment by PuttItOut** [comment]
These are all valid issues but I am closing right now as code has changed significantly since issue logged.
