### ISSUE TITLE
Merge features from AVE such as user tagging

### ISSUE THREAD

**Issue by dessalines** [voat/voat#644]
I've noticed that there is an RES-like stylesheet for Voat called AVE, that has a lot of cool features that pretty much everyone wants.

https://www.voat.co/v/AVE

Why not merge in those changes? Especially user tagging.

**Comment by jksg** [comment]
It’s not a stylesheet; it’s a GreaseMonkey userscript (JavaScript).

Those features cannot simply be “merged in” because they are not changes to Voat’s code but a completely separate set of code. Some of the logic might be helpful but any feature would essentially have to be rewritten as part of Voat.

The AVE developer could contribute directly to Voat if he was so inclined.

**Comment by DanielFlamino** [comment]
Besides those tags are only saved on one computer. Which means that if you were to open your account in another computer (or simply in another browser), you won't have all your tags.

**Comment by tchoulihan** [comment]
Okay, then how about making specific feature requests for things like user
tagging?

This is a really sought after feature, or extensions like ave and RES would
have no users.

**Comment by guest20** [comment]
On 13 July 2015 10:31:44 am AEST, Tyhou <notifications@github.com> wrote:
>Okay, then how about making specific feature requests for things like
>user
>tagging?
>
>This is a really sought after feature, or extensions like ave and RES
>would
>have no users.
>On Jul 12, 2015 7:20 PM, "Daniel Flamino" <notifications@github.com>
>wrote:
>
>> Besides those tags are only saved on one computer. Which means that
>if you
>> were to open your account in another computer (or simply in another
>> browser), you won't have all your tags.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/voat/voat/issues/644#issuecomment-120772178>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/voat/voat/issues/644#issuecomment-120776226

The point of hacks like this is to move pressure to implement and test new features from the core devs (voat) to the community.

Changes / innovation can be done faster on the greasemonkey scripts, and if people love the features, they can submit pull requests.

(And even if the pull request is denied, the feature lives on in the hacks)
-- 
Alastair Cooke - hacking perl at booking.com for great justice. 
Like D☆E☆R☆P on the wiki

**Comment by DanielFlamino** [comment]
>Okay, then how about making specific feature requests for things like user
tagging?

Sure, go ahead and make those.

**Comment by PuttItOut** [comment]
Closed as this is not a planned feature.
