### ISSUE TITLE
Deleting a PM should have a "Are you sure" warning prior to deletion

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#645]
Not much to add, the behaviour would be the same as when clicking to delete a comment. First time clicking, it appears "Are you sure? Yes/No", and it would delete only if the user clicked Yes, otherwise cancel.

Suggesting this because I just deleted a PM when trying to reply (I guess my muscle memory made thought the reply button was a bit more to the right).

**Comment by PuttItOut** [comment]
Closed as this is not a planned feature.
