### ISSUE TITLE
[Bug?] Last comment's children isn't seen unless it's collapsed or permalinked.

### ISSUE THREAD

**Issue by KinOfMany** [voat/voat#648]
Found in this thread https://voat.co/v/technology/comments/266821

Last reply to Atko (by startv) is automatically collapsed because of negative score. You can see this comment's children. If you uncollapse it, suddenly the child comments are gone. Child comments are set to  `display:none` for some reason.

Attached an illustration:
![illustration](https://cloud.githubusercontent.com/assets/13050434/8657544/f44f1a86-29a6-11e5-9d9d-3e4a375bbc6d.jpg)

**Comment by fringenerd** [comment]
I came across the same problem today. 
![commentbug](https://cloud.githubusercontent.com/assets/9771891/8704161/9de80a28-2b21-11e5-916b-e4a6ed586a77.jpg)

**Comment by mgiuffrida** [comment]
+1. [Another example](https://voat.co/v/funny/comments/286068) shows this problem recursively on child comments -- ctrl+f "nonsense", click "1 reply" under Bkow's post, then have fun collapsing/expanding comments in that thread.

**Comment by PuttItOut** [comment]
This is has been fixed:

https://github.com/voat/voat/commit/b3ad4543bdbaea9179fc6308838ff16727865212
https://github.com/voat/voat/commit/64cd296da0950f7163e9f5fa16fe3b7a4c8a7212
