### ISSUE TITLE
Had an issue being 'lock out of voat.' but easily circumvented it. Happened on a message.

### ISSUE THREAD

**Issue by FoundersDiscount** [voat/voat#653]
Safari browser. I had 4 notifications/messages on the voat main page. Comments and replies to comments. Replied to 3 of them. Got to my last one. It was on /v/civilization. Replied, clicked submit. Got a message in red below text box: 'You're doing that to much. try again in 30 seconds.' Did that, and several longer spurts of waiting and browsing other tabs before submitting, still nothing. Click through to the thread itself and tried. Same deal. Tried another comment in another subverse. Immediately let me comment. Come back to my /v/civilization message via the messages envelope button and try that one again. Same message. Then after trying and message the actual person (was a moderator discussing ideas for the subverse) I get a huge red and grey notification with an 'x' saying im locked out of voat. I just enter voat in the address bar and return to the site. This time, go to the subverse via the address bar ( www.voat.com/v/civilization), find the post in the subverse, enter the comment that way, and boom. It goes through. Weird.

**Comment by fringenerd** [comment]
I've had a similar thing happen to me once. I tried to reply to a comment in a thread but kept getting "You're doing that too much. Try again in 30 seconds." I waited and tried again, several times, to no avail. When I tried to reply to other comments, I could, but not to that one.
