### ISSUE TITLE
Desktop view mode doesn't work in iOS browsers and some android browsers

### ISSUE THREAD

**Issue by iliketurtlesbro** [voat/voat#654]
If using 'Request Desktop Site' on Firefox (tested on version 39) for Android (version 5.1.1), the user is successfully presented with the desktop view of Voat. However, it does not work on Chromium (version 45) for Android, or Safari for iOS 8.

**Comment by jksg** [comment]
Voat doesn’t have explicit desktop vs mobile versions, only one version of the site that reacts to your browser (viewport) width. You can get the “mobile view” by resizing a browser window to a small size on your desktop.

If the mobile browser’s “Request Desktop Site” feature merely changes its user-agent then it will have no effect. Firefox for Android specifically addressed the viewport issue by [pretending to have a desktop-like viewport](https://bugzilla.mozilla.org/show_bug.cgi?id=1106905). If you want similar functionality in other browsers it would be best to file a bug with them instead.
