### ISSUE TITLE
Duplicate but linked comments.

### ISSUE THREAD

**Issue by begetipa** [voat/voat#656]
![image](https://cloud.githubusercontent.com/assets/5445217/8677822/98d4ec7a-2a51-11e5-941c-d83bae23bab8.png)
---

![image](https://cloud.githubusercontent.com/assets/5445217/8677828/a50ed7e4-2a51-11e5-9b1c-42037d323296.png)
---

![image](https://cloud.githubusercontent.com/assets/5445217/8677966/4d9a89da-2a52-11e5-9bdc-0dcbcab87b62.png)

/u/Numzane

**Comment by PuttItOut** [comment]
Fixed
