### ISSUE TITLE
Trying to add RSS to a standalone reader returns an Error

### ISSUE THREAD

**Issue by LeafG** [voat/voat#659]
As the title say:
I get the following error when trying to add the feed to my stand alone reader (<a href="http://quiterss.org/" target="_blank">quiterss</a>), but it works fine from my browser at the same time.

Error text:
<i>Server replied: Service Temporarily Unavailable (301)</i>

Screenshot:
![voat-rss-error.jpg…](http://i.imgur.com/q5SfyR5.jpg)

**Comment by jksg** [comment]
This is likely due to the CloudFlare anti-DDoS measures in place temporarily. As your feed reader doesn’t behave like a “normal” browser it’s being blocked.

Hopefully the measures will be lifted soon.

**Comment by tyaremco** [comment]
Are there any plans to remove this protection so the rss feeds are useable?

**Comment by PuttItOut** [comment]
Closing this issue because of age, if still a condition please resubmit.
