### ISSUE TITLE
"Bad request" (error 400) when clicking "mark all as read" in Private Messages

### ISSUE THREAD

**Issue by llagerlof** [voat/voat#660]
A Voat user sent me a private message, but when I click in "mark all as read", I got the message "something went wrong."

This message is stucked in my Private Messages. 

![2015-07-15 11_09_06-inbox](https://cloud.githubusercontent.com/assets/193798/8700594/0d39439a-2ae3-11e5-9f40-6510ac000cbf.jpg)

**Comment by voat** [comment]
I was able to reproduce this when clicking the "mark all as read" twice.
