### ISSUE TITLE
User is able to access Remove Mod page without correct access level

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#661]
Credit to [@pembo210](https://voat.co/u/pembo210) for finding this one.

List of moderators of /v/testmoddelete. As you can see, spoooky_ghost is the only moderator and is the subverse creator.
![image](https://cloud.githubusercontent.com/assets/6509486/8702482/fb38ec04-2b0f-11e5-8420-bfb247efb9bd.png)

Page to remove spoooky_ghost as moderator
![image](https://cloud.githubusercontent.com/assets/6509486/8702488/fe061a1a-2b0f-11e5-9c87-b8ffd9390a5b.png)

Opened the above page again, but this time using my account
![image](https://cloud.githubusercontent.com/assets/6509486/8702489/01ca8d0c-2b10-11e5-8608-7273c934da24.png)

I can see the page (which I'd guess is probably not intended), but it seems that at least I can't remove spoooky_ghost as mod, because when I click the remove button, I just get redirected to the frontpage and spoooky_ghost seems to remain as subverse moderator. However I don't know if it might just be that some caching is being done and I haven't seen the changes take effect yet (Link to check if they eventually do take effect: https://voat.co/v/testmoddelete), so there might be a potential issue here. Still, that page should not be visible to other users.

When pembo reported this to me, he gave these links:

https://voat.co/v/pembo210/about/moderators/delete/2

https://voat.co/v/pembo210/about/moderators/delete/20

https://voat.co/v/pembo210/about/moderators/delete/43

https://voat.co/v/pembo210/about/moderators/delete/221

Which made me notice something else. I assume that the number after /delete/ is the subverse id that is used by the page to identify the subverse, whilst the subverse name on the url (in this case v/pembo210) is completely discarded.

**Comment by pembo210** [comment]
Ok good, you got it. I wanted to double check a few things before I made it public, just in case you could actually remove the mod. I did similar tests with both mod and non-mod users. All tests failed to remove the mod. I also waited an hour in case of caching. PuttItOut also confirmed via PM. Thankyou.
