### ISSUE TITLE
Why ASP?

### ISSUE THREAD

**Issue by techhelper1** [voat/voat#662]
Why ASP? Why limit it to the Windows/Mono platform? Seems like its a wasted overhead and possible expense.

Why not Ruby on Rails, Python, NodeJS, etc...?

**Comment by thestamp** [comment]
To do what no man has done before. To explore the capabilities and learn
new technology. To further our horizons, both in knowledge and
understanding.

This is why voat is what it is, and what it's made of.

If you want to choose another tech, go forth and prosper. For this is an
ASP MVC .net project, and are doing what we are setting out to do.

**Comment by thestamp** [comment]
Have set*

**Comment by DanielFlamino** [comment]
>This was just a hobby project to help me get a better understanding of C# and ASP.NET MVC and Entity Framework.

There you go. (Although I think thestamp's answer is better. :X)

**Comment by thestamp** [comment]
I got your back man ;)

**Comment by jacklify85** [comment]
Regardless, all the time spent remaking Voat into another language and frameworks would be of better use in refactoring and optimizing the current code base.

I'm a firm believer in it's more of  the developers and not the libraries or languages, but I'm biased. After all I make games in Java. :+1:
