### ISSUE TITLE
javascript: URIs not filtered properly

### ISSUE THREAD

**Issue by minitech** [voat/voat#663]
Applies to both Markdown:

```
[a link](&#106;avascript:alert%281%29)
```

and to submitted links, assuming the `submit` listener on the form has been disabled:

```
javascript:alert%281%29
```

The fixes are:
- use a scheme whitelist instead of a scheme blacklist, and
- validate submitted links server-side

respectively. ([Live](https://www.voat.co/v/AskVoat/comments/288665) [examples](https://www.voat.co/v/introductions/comments/288409).) I can submit a pull request if you like.

**Comment by voat** [comment]
Thank you, a PR would be nice.

**Comment by PuttItOut** [comment]
Fixed
