### ISSUE TITLE
Moderator list only displays 10 moderators

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#667]
As the title says, the moderator list only displays, what I think it is, the first 10 moderators ordered by alphabetical order, instead of showing all of them or providing a link to a page displaying all of them.

![image](https://cloud.githubusercontent.com/assets/6509486/8753977/f07fb4ce-2cb7-11e5-950d-07df61d1ef3c.png)

![image](https://cloud.githubusercontent.com/assets/6509486/8753968/e4626d6c-2cb7-11e5-837b-afb6767e0376.png)

**Comment by BrianAllred** [comment]
Looks like this is intentional, according to the code and comments. No mention in the comments on if it is temporary or not.

**Comment by nonillion** [comment]
Heh, sorry for submitting 2 commits. I've never used Github before

**Comment by talons1337** [comment]
I'm in the screenshot! Wow, I'm famoose!

**Comment by PuttItOut** [comment]
Fixed
