### ISSUE TITLE
[request] Uncurated front page

### ISSUE THREAD

**Issue by phly95** [voat/voat#669]
It's nice to see your subscriptions on the front page, but sometimes I want to see what it looks like when not logged in.

**Comment by jksg** [comment]
That’s what [/v/all](https://voat.co/v/all) (the “all” link in the top left) is for.

/v/all shows all public subverses that use default scoring settings (i.e. have no CCP restrictions on downvoting), minus those you’ve blocked. It will also show or hide NSFW subs depending on your account settings.

If you want to truly see what non-logged in users see, the easiest way is to open a new browser window in “incognito” or private mode.
