### ISSUE TITLE
[Request] Add an id attribute to the div containing the "# replies" a element.

### ISSUE THREAD

**Issue by HorzaGobuchul** [voat/voat#671]
Hello,

I'm modifying my extension to update modules, when more replies are loaded, with a MutationObserver.

The problem is that I can't really identify what is removed with certainty because the element deleted is a div with no attributes (which is singular in itself, but not enough).

I resorted to using the following line of code, but I'm afraid the conditional is not precise enough and could lead to errors.

```
if (e.removedNodes[0].tagName == "DIV" && e.removedNodes[0].id == "")
```

Would it be possible to add an identifier to the div in question?

**Comment by PuttItOut** [comment]
Closed as this is not a planned feature.
