### ISSUE TITLE
Open comments in new tab

### ISSUE THREAD

**Issue by nonillion** [voat/voat#679]
Because it's annoying to have to right click and open in a new tab

**Comment by thestamp** [comment]
Try middle click

**Comment by nonillion** [comment]
I don't have a middle click. I'm on a laptop. Also doesn't make it easier for those on mobile. All that'd need to change is adding target="_blank" to the <a> tag.

**Comment by thestamp** [comment]
Fair enough. I would rather it be a device specific setting though, rather
than affecting the experience of users on all devices

**Comment by nonillion** [comment]
In that case, a new setting could be added for "open comments in new tab". Though permalinks shouldn't be opened in new tabs, 'context' and 'full comments' should were the setting to be enabled.

**Comment by thestamp** [comment]
Sounds good to me!

**Comment by jksg** [comment]
Would like to see this as a per-user setting.

Objectively `target="_blank"` is bad on mobile because it reduces user choice. There is no way (by default in mobile Chrome/Safari at least) to force opening in the same tab, while normal links can be opened in a new tab easily with a long tap.

**Comment by Luk3M** [comment]
Maybe my pull request #690 can help this

**Comment by 39bit** [comment]
Apart from middle click, you could also try holding down Ctrl if you're on a laptop

**Comment by PuttItOut** [comment]
Closed as this is not a planned change.
