### ISSUE TITLE
Using DateTime.Now

### ISSUE THREAD

**Issue by nonillion** [voat/voat#682]
in the source, for ranking submissions Voat uses DateTime.Now. This is a quick and easy way to go about getting the time, however, it is not the best. See, DateTime.Now uses the local time which means should the servers ever switch to a different timezone it'll be thrown off. Now this is a speculative issue, however, the issue is that twice a year in most parts of the world, the time gets messed up. By this I mean, we change our clocks for daylight savings time.

Thus 2 times a year the ranking algorithm is thrown completely out of balance. Not a super huge issue as far as issues go, but this can easily be rectified by replacing any line that includes 

```
DateTime.Now
```

with

```
DateTime.UtcNow
```

**Comment by drusellers** [comment]
Also it might be worth considering the use of DateTimeKind which stores the TimeZone if that is important.

**Comment by shadcollins** [comment]
The time actually should be stored in UTC and converted on the fly to each user at render time.  This is the only way to keep everything straight.  This becomes a lot more relevant when using geo-load-balanced servers.  It also helps correlate logs from multiple devices and servers to get a consolidated view of what is going on.  Pro-tip from enterprise solutions development.

**Comment by Jaspaul** [comment]
To add to @shadcollins the other fun thing with timezones is that they don't really have any rules. For instance the US changed the day they observe daylight savings on in 2005 in an attempt to [reduce energy consumption](https://en.wikipedia.org/wiki/Daylight_saving_time_in_the_United_States#2005_revision_to_dates_of_observance). I can only imagine the headache that caused to people not using UTC to normalize all their dates and times.

**Comment by PuttItOut** [comment]
Fixed
