### ISSUE TITLE
Post submission restrictions not being properly applied

### ISSUE THREAD

**Issue by TheGuyWithTheFace** [voat/voat#683]
Copy-pasting this from [/v/VoatBugHunters](https://voat.co/v/VoatBugHunters/comments/337214), courtesy of [/u/pm_me_your_airbags](https://voat.co/user/pm_me_your_airbags): 

>The restrictions applied to post submissions in Voat include the following:
>
> * You can post up to 10 submissions to a particular subverse in 24 hours
>
> * You can post up to 3 submissions to a particular subverse in an hour
>
> * You may crosspost only 2 link submissions to different subverses in 24 hours
>
>However, some Voaters have commented that they have either been able to post submissions in apparent >contravention to these rules, or have seen other people do so (see, for example, the comments [here](https://voat.co/v/VoatFAQ/comments/330445)).
>
>The main function dealing with this is Submit() (the POST version) in [HomeController.cs](https://github.com/voat/voat/blob/master/Voat/Voat.UI/Controllers/HomeController.cs).

I'll also go ahead and share my thoughts on this, from the same thread:
> I do have a hunch about [Line 243 in HomeController.cs](https://github.com/voat/voat/blob/master/Voat/Voat.UI/Controllers/HomeController.cs#L243): It looks like [Utils.User.UserDailyPostingQuotaForSubUsed](https://github.com/voat/voat/blob/master/Voat/Voat.UI/Utils/User.cs#L649)'s second parameter is supposed to be a string containing the name of the subverse we're posting to. On line 243 however, we're posting something called submission.MessageContent.
>
>Now, this is where my context ends, because I don't know exactly what submission.MessageContent is, but it certainly doesn't sound like it would hold the name of the subverse. A low effort scan of the [Message class](https://github.com/voat/voat/blob/master/Voat/Voat.UI/Models/Message.cs) isn't incredibly helpful, but I do see that Message also has a property called Subverse. My hunch is that we're just passing the wrong property into UserDailyPostingQuotaForSubUsed, but without digging any deeper to find how MessageContent is actually used, that's the best I can do right now.

**Comment by voat** [comment]
Thanks for looking into this. MessageContent contains the content of a submission which can be 2 things: for link type submissions, this will be the URL submitted, otherwise, this will contain the text content of the submission.

**Comment by voat** [comment]
This should now be fixed.

**Comment by TheGuyWithTheFace** [comment]
What fixed it, if you don't mind me asking?
