### ISSUE TITLE
There's no link to recover your account, even if associated with your email already.

### ISSUE THREAD

**Issue by ryanelian** [voat/voat#691]
![screenshot 2015-07-31 15 13 51](https://cloud.githubusercontent.com/assets/8892187/9003318/1e2bc428-3797-11e5-8dbc-e16112570e53.png)

There's no link for account recovery in the login screen.

Registration screen shows invite only message but no link to account recovery.

**Comment by DanielFlamino** [comment]
Related to issue #6

**Comment by IvanDSM** [comment]
I've lost access (a long time ago) to my similarly-named account on Voat which exists since last year. I added my e-mail to the recovery field and I really miss this feature. Anyway, thanks to the team for working on such an awesome website!

**Comment by PuttItOut** [comment]
Fixed
