### ISSUE TITLE
"The search term must be at least 3 characters long." when searching for URL

### ISSUE THREAD

**Issue by mgiuffrida** [voat/voat#695]
Trying to search for https://www.techdirt.com/articles/20150801/00093531816/spanish-cops-use-new-law-to-fine-facebook-commenter-calling-them-slackers.shtml yields the error "The search term must be at least 3 characters long." when attempting to submit the search form.

Not sure what in particular about that URL is causing the error.

**Comment by OrbitApoapsis** [comment]
Looking here: https://github.com/voat/voat/blob/a5f7479e922ff711553bc631c48780bbe1b8318e/Voat/Voat.UI/Models/ViewModels/SearchViewModel.cs#L22
and testing to confirm, search entries have a 100 character limit. That link is 134.

**Comment by PuttItOut** [comment]
Closed as this is not a planned change.
