### ISSUE TITLE
Domain bans are not applied in comments

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#700]
I don't know if this is a bug or if it just wasn't implemented (and I don't think v/science is ignoring the domain bans), but banned domains are still allowed to be posted in comments. [Example](https://archive.is/WHmIq) that links to manhood101.com, which is listed as banned under spam in https://voat.co/api/bannedhostnames.

**Comment by PuttItOut** [comment]
Comment content simply isn't filtered.

**Comment by DanielFlamino** [comment]
Since the comments are also used for spamming links (that example pretty much just spams in comments), shouldn't comment content also be filtered?

**Comment by PuttItOut** [comment]
Wouldn't be a bad idea. The real question is where does this rank on our very small TODO list. #2 or #3? ;)

**Comment by DanielFlamino** [comment]
I think it's #-1 obviously.

**Comment by TNTGav** [comment]
I had a brief look into this and it's not a small job, the largest job being extracting each domain out of the comment that gets posted then checking each one is not banned against the BanningUtility.

**Comment by PuttItOut** [comment]
Fixed
