### ISSUE TITLE
Ability for moderators to allow duplicate links on their subverse

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#701]
This one is mainly because of v/subverserequest, but it might also be useful for other subverses. Pretty much have the ability to disable the duplicate link check in a subverse. For example, if I want to make a submission that links to v/subverse and someone else did it before, I have to add an # or something so that the duplicate check isn't triggered.

**Comment by PuttItOut** [comment]
Closed as this is not a planned feature.
