### ISSUE TITLE
ChildCount error

### ISSUE THREAD

**Issue by jingyuyao** [voat/voat#708]
During testing I made the following api call:

GET https://fakevout.azurewebsites.net/api/v1/comments/13058

Raw response body: {"success":true,"data:{"id":13058,"parentID":null,"submissionID":5535,"subverse":"Test","date":"2015-08-09T18:29:06.627Z","lastEditDate":null,"upVotes":0,"downVotes":0,"userName":"swampfire100","childCount":null,"level":null,"content":"Generic hateful, ignorant and arrogant comment","formattedContent":"<p>Generic hateful, ignorant and arrogant comment</p>\n"}}

The child count returned by the api is null but the expected child count should be 2 according to the comment permalink: https://fakevout.azurewebsites.net/v/Test/comments/5535/13058

**Comment by PuttItOut** [comment]
Fixed
