### ISSUE TITLE
Cannot report subverse in voat.co/subverses page

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#710]
A picture is better than a thousand words (but not better than a thousand cookies):

![image](https://cloud.githubusercontent.com/assets/6509486/9185954/5fb0fa0c-3fb8-11e5-9791-2c5b28d1a364.png)

"Uncaught ReferenceError: change_state is not defined"

So we have a missing function somewhere.

**Comment by PuttItOut** [comment]
Would be nice but closed as this is not a planned feature.

**Comment by MagicalBlob** [comment]
Shouldn't the report button be removed then?
