### ISSUE TITLE
Strange negative vote count

### ISSUE THREAD

**Issue by jksg** [voat/voat#724]
There’s [a post](https://voat.co/v/gifs/comments/415777) with a negative number of downvotes (not negative score), resulting in >100% likes.

[Screenshot](https://veuwer.com/i/31ma.png) of the post itself, and [screenshot](https://veuwer.com/i/31mb.png) of the post in /v/all with `(+10|--2)` score.

---

With some investigating, it got worse :grimacing:

After I downvoted the above post, I cannot remove my downvote. Clicking the active downvote arrow makes it inactive on my current view, but refreshing the page shows that the score has updated (decrementing by 1 downvote), yet the downvote state is still active. I can repeat this indefinitely to continue decrementing the downvote count by 1 each time. The user now has 47 SCP from 13 upvotes and -34 downvotes.

**Comment by voat** [comment]
This should no longer be an issue. Please report back here if you can reproduce this. Thank you.
