### ISSUE TITLE
SCP and CCP should remain after submission/comment deletion

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#727]
There have been spammers that delete their downvoted comments and submissions in order to get back up the threshold limits and essentially "reenable" their accounts. A good solution for this is to make that SCP and CCP permanently affect the account.

**Comment by voat** [comment]
Duplicate of #138 :)

**Comment by DanielFlamino** [comment]
I thought that was just to make it not calculate on the fly, and not to make it stay after deletion. My bad, I guess.

**Comment by voat** [comment]
You're right, the purpose was not the same but the implementation will tackle both issues. The code should now be ready: https://github.com/voat/voat/commit/7ef473dc93e5e2c74a825854db17c6aee2cbb991.

**Comment by DanielFlamino** [comment]
Good to know that! :)
