### ISSUE TITLE
Cannot remove user.

### ISSUE THREAD

**Issue by KinOfMany** [voat/voat#730]
Submissions aren't removed, and the user itself isn't either.

Found here: https://github.com/voat/voat/blob/ead0b32cfe1cf1b63e7a5696b79f63d6fb9f7d28/Voat/Voat.Business/Utilities/UserHelper.cs#L60

UPDATE: Dan tested this, and it turns out there's a NullReferenceException on line 115.
https://github.com/voat/voat/blob/ead0b32cfe1cf1b63e7a5696b79f63d6fb9f7d28/Voat/Voat.Business/Utilities/UserHelper.cs#L115

**Comment by DanielFlamino** [comment]
https://i.imgur.com/F6lxGCg.png

**Comment by DanielFlamino** [comment]
http://i.imgur.com/QuxEaMV.png

http://i.imgur.com/WcuaVB5.png

Creating an entry for the user on the Userpreferences table seems to make it work

**Comment by KinOfMany** [comment]
Thanks Dan, as always for your contribution :)

Changing setting to nightmode and removing the account is a temporary workaround.
