### ISSUE TITLE
Level 2 Moderators can't resign via the Subverse Moderators list

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#732]
Since, up until very recently, lvl2 mods couldn't access the subverse moderators list, the resign option was just a _not so obvious_ link on the sidebar. Now even though they can access said list, they can't click on the Remove link and effectively resign since those links were designed for lvl1 mods.

I purpose dropping the [resign link](https://i.imgur.com/qQq238d.png) and simply allow level 2 mods to click on the Remove link (only the one that is their own username of course)

**Comment by calloatti** [comment]
Right now you can click on the link, but nothing happens, you just get redirected to the home page

**Comment by PuttItOut** [comment]
Fixed
