### ISSUE TITLE
Wonky Landing Page

### ISSUE THREAD

**Issue by smalltock** [voat/voat#733]
I see this nearly every time I type in voat.co.
I'm using [Qutebrowser](https://qutebrowser.org).

![untitled](https://cloud.githubusercontent.com/assets/3895638/9300953/ac52420a-447f-11e5-971e-69d8f5646e41.png)

Any idea how to approach this?

**Comment by jksg** [comment]
The CSS stylesheet isn’t loading. I’m not familiar with Qutebrowser but if it has the same inspector as WebKit browsers (`wi` should bring it up according to [this](http://qutebrowser.org/img/cheatsheet-big.png), open it and look for a “Network” tab.

Reload the page and watch the list of files populate. If any file fails to load it will show up in red. Click on that row to get more information and then screenshot it here.

**Comment by smalltock** [comment]
No CSS is loading at all. Nothing shows up in red seemingly because, as the indicator at the bottom suggests, the browser is still trying to load it, but it never gets any further.

If I click one of the links to navigate to a different page, it'll load properly.
![jej](https://cloud.githubusercontent.com/assets/3895638/9344961/720a2cfa-45c1-11e5-9325-2d473efc4cf0.png)
