### ISSUE TITLE
voat.sql isn't updated?

### ISSUE THREAD

**Issue by KinOfMany** [voat/voat#734]
My local copy of Voat returns an exception on line 367 with the message ````Invalid column name 'IsDeleted'.````

https://github.com/voat/voat/blob/master/Voat/Voat.UI/Controllers/HomeController.cs#L367

**Comment by TNTGav** [comment]
You will need to run the schema update : https://github.com/voat/voat/blob/master/Voat/SqlScripts/voat-SchemaUpdate.sql

**Comment by KinOfMany** [comment]
But IsDelete isn't there too.

**Comment by voat** [comment]
Sorry about that. You will need to manually add IsDeleted bit field in Messages and Comments table with default values of 0 until we update the scripts.
