### ISSUE TITLE
Open-ended html tags apply that formatting to the entire comments section below the formatted comment.

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#737]
Reported [here](https://voat.co/v/voatdev/comments/430065) by [LegoMyEgo](https://voat.co/user/LegoMyEgo)

In action: https://voat.co/v/announcements/comments/194043

Also occurs in user profile: https://voat.co/user/DanielFlamino
![image](https://cloud.githubusercontent.com/assets/6509486/9388026/2da3a866-475b-11e5-82d4-e3b666c35fcf.png)

More: https://voat.co/v/voatdev/comments/465645

**Comment by DanielFlamino** [comment]
[Bold and italic also confirmed bugged](https://archive.is/eN4LU)

**Comment by DanielFlamino** [comment]
Might not be a bad idea to simply remove all tags that have a markdown counterpart from the whitelist, though then we'd still have to deal with `<s> <sup> <sub>`

**Comment by voat** [comment]
Thank you for reporting this. All previously considered safe tags are now removed, including s, sup and sub, from the markdown deep library. Fixing this properly should be done by their team, if they are still maintaining it, which I doubt..
