### ISSUE TITLE
Undelete / Restore option for accidentally deleted posts

### ISSUE THREAD

**Issue by jeffmcneill** [voat/voat#741]
Hello,

I've accidentally deleted a post, but cannot find a way to restore / undelete. This is someone else's post in a subverse I am a mod in. Please advise or add as feature request.

Thanks!,
Jeff

**Comment by ghost** [comment]
To the @voat team, I would suggest instead cloaking data instead of deleting, in order to keep things like this from happening.

**Comment by PuttItOut** [comment]
Closed as this is not a planned feature.
