### ISSUE TITLE
Bug that allows you to edit a removed comment

### ISSUE THREAD

**Issue by KinOfMany** [voat/voat#745]
This bug allows the user to change the [Removed by author at...] string with something else.
Here it is in action: https://voat.co/v/AskVoat/comments/436754/1976465

Steps taken to reproduce:
1. Make a comment.
2. Open permalink in another tab.
3. Edit comment in the first tab. Hit save.
4. Wait until comment is completely removed.
5. Refresh the permalink page, and you should see an edit button.
6. Edit to whatever string you like.

SurvivorType's method of reproducing:
1. Make a comment.
2. Make a child comment.
3. Delete the child.
4. Refresh page.
5. Edit before caching catches up.

Reported by Moe, DanielFlamino & SurvivorType

**Comment by voat** [comment]
Thank you for reporting this.
