### ISSUE TITLE
Can't update profile image

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#747]
https://gfycat.com/RichVigilantEyelashpitviper

~~Or at least there's no confirmation of sucess.~~ Doesn't seem to be caching related because it hasn't updated yet.

**Comment by voat** [comment]
This should no longer be an issue (please give it 10 minutes or so for the update to show). Also happy new year :)

**Comment by DanielFlamino** [comment]
Yep, I managed to update it eventually. :)
