### ISSUE TITLE
Can't get beyond protection (Checking your bits) page while on a slow connection.

### ISSUE THREAD

**Issue by salvenose** [voat/voat#748]
A bunch of us users can't access Voat at all. The protection page is 749KB in size, which is just way to big for such a simple page. Adding the images and css embedded in the html is just a bad idea.

For one firefox or any other browser can't cache the images and css which means fetching 749KB of data every time the protection page is loaded. And because of the timeout set, we get stuck in an infinite loop were the protection page is the only thing we have access to.

It just reloads and reloads forever. Please fix this.

**Comment by leofidus** [comment]
#748 would fix this
