### ISSUE TITLE
Add translations into other languages and a possibility to contribute.

### ISSUE THREAD

**Issue by mak3e** [voat/voat#749]
It would be nice if we could translate voat into other languages and it would bring new users from non-English-speaking countries.

**Comment by jksg** [comment]
See #638

**Comment by talons1337** [comment]
Well, if it does become a thing, I wouldn't mind helping out with Polish localisation.

**Comment by Estruenos** [comment]
Main developers think it's not worth it. They're wrong, underestimating international visitor traffic.

**Comment by mak3e** [comment]
I agree with @Estruenos. There is many international visitors including myself. I understand that translations can't be first on the to-do-list but I hope that they understand the importance of them for an international website like Voat.

**Comment by leofidus** [comment]
I'm pretty sure that our main developers are very aware of international visitors (it's hard to miss that most people aren't Swiss). But translations are hard and require a lot of code changes and effort. Meanwhile there's 200 open issues and 50 open pull requests. 

Also, the number of international visitors isn't relevant as it makes no sense to use a translated interface to access English content. The important metric is the number of people who would form a non-english-speaking community inside voat. For example my primary language is German, but I never participated in a German speaking community on reddit or voat. The English content is just more interesting. Are there any examples of big non-english communities on a fully translated site like reddit?

**Comment by Estruenos** [comment]
I understand what you say, leofidus, but:
By adding internalization to the code, they will get:
 - More users from other languages.
 - More international developers helping with the source code, as it becomes more useful for them in their own projects.
This second one, is I believe, very valuable; even more than the first.

**Comment by talons1337** [comment]
@leofidus There are some subs completely in Vietnamese or completely in Polish, like /r/polska. And I do believe that /r/schland is *mostly* german, but I don't remember.

**Comment by leofidus** [comment]
@talons1337 but they are small. /r/polska has about 21,400 subscribers /r/schland less than 6000, /r/ru less than 2300. For comparison: both /r/4chan and /r/programming have over 600,000 subscribers, /r/wheredidthesodago has 370,000 subscribers.
