### ISSUE TITLE
Target Mono framework

### ISSUE THREAD

**Issue by missyyyyyyy** [voat/voat#75]
To contribute to Whoaverse I need to be able to build it on [Mono](http://www.mono-project.com/).

Normally I wouldn't even ask, but to my surprise Whoaverse appears to be extremely close to build-able on Mono already: the only problems are the use of `System.ComponentModel.DataAnnotations.UrlAttribute` (in AddSubmissionLinkpost) and `System.Web.Routing.RouteCollection.LowercaseUrls` (in RouteConfig), which Mono has not (yet) implemented.

I think I can do the work, but I need to know if the goal of targeting Mono is acceptable to you. It would at times be an inconvenience, but I know I am not the only person who would prefer to not buy Windows in order to contribute to an open-source project.

**Comment by gholol** [comment]
@AngraManyu Well you could say how you managed to do it?
