### ISSUE TITLE
BANK FINANCE INSTRUMENT SUCH AS BG,SBLC,LC, FOR LEASE,

### ISSUE THREAD

**Issue by Ibrahim10** [voat/voat#750]
Dear sir/Ma

We are project funder with our cutting edge and group capital fund we can finance your signatory projects and help you to enhance your business plan, our financial instrument can be used for purchase of good from any manufacturer irrespective of location. We specialized in BG, SBLC, MTN, CD,LC , Non collateral loan, confirmable Bank Draft and other financial assistance from AAA rated bank (Prime Bank). The financial instrument can be invested into High Yield Trading Program or Private Placement Programme (PPP). Please see our instrument description and leasing procedure as follow.

DESCRIPTION OF INSTRUMENT:
1. Instrument: Bank Guarantee {BG} /StandBy Letter of Credit{SBLC} (Appendix A)
2. Total Face Value: Eur/USD 1M{Minimum} to Eur/USD 10B{Maximum}
3. Issuing Bank: AAA Rated Bank (Prime Bank).
4. Age: One Year and One Day
5. Leasing Price: 5.0% + 2% Broker commission
6. Delivery: S.W.I.F.T MT-760
7. Payment: MT103 (TT/WT)
8. Hard Copy: Bonded Courier Service

We specialize in Bank Guarantee lease and sales, there are two types of bank guarantee which are Direct Bank Guarantee and Indirect Bank Guarantee. Its used as Bid Bond, Payment Guarantees, Letter of Indemnity,

Guarantee Securing Credit Line, Advance Payment Guarantees, Performance Bond Guarantee E.T.C.
Intermediaries/Consultants/
Brokers are welcome to bring their clients and are 100% protected. In complete confidence, we will work together for the benefits of all parties involved.

Thank you
BROKERS ARE WELCOME & 100% PROTECTED!!!
Contact Email : mibram.fundings@gmail.com
Skype ID: mibram.fundings

**Comment by OffTheChartMaymays** [comment]
[Interesting...](https://www.youtube.com/watch?v=Ccoj5lhLmSQ)
