### ISSUE TITLE
Avatar image bug.

### ISSUE THREAD

**Issue by Thel3igO** [voat/voat#752]
Hello Voat,

I am @Thel3igO, and I have noticed that it is not possible for me to change my avatar picture from its default. I already tried to change the file type, but that didn't work. I contacted another user (@farmer-) and they said that they couldn't change their current, non-default avatar picture to another either. I am reporting this as a possible bug. If it would help, here is the link to the image I am trying to upload.
http://f0.bcbits.com/img/a3515396073_2.jpg

Thanks!

--O

**Comment by terrorist96** [comment]
:+1:

**Comment by KeenRivals** [comment]
Same issue here. I uploaded [my avatar](http://i.imgur.com/LTMauxR.png) and on my profile page I just see a blank space where the avatar should be. Accessing the [avatar URL](https://cdn.voat.co/avatars/rigamarole.jpg) directly gives me a "BlobNotFound" error.

I also notice you're converting my PNG avatar to jpeg. That's not really a good idea, as the PNG is 128 bytes and a jpeg at quality 0 is over 600 bytes. You might want to optimize your image conversion system. This could be as simple as "Is png smaller than jpeg? Yes: use png, No: use jpeg".

**Comment by voat** [comment]
Avatars are stored on our CDN and cached in at least 2 places. It could take a few minutes for the new avatar to appear in your profile.

**Comment by terrorist96** [comment]
This still doesn't work for me. 
https://cdn.voat.co/avatars/terrorist96.jpg

<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:0bdfd3ce-0001-0008-7194-60338e000000 Time:2016-02-06T04:12:43.1519593Z
</Message>
</Error>

**Comment by terrorist96** [comment]
And now it works..
