### ISSUE TITLE
Should downvotes have more weight than upvotes?

### ISSUE THREAD

**Issue by voat** [voat/voat#753]
Since all new accounts can immediately upvote but not downvote, should downvoting have more weight given the fact that downvoting is restricted to accounts with predefined amount of CCP?

**Comment by terrorist96** [comment]
How will the magic ratio be determined?

**Comment by SemiNormal** [comment]
No. This would just make vote brigading worse.

**Comment by PuttItOut** [comment]
Closed as this is not a planned change.
