### ISSUE TITLE
Username Changes

### ISSUE THREAD

**Issue by SysVoid** [voat/voat#754]
I searched and didn't find this as an issue, so I'll submit it.

We should be able to change our usernames once a month or something around that.

**Comment by git-project-one** [comment]
I feel that this could result in a lot of confusion, etc. Whats wrong with creating new account in the same fashion as many forums / reddit / etc.

**Comment by SysVoid** [comment]
I'm an alpha user that wants to keep the badge, sub verses and comments. Username history could be a thing.

**Comment by voat** [comment]
This is most likely not going to become a feature.
