### ISSUE TITLE
New users won't get the "Early Adopter" badge after 2015-08-31

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#756]
https://github.com/voat/voat/blob/master/Voat/Voat.UI/Views/Shared/Sidebars/_SidebarUserInfo.cshtml#L96-L112

**Comment by talons1337** [comment]
Hey wait a second, wasn't 31/08 the date that the badges were going to be ended last year? 

#muhexclusivity

There should be a "who?" badge for whoaversians :)
