### ISSUE TITLE
128 char password getting "must be more than 6 chars long" error

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#757]
https://voat.co/v/Voat/comments/467043

![image](https://cloud.githubusercontent.com/assets/6509486/9586283/c46c869e-5013-11e5-9929-9d7b25deafbb.png)

Could it be a case of a too long password but wrong error message text?

**Comment by talons1337** [comment]
By the looks of it, it's either using a signed int with 8 bits of data (so when you get to 128, it goes to -1), or it's an unsigned int with 7 bits of data.

**Comment by Carterj3** [comment]
Or it just gives that error message if validation fails. I believe the maximum length is 100.
https://github.com/voat/voat/blob/master/Voat/Voat.UI/Models/ViewModels/AccountViewModels.cs

**Comment by PuttItOut** [comment]
Fixed

**Comment by MagicalBlob** [comment]
I'm afraid not...

![image](https://cloud.githubusercontent.com/assets/6509486/19989438/62505180-a21e-11e6-8a09-94f1fd03ac68.png)

Inserted string: "TMhLx9lBAQQckxnjpAMnljWXRovVfFniP0UKytutnkpJzUjSPHEeBptX2To4XVwVfaPpwvp6noyZGyNm0lIfolCFl69SGBWV7uQAG" 101 chars
