### ISSUE TITLE
Comments downvoted below threshold are auto collapsed in the comment reply page of the inbox

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#764]
Reported [here](https://voat.co/v/voatdev/comments/480314) by [TheBlackerMath](https://voat.co/user/TheBlackerMath)

![image](https://cloud.githubusercontent.com/assets/6509486/9682424/692e05a8-52fe-11e5-9fcd-bc171837156c.png)

**Comment by PuttItOut** [comment]
Fixed
