### ISSUE TITLE
Implement unit testing with mocking framework for Entity Framework

### ISSUE THREAD

**Issue by voat** [voat/voat#77]
Whoaverse relies heavily on Entity Framework. Currently, there are no unit tests in whoaverse codebase which test data manipulation through EF. 

I suggest implementing this with a mocking framework as described in this article: http://msdn.microsoft.com/en-us/data/dn314429.aspx.

**Comment by PuttItOut** [comment]
The API will release the first version of this framework.

**Comment by PuttItOut** [comment]
Closed as this is not a planned change.
