### ISSUE TITLE
An error occurs when submitting to an anonymous subverse

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#770]
https://voat.co/v/voatdev/comments/478060

https://voat.co/v/help/comments/479237

https://voat.co/v/voatdev/comments/483506

https://voat.co/v/bugs/comments/483864

When making a submission to an anonymous subverse, the user is redirected to the "Well this is embarrassing. Something went wrong and let's face it, nobody's happy about it. We'll dispatch our monstersquad to take a look at it right away!" error page.

**Comment by madmalloy** [comment]
Having the same problem.

**Comment by DanielFlamino** [comment]
Looks like it has been fixed
