### ISSUE TITLE
can't load voat on chrome on Windows 10

### ISSUE THREAD

**Issue by gofirst2220** [voat/voat#774]
see title. it just gives a infinite loop on "checking your bits" page.

**Comment by DanielFlamino** [comment]
I can sort of reproduce this issue, but to me it only happens when I'm having connection issues (mainly when my speed drops down), so it might not be the same thing. Could it be an effect of a certain extension or do you not have any?

**Comment by gofirst2220** [comment]
my connection is strong, and none of the extensions seems to help
