### ISSUE TITLE
You can invite yourself to moderate your own subverse if you add a space before your username in the invitation form.

### ISSUE THREAD

**Issue by ArotaesForgehammer** [voat/voat#779]
Discovered again through dickery on v/soapboxbanhammer

**Comment by DanielFlamino** [comment]
I was about to make this after reading your thread. GG

Also, more proof that SBBH is a great addition to Voat.

**Comment by DanielFlamino** [comment]
![image](https://cloud.githubusercontent.com/assets/6509486/9834092/24fd91b2-59a4-11e5-8540-aeafeb2cd47b.png)

Now there's an invitation that I can't accept nor recall. Neat! :D

**Comment by ArotaesForgehammer** [comment]
95% of the bugs I find is through trying to find ways to alienate the other mods on SBBH.

**Comment by PuttItOut** [comment]
Fixed
