### ISSUE TITLE
Image link to voat mascot is broken in readme.md

### ISSUE THREAD

**Issue by rnand** [voat/voat#783]
The link to voat mascot is broken in the readme:
![1](https://cloud.githubusercontent.com/assets/12506856/9869562/6b934c0c-5ba2-11e5-8e19-ec976d27f3cb.PNG)

When I click on it, a "file not found message" is shown:
![2](https://cloud.githubusercontent.com/assets/12506856/9869574/857ca7d0-5ba2-11e5-9cd5-230d518cb6c9.PNG)

**Comment by DanielFlamino** [comment]
Problem with CloudFlare, maybe?

**Comment by rnand** [comment]
@DanielFlamino I think it's because of the "verifying your bits" thing on voat.co. Try opening this: https://voat.co/Graphics/voat-goat.png. If the image is displayed without issues, try reloading. You'll see the "verifying your bits" thing. So if you link this in an img tag, most of the time the image will not be displayed. You can try it out by creating an html page and using an img tag with https://voat.co/Graphics/voat-goat.png as the src.

I have fixed it by linking a relative path to the image from the repo itself rather than using the voat.co site.

**Comment by DanielFlamino** [comment]
Yep, that's what I was thinking. Looks like the relative link works just fine.
