### ISSUE TITLE
Minor security flaw in the new API

### ISSUE THREAD

**Issue by KinOfMany** [voat/voat#784]
Despite there being a "Publicly display my subscriptions on my profile" button, people can still see a user's subscriptions by calling `api/v1/u/{user}/subscriptions`.

**Comment by voat** [comment]
Thank you for reporting this. Please note: this is only related to the beta API which currently has no connection to the live database.

**Comment by KinOfMany** [comment]
Yeah, I understand. If you could direct me to the code that handles these requests, I could try and fix the bug, shouldn't be too hard.

**Comment by voat** [comment]
This should be resolved in the latest api version (which is not public yet but release date is close)
