### ISSUE TITLE
Auto-link thingy runs if the link is inside a code tag

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#787]
For example, this:
`firefox -new-tab http://www.venturebeat.com`
renders like this:
`firefox -new-tab [http://www.venturebeat.com](http://www.venturebeat.com)`

Live example:
https://voat.co/v/Voat/comments/526553

EDIT: Only occurs if 4 four preceding spaces are used to make the code markup, the 3 tildes or the single quote methods do not cause this issue.

![image](https://cloud.githubusercontent.com/assets/6509486/19190424/572d2c40-8c95-11e6-9c6a-93e52b836937.png)

**Comment by PuttItOut** [comment]
Should be fixed

**Comment by MagicalBlob** [comment]
[Looks like it isn't](https://voat.co/v/test/1387803)
