### ISSUE TITLE
Offer Voat on zeronet

### ISSUE THREAD

**Issue by Konstamokh** [voat/voat#790]
Recently I discovered www.zeronet.io and thought that Voat should be offered using this, in addition to the normal website.

**Comment by voat** [comment]
I wish this was possible right now, but modifying Voat to run on zeronet is just nor realistic. One would be better off with writing something like that from scratch with zeronet environment in mind. /Atko

**Comment by Konstamokh** [comment]
Indeed. It's not possible at the moment.
We should keep an eye out for the different ongoing projects that thrive to make the internet more decentralized.
