### ISSUE TITLE
Voat Can be Run on this Configuration?

### ISSUE THREAD

**Issue by GodOfConquest** [voat/voat#796]
So, I'm planning to try Voat on this following configuration at Azure.

VM =
Type: Windows 
1. |  |CORES|	|RAM|	    |  DISK SIZES|	
A0|	1	       |0.75 GB|	  |20 GB|
https://azure.microsoft.com/en-us/pricing/details/virtual-machines/
I'm thinking to later scale up to higher RAM and cores as required. Will it run on the following Configuration as starting? 
And another query, Should i go for Cloud or VM on Azure? which would be best for voat? and recommended?

**Comment by voat** [comment]
Hi, everything depends on the number of users you want to support. I would start with something small and scale up as needed. Keep in mind that you also need at least one DB server (SQL express will do for a small user base) and I would recommend you keep that on its own machine (at least 1 VM for IIS and 1 for DB).
