### ISSUE TITLE
Cannot find Reference and error on restoring packages

### ISSUE THREAD

**Issue by franzbuenaventura** [voat/voat#797]
tried doing this: https://github.com/voat/voat/issues/467

Unfortunately when I try restoring through Package Manager Console:

Update-Package : Some NuGet packages are missing from the solution. The packages need to be restored in order to build the dependency graph. 
Restore the packages before performing any operations.
At line:1 char:1
+ Update-Package -Reinstall
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Update-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetMissingPackages,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand

When I tried restoring the packages, a lot of it are "unable to find version ..."

**Comment by voat** [comment]
Please direct this to https://voat.co/v/programming. Thank you.
