### ISSUE TITLE
Increase CSS Character Limit

### ISSUE THREAD

**Issue by AmyAcker** [voat/voat#798]
It was said back in July (IIRC) that the character limit would be tripled (150k from current 50k). I remember the conversation from IRC. The user was told to open an issue, but looks like that never happened.

It would be great to finally see this implemented. Atko, pls.

**Comment by bradgreens** [comment]
It's 10,000 characters.

<img width="1036" alt="screen shot 2016-01-10 at 12 50 51 pm" src="https://cloud.githubusercontent.com/assets/284366/12223915/e2ced852-b798-11e5-8d40-fd2ed3ecc727.png">
