### ISSUE TITLE
Add class="selected" to items in "my subverses" popout menu

### ISSUE THREAD

**Issue by YoshiTigerfish** [voat/voat#80]
In the main navigation bar that lists the default subverses it sets the class to "selected" for the link to the subverse if you are actually in that subverse. It would be good to have it apply the selected class to items in the "my subverses" menu if you are currently in one of the subverses in it.

**Comment by DanielFlamino** [comment]
I don't see this implemented, was the idea discarded?

![image](https://cloud.githubusercontent.com/assets/6509486/6092770/17e20468-aee6-11e4-8972-3f5e0c64a86b.png)

**Comment by voat** [comment]
The idea was discarded - not a priority right now and it is also likely that <1% of users use the my subs menu. The menu itself may be redesigned to show "my sets" instead. We'll see :)

**Comment by DanielFlamino** [comment]
Ah ok, that makes sense. To be fair I don't even use the top bar at all. Just the "more »" link.
