### ISSUE TITLE
PMs sent by the server are displayed as sent by /u/Voat which doesn't appear to be a system account

### ISSUE THREAD

**Issue by DanielFlamino** [voat/voat#807]
Once again, title + image explains it all...
![image](https://cloud.githubusercontent.com/assets/6509486/12070099/d32de3d2-b056-11e5-9f47-1d3237b56358.png)

https://voat.co/u/Voat

Also, happy new year! :)

**Comment by MagicalBlob** [comment]
This has since been fixed.
