### ISSUE TITLE
password policy is inconsistently enforced

### ISSUE THREAD

**Issue by ulrikrasmussen** [voat/voat#809]
I tried creating a new account with a 26 letter long password consisting of lowercase letters and numbers. Voat refused, and told me that password has to contain at least one special character.

I appended a special character to the end and subsequently changed my password back to the original one (without special characters) using the "Manage" button.

I propose that you remove all password restrictions except requiring passwords to be at least 6 characters long. My password is more than secure enough - it is generated by a hash function - and overly specific password policies will just annoy people.

**Comment by ghost** [comment]
I agree with this, and adding a password strength meter will help put more of the responsibility of creating a strong password to the users.

**Comment by PuttItOut** [comment]
By design
