### ISSUE TITLE
Unable to log in or register

### ISSUE THREAD

**Issue by Aukxsona** [voat/voat#810]
I was unable to log in to my Voat_a_Goat_Mamma account.  When I tried to register as a different account, not happening. It just returned to the page I was on like nothing happened. People are posting and voat is up.  Is this an isp ban and if so why?  I don't understand what happened?

**Comment by dodged** [comment]
hello when I try to log in nothing seems to happen, If I try an incorrect password it will tell me (incorrect password)  .... my login :dodge is having trouble

**Comment by voat** [comment]
Hi, we don't do IP bans. This may be a connection issue with your internet provider. Please try again on another connection or with a different browser.
