### ISSUE TITLE
Post's comments become completely inaccessible when nested comment section containing 256 comments is on the comment page.

### ISSUE THREAD

**Issue by pembo210** [voat/voat#818]
u/Boukert, u/Jobes, and u/Zaebos_11 inadvertently discovered a bug that renders a thread completely inaccessible. The working theory, which they reproduced, is that once a reply chain hits 255 or 256 nested comments the thread locks you out (in other words, you could hit "Parent" 255 times on the final comment and keep going up the thread). Once critical mass is reached, you can no longer view the thread when you try to open it, even though it worked moments earlier. The post can still be seen in the subverse, but will send you to a "Whoops!" page when you try to navigate to the comment section.

Two threads in question:  
- https://voat.co/v/soapdoxbanhammer/comments/749001
- https://voat.co/v/soapdoxbanhammer/comments/704909

The comments API fail:  
- https://voat.co/api/submissioncomments?submissionId=749001
- https://voat.co/api/submissioncomments?submissionId=704909

The the post info is still accessible:  
- https://voat.co/api/singlesubmission?id=749001
- https://voat.co/api/singlesubmission?id=704909
---

/v/bugs post - https://voat.co/v/bugs/comments/850617
Posted on behalf of non-github users.

**Comment by PuttItOut** [comment]
Fixed
