### ISSUE TITLE
Notifications are not received when the number of characters of the message is more than 3990

### ISSUE THREAD

**Issue by kashka-voat** [voat/voat#820]
I have reported the bug [here](https://voat.co/v/voatdev/comments/845736) and user In_Cog_Nito helped me test it there. After some tests we concluded that Voat does not send notifications for messages containing more than ~3990 characters, a safe number to trigger the bug seems to be 4000. We are not sure if this is caused by the number of characters in the markdown source or the number of characters in the generated HTML.

**Comment by PuttItOut** [comment]
Fixed
