### ISSUE TITLE
Rape Content

### ISSUE THREAD

**Issue by baank** [voat/voat#824]
So is this what Voat is all about ?

https://www.voat.co/v/Rape/comments/414645
https://www.voat.co/v/Rape/comments/341208

**Comment by teran-mckinney** [comment]
If you like to browse /v/Rape, that's probably what you'll find.

Feel free to browse other subverses.

**Comment by atomGit** [comment]
> Feel free to browse other subverses.

... or better yet, feel free to not open a bullshit ticket and return to your home at reddit

**Comment by DeliciousRaspberryPi** [comment]
We're pleased to see that you've noticed Voat prioritizes actual free speech.  We don't agree with their message, either.


> "The trouble with fighting for human freedom is that one spends most of one's time defending scoundrels. For it is against scoundrels that oppressive laws are first aimed, and oppression must be stopped at the beginning if it is to be stopped at all."  - H. L. Mencken


> “I believe there are more instances of the abridgment of the freedom of the people by gradual and silent encroachments of those in power than by violent and sudden usurpations.” - James Madison


> “Because if you don't stand up for the stuff you don't like, when they come for the stuff you do like, you've already lost.”  - Neil Gaiman


> “Whoever would overthrow the liberty of a nation must begin by subduing the freeness of speech.”  - Benjamin Franklin

We have to protect all the speech people want to have in our community.  That includes FPH, Coontown, Rape, and others.  I despise them all too, but they have a right to talk.

**Comment by monoxane** [comment]
>We have to protect all the speech people want to have in our community. That includes FPH, Coontown, Rape, and others. I despise them all too, but they have a right to talk.

Seconded

**Comment by kfroemming** [comment]
Agreed. I think it's disgusting but I will defend their right to speak.
