### ISSUE TITLE
Site is completely unresponsive and I can't log into or use my account

### ISSUE THREAD

**Issue by 0x4F** [voat/voat#828]
Clicking Login from the homepage does nothing. I have to click Submit a Link while logged out and then log in from there. Once logged in, however, nothing works; when I try to open the My Subverses menu to access a list of my subscriptions, the link goes nowhere and only shows an "anchor" in the address bar (I think this is the right term for it -- it looks like **voat.co/#**).  That same "anchor" thing happens when I click on any of the default subs in the header while logged out. It just redirects to an empty nowhere link and fails to do anything.

I cannot up- or down-voat anything, I can't post, I can't reply to comments or read heavily nested replies (like when you click "Load more comments" or "_x_ reply/replies" in a particular conversation within the general thread). Also, a bizarre thing happens to my screen when switching between subs or attempting to submit links or selfposts: My screen actually **fades to black** for a second, like a scene change in a movie or a slide change in PowerPoint. It's almost like the entire site is a static image that I can't interact with. This has never happened before in the whole half-year I've been a member, and I'm worried that something is wrong. I know it can't be a shadow ban, because why would I be completely unable to click any links even to read them while logged out?

I PMed the mods at voatdev but am leaving this ticket here too as a backup. I hope someone didn't put a malicious script or something in the backend. Other people seem to be posting OK, but I can't ask any questions on Voat itself to see if anyone else has been having this problem, because I can't login properly or submit any posts! Please help!

**Comment by voat** [comment]
Are you still having this issue? Please try clearing your browser cache and cookies and report back.
