### ISSUE TITLE
Reduce the amount of code clutter by splitting up HomeController god object.

### ISSUE THREAD

**Issue by AdamHess** [voat/voat#829]
The home controller is handling a dozen or more different routes. It makes both your development capability and time extremely painful having a single "god" object for all your routes. Additionally, splitting it up and using MVC _conventions over configuration_  makes your code easier to write and would allow you reduce the size of your route table (Which is unessesarily huge) 

A good example is creating a HelpController 

https://github.com/voat/voat/blob/master/Voat/Voat.UI/Controllers/HomeController.cs#L611

instead of handling all of your routes manually, you can rely on CONVENTION to have your content served up and generalize your code. 

Another good example are the lines of code right above that: 

https://github.com/voat/voat/blob/master/Voat/Voat.UI/Controllers/HomeController.cs#L607

using MVC would mean you would just need to do: 

```
return View();
```

instead of 

```
  return View("~/Views/Welcome/Welcome.cshtml");
```

which is more prone to error. (not to mention more typing)

**Comment by voat** [comment]
Thanks for your comment. We'll definitely need to refactor a lot of things, but for now this is not a priority while the new API is in development. The entire UI will most likely be refactored to consume the new API and most controllers will be heavily slimmed down as a result.

**Comment by kfroemming** [comment]
Hey Voat team, is there a repo for the new api? I see the current one is currently built in Jquery, however I think a great alternative would be Angular or React.

**Comment by ghost** [comment]
@voat when will the new API be deployed?

**Comment by PuttItOut** [comment]
This still needs to be done but Closing as code has changed significantly since issue logged.
