### ISSUE TITLE
Use Consistent C# coding conventions

### ISSUE THREAD

**Issue by AdamHess** [voat/voat#830]
https://github.com/voat/voat/blob/4baa0cce7ebd9f5e01ed3cd79235f37532d33673/Voat/Voat.Data/Models/voatEntities.cs#L11

Notice the lowercase voatEntities

the programming convention for C# is that Objects _Always_  start with a capital.

**Comment by voat** [comment]
Thank you for reporting this. This should be the only case as this was an autogenerated class, but we'll check the entire solution asap and refactor.
