### ISSUE TITLE
"Voat is under heavy load" error

### ISSUE THREAD

**Issue by victorrest** [voat/voat#832]
Hi Voat,
Firstly, i really like your site, Voat is so much better and user-friendly than reddit. I want to test your open source code from github, but when i try installed to my Windows 2012 vps with IIS8 i everytime get "Voat is under heavy load. Please try again in a few minutes." error.

Can you help me what i made wrong? Maybe the operation system is the problem, or what? I set the databases and everything what you wrote on github, but nothing. Please help me if you can. Thank you developers, and congratulations to the Voat!

**Comment by voat** [comment]
Hi, this error is always caused when there are problems communicating with one of the databases. Please make sure your databases are properly setup, check your connection strings and run the solution in debug mode to pinpoint where exactly the exception is thrown.
