### ISSUE TITLE
Use BitHub to encourage commits

### ISSUE THREAD

**Issue by mikalehmann** [voat/voat#834]
https://github.com/WhisperSystems/BitHub
"BitHub is a service that will automatically pay a percentage of Bitcoin funds for every submission to a GitHub repository."

I also suggest making the donation to this fund optional. If you implement a way to let people pay monthly, they should get an option to pay for development, which should add to this fund. By default this option should be set to 0 and they can increase it if they want.

**Comment by PuttItOut** [comment]
Closed as this is not a planned change.
