### ISSUE TITLE
Missing dbo.Submission.[RelativeRank] column on SqlScrips schemas

### ISSUE THREAD

**Issue by leonardobaggio** [voat/voat#837]
#### **Scenario:**

I've downloaded the current "voat-master" branch, and after getting everything configured at web.config and the databases ok, the front page was displaying the "error/heavyload " message and was not possible to see anything at front page, neither in any other submission based page. 

Others pages like, user settings, registration, etc was working fine.

By setting a breakpoint at the Global.asax's **Application_Error** method , I could see that was an exception occurring UserHelper.cs:543 (probably the first database call):

> An exception of type 'System.Data.Entity.Core.EntityCommandExecutionException' occurred in EntityFramework.SqlServer.dll but was not handled in user code
> 
> Additional information: An error occurred while executing the command definition. See the inner exception for details.

Inner exception:

> {"Invalid column name 'RelativeRank'."}

Taking a further look, comparing the VoatEntityDataModel.edmx and the [voat] database, I could conclude that this column was missing from the files at **SqlScripts** folder. (I've added the column manually and everything started to work fine)
#### **Q:**

**Did I miss something during the setup?** 
_If not, how can it be solved at the master branch?_
_If it was a merging issue, how can it be fixed and avoided?_

_ps.: Sorry if I described it in an excessively exhaustive manner, I don't usually collaborate with open source projects._

**Comment by voat** [comment]
Hi, it doesn't look like you missed anything during the setup. We need to update the script to include the missing column.

**Comment by farybagj** [comment]
Bump! The script still haven't been updated... (I'm also missing RelativeRank column...)

As a result its displayed:
Voat is under heavy load. Please try again in a few minutes.
And the side bar is not loaded...

To fix it (without the proper script) just go to the DB: voat/Tables/dbo.Submission table and add a the missing column manually... (I made it as a float with default value 0 and can marked it optional)

**Comment by PuttItOut** [comment]
Fixed. Current Schema files are in DEV branch
