### ISSUE TITLE
Potential caching issue

### ISSUE THREAD

**Issue by MagicalBlob** [voat/voat#840]
I just got served a page with night mode when I have night mode disabled in my settings. The night mode is limited to that page and the account that is displayed on it as being logged on is mine, however the subverse list on the top bar is not mine, so there's a mix of the page I should be seeing and someone else's.

screenshot:
![image](https://cloud.githubusercontent.com/assets/6509486/16127016/9938d130-33f2-11e6-96ae-110908c559a2.png)

EDIT:
happened again
![image](https://cloud.githubusercontent.com/assets/6509486/16254689/7dd807de-383a-11e6-80a0-88f628744c95.png)

**Comment by PuttItOut** [comment]
Fixed
