### ISSUE TITLE
"Sorry, this link has already been submitted recently." link is not clickable

### ISSUE THREAD

**Issue by mikalehmann** [voat/voat#848]
The link after this message is not clickable. I have to copy it into my address bar to access the post.

Why was the redirecting removed?

**Comment by PuttItOut** [comment]
Closed as this is not a planned feature.

**Comment by mikalehmann** [comment]
Is it that hard to implement? This would only need an extra `<a>`, right?

**Comment by mikalehmann** [comment]
If you choose to ignore me, I'll just open a post on /v/voatdev. And another one, and another one... until this is implemented. At least explain to me why my proposal is shit.
