### ISSUE TITLE
applicationhost.config and NuGet package reinstall

### ISSUE THREAD

**Issue by fvanzee** [voat/voat#850]
I'm pretty new on working on open source projects and I am running into some issues with changes and what to commit to git.

These are the actions I'm executing:
- Fork the project
- Clone the fork
- Open solution in Visual Studio (Update 3)
- Update-Package -reinstall (no to all for overwrite)

First when I open the project in Visual Studio it immediately changes the applicationhost.config (sets web.config path), that is expected. Though it does add it to the git changes overview. I don't want this change to be committed. I read something about this issue just being introduced after Update 2, although I like to check if there is anything I should do differently here. Should I just run `git update-index --assume-unchaged`  on this file?

Next when I update the packages, it does some actions I don't expect. 
- Updates the packages.config for Business, Tests, and UI. It sets the target framework from 4.5.2 to 4.5.1. The project target frameworks are 4.5.1 so it seems correct. Do the project target frameworks need to be changed? Or the packages.config records be set to 4.5.1?
- Adds a bunch of .js files under UI/Scripts. Although these files are already under UI/Scripts/libs. These new files seem unnecessary.
- Adds themes/base under UI/Content. Also this seems unnecessary.

Am I doing something wrong here? Sorry if so. I've tried to find similar issues, but could not find any.

**Comment by PuttItOut** [comment]
The DEV branch should have most of these issues addressed.
