### ISSUE TITLE
So is voat dead?

### ISSUE THREAD

**Issue by lloydjatkinson** [voat/voat#887]
No commits in over a year.

**Comment by MagicalBlob** [comment]
# Developers hate him!
## Hide your commits with this one simple trick!

![image](https://cloud.githubusercontent.com/assets/6509486/24014342/7a7c11d8-0a7c-11e7-8045-82d7fc1268ae.png)

![image](https://cloud.githubusercontent.com/assets/6509486/24014349/80318338-0a7c-11e7-8a15-302d221ee02f.png)

**Comment by ghost** [comment]
Oh damn, that's a ton of commits am I rite

**Comment by ChillyHellion** [comment]
DanielFlamino, probably the best comment I've seen on Github.
