### ISSUE TITLE
Voat does not run on an open platform

### ISSUE THREAD

**Issue by Zer0-** [voat/voat#892]
To run Voat currently you need a Windows and SQL Server license. This adds significant cost to hosting as well as reducing hosting options among other numerous drawbacks compared to supporting an open platform.

**Comment by AdamHess** [comment]
Consider switching to .NET core and MySQL entity framework DOES support MySQL database. 

I'd even recommend looking into code first with migrations to make switching databases easier.  

Also this will significantly drop your hosting costs to switch from windows to linux.

**Comment by alex9099** [comment]
I agree

**Comment by voat** [comment]
This is currently in progress: 

https://github.com/voat/voat/tree/Core
