### ISSUE TITLE
voat.sql is seems out dated

### ISSUE THREAD

**Issue by chufy** [voat/voat#900]
Invalid column name 'IsArchived'.
Invalid column name 'IsArchived'.
Invalid column name 'Votes'.
Invalid column name 'LinkDescription'.

We installed it local server but got these errors. Is there any updated or working SQL for installing Voat?

**Comment by PuttItOut** [comment]
Hey chufy,

Please make sure you are using the correct branch. master is out of date and stale. Use Dev for live site or PostgreSQL or Core for the current port branches. 

Let me know if this isn't the issue.

**Comment by chufy** [comment]
Ah! I have been used "master" branch.  I'll try "dev" and let you know :) Thank you. 👍

**Comment by chufy** [comment]
By the way how can I have admin permission when I installed it? There is haven't any documentation :/

**Comment by ghost** [comment]
If you mean making an user an admin, there is no such thing, all users have the same permissions. Admin tasks are done directly on the database using your database user and password and executing SQL queries.

**Comment by chufy** [comment]
I understand, seems so I need to learn SQL :) A newbie question. if there is no any admin account when someone reported another user who can see these reports. How can we suspend any user and delete posts or topics? Could you please give some information about these features and if these are done with SQL queries could you please give some examples? Thanks for your kindly interests :)

**Comment by ghost** [comment]
Voat uses a public subverse for receiving reports: https://voat.co/v/ReportSpammers

For deleting something in subverses your user account does not moderate you have to set the "IsDeleted" column of the submission in the database (table "dbo"."Submission") to 1 (if using SQL Server) or True (if using PostgreSql) and change the value of "Content" to something like "[Deleted]".

For banning an user you have to insert a new row in the "dbo"."BannedUser" table.

Both things must be done using SQL but you can get some GUI management tool for doing this without having to write SQL queries. You can get pgAdmin 4 if you are using PostgreSQL or SQL Server Management Studio if you are using SQL Server.

**Comment by chufy** [comment]
Thanks for your patience and kindly answers 👍 then first of all I need to learn SQL. Actually Fuzzy, I don't have good knowledge about Windows Servers and SQLs but I want to use Voat on my local town as a website. We are 2 collage students and I will hire a freelancer for install Voat on a windows server :/ Could you please give me an advice which servers are best for starting. You can give a specific web hosting provider.

**Comment by ghost** [comment]
I'm sorry but that's not my area of expertise. I could run Voat on a computer with as few as 2GB of RAM but I definitely don't recommend that to host a web server. I hope someone with experience on those topics can recomend you a good web hosting provider.
