### ISSUE TITLE
SQL queries for managing things.

### ISSUE THREAD

**Issue by chufy** [voat/voat#901]
~~Hello, I've installed fresh Voat on Windows Server. Created the first user but I can't create any subverse because Voat wants 10 CCP for creating a subverse. But at the start, there is no any subverse or post that we can earn CCP. I tried to create subverse with SQL queries but it didn't work. After that tried to give CCP to my user and it didn't work too.  Could you please show me a way to create first subverses.~~

### I've found Web.config answers for all things above

My second question is if there is no any admin account on Voat, how we manage things like create ads, **adding badges** and feature sub.

Thanks, sorry for newbie questions :)

http://46.4.99.19/s/Front@bosbakan is not working.

~~and still don't know how to edit subverse. "bosbakan" user is creater of the sub but moderator is "YouCanClaimThisSub" and I don't know how can I change this, I can't change anything on this sub.~~

**Solution: If you set your Web.config correctly and create subverse with using website instead database it works like a charm.**

## But still http://46.4.99.19/s/Front@bosbakan is not working.

and

**Comment by husleuujii** [comment]
bro how did u installed your Core branch
