### ISSUE TITLE
voat.co is read only!!

### ISSUE THREAD

**Issue by ghost** [voat/voat#916]
Last new post was 12 hours ago. Cannot comment or vote.

Did the disk on the database fill up?

**Comment by danuker** [comment]
It looks like this is fixed now.

https://www.voat.co/v/announcements/2306193

> P.S. We had a technical issue earlier today and had a few hours of downtime while we fixed it.

**Comment by ghost** [comment]
Ha, yeah it was like this some time ago, then again yesterday. Will close for now, thank you!
